package dspss_tniu_interrupt_tniu_pkg;

    //===========================================================================
    // user defined parameters — driven by INTR_TNIU_* macros from interrupt_tniu_define.sv
    //===========================================================================
    localparam integer unsigned OVERFLOW_TGT_ID         = `dspss_tniu_INTR_TNIU_OVERFLOW_TGT_ID;
    localparam integer unsigned OVERFLOW_TGT_INTR_ID    = `dspss_tniu_INTR_TNIU_OVERFLOW_TGT_INTR_ID;
    localparam integer unsigned TIMER_COUNT              = `dspss_tniu_INTR_TNIU_TIMER_COUNT;

    //===========================================================================
    // event recorder parameters
    //===========================================================================
    localparam integer unsigned TIMER_COUNT_WIDTH        = $clog2(TIMER_COUNT);
    localparam integer unsigned NIU_ID_WIDTH             = `dspss_tniu_INTR_TNIU_NIU_ID_WIDTH;
    localparam integer unsigned INTR_ID_WIDTH            = `dspss_tniu_INTR_TNIU_INTR_ID_WIDTH;
    localparam integer unsigned INTR_RAW_BASE_ADDR       = `dspss_tniu_INTR_TNIU_RAW_BASE_ADDR;
    localparam integer unsigned INTR_MERGE_MASK_BASE_ADDR = `dspss_tniu_INTR_TNIU_MERGE_MASK_BASE_ADDR;
    localparam integer unsigned INTR_PULSE_MODE_BASE_ADDR = `dspss_tniu_INTR_TNIU_PULSE_MODE_BASE_ADDR;
    localparam integer unsigned INTR_SET_BASE_ADDR       = `dspss_tniu_INTR_TNIU_SET_BASE_ADDR;
    localparam integer unsigned INTR_CLR_BASE_ADDR       = `dspss_tniu_INTR_TNIU_CLR_BASE_ADDR;
    localparam integer unsigned INTR_INTERNAL_BASE_ADDR  = `dspss_tniu_INTR_TNIU_INTERNAL_BASE_ADDR;
    localparam integer unsigned INTR_CONFLICT_BASE_ADDR  = `dspss_tniu_INTR_TNIU_CONFLICT_BASE_ADDR;
    localparam integer unsigned INTERNAL_INTR_NUM        = `dspss_tniu_INTR_TNIU_INTERNAL_INTR_NUM;

    localparam integer unsigned EVENT_COUNT_MAX     = `dspss_tniu_INTR_TNIU_EVENT_COUNT_MAX;
    localparam integer unsigned EVENT_COUNT_WIDTH   = $clog2(EVENT_COUNT_MAX);
    localparam integer unsigned CONTEXT_NUM         = `dspss_tniu_INTR_TNIU_CONTEXT_NUM;
    localparam integer unsigned CONTEXT_NUM_WIDTH   = $clog2(CONTEXT_NUM);

    localparam integer unsigned EVENT_REQ     = `dspss_tniu_INTR_TNIU_EVENT_REQ;
    localparam integer unsigned APB_REQ       = `dspss_tniu_INTR_TNIU_APB_REQ;

    localparam integer unsigned INTERNAL_OVERFLOW_ERROR_ID      = `dspss_tniu_INTR_TNIU_INTERNAL_OVERFLOW_ERROR_ID;
    localparam integer unsigned INTERNAL_ECC_ERROR_ID           = `dspss_tniu_INTR_TNIU_INTERNAL_ECC_ERROR_ID;
    localparam integer unsigned INTERNAL_CONFLICT_ERROR_ID      = `dspss_tniu_INTR_TNIU_INTERNAL_CONFLICT_ERROR_ID;
    localparam integer unsigned INTERNAL_TGT_ID_ERROR_ID        = `dspss_tniu_INTR_TNIU_INTERNAL_TGT_ID_ERROR_ID;
    localparam integer unsigned INTERNAL_TGT_INTR_ID_ERROR_ID   = `dspss_tniu_INTR_TNIU_INTERNAL_TGT_INTR_ID_ERROR_ID;


    typedef struct packed{

        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic                              toggle_flag;
    } intr_repeater_pkg;

    typedef struct packed{
        logic                              srcid;
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic [CONTEXT_NUM_WIDTH-1:0]      context_id; // used to indicate the context ID
    } event_apb_arb_pkg;

    typedef struct packed{
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic [CONTEXT_NUM_WIDTH-1:0]      context_id; // used to indicate the context ID
    } event_pkg;

    typedef struct packed{
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
    } lut_pkg;

    typedef struct packed{
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
        logic [$clog2($bits(lut_pkg))-1:0] ecc; // used to indicate the interrupt address
    } ecc_pkg;



endpackage
