//[UHDL]Content Start [md5:88c33008cf78ab99c811e3c4ea9b50e3]
-f $INTR_RING_REQ_SINK_OUT_DIR/filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ring_sink_station.v
-f $INTR_RING_BUF_OUT_DIR/filelist.f
-f $INTR_INIU_TOP_OUT_DIR/intr_iniu_top_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/soc_intr_xbar_routing_lut_w8_c1.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_50_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ddr5_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_49_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ddr4_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_48_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ddr3_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_47_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ddr2_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_46_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ddr1_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_45_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ddr0_iniu_node_top_wrap.v
-f $INTR_TNIU_TOP_OUT_DIR/intr_tniu_top_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_44_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/npu_ss4_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_43_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/npu_ss4_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_42_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/mcu_ss_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_41_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/mcu_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_40_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/pcie_eth_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_39_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/ufs_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_38_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/camera_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_37_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/gpu_ss0_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_36_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/peri_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_35_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/npu_ss3_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/SocIntrNodeIdGen_node_id_value_34_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/npu_ss3_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_dn_harden_wrap/soc_intr_ring_noc_dn_harden_wrap.v
//[UHDL]Content End [md5:88c33008cf78ab99c811e3c4ea9b50e3]

