//[UHDL]Content Start [md5:4be95efe5207bcbd407d18765ab51c84]
-f $INTR_RING_REQ_SINK_OUT_DIR/filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/ring_sink_station.v
-f $INTR_RING_BUF_OUT_DIR/filelist.f
-f $INTR_INIU_TOP_OUT_DIR/intr_iniu_top_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/soc_intr_xbar_routing_lut_w8_c1.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_36_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/pcie_eth_ss_iniu_node_top_wrap.v
-f $INTR_TNIU_TOP_OUT_DIR/intr_tniu_top_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_7_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/display_ss_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_6_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/dp_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_5_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/gpu_ss1_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_4_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/gpu_ss0_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_3_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/peri_ss_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_2_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/audio_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_1_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/ucie_ss0_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/SocIntrNodeIdGen_node_id_value_0_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/cpu_ss_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc_up_harden_wrap/soc_intr_ring_noc_up_harden_wrap.v
//[UHDL]Content End [md5:4be95efe5207bcbd407d18765ab51c84]

