`define dti_iniu_top_display_ss_INIU_ROUTE_BASE 19
`define dti_iniu_top_display_ss_PAYLOAD_WIDTH 90
`define dti_iniu_top_display_ss_TBU_NUM 1
`define dti_iniu_top_display_ss_TID_WIDTH 6
`define dti_iniu_top_display_ss_TRANSACTION_MAX_NUM 8
