package gpu_ss0_tniu_interrupt_tniu_pkg;

    //===========================================================================
    // user defined parameters
    //===========================================================================
    localparam integer unsigned OVERFLOW_TGT_ID         = 0;
    localparam integer unsigned OVERFLOW_TGT_INTR_ID    = 0;
    localparam integer unsigned TIMER_COUNT    = 10;

    //===========================================================================
    // event recorder parameters
    //===========================================================================
    localparam integer unsigned TIMER_COUNT_WIDTH    = $clog2(TIMER_COUNT);
    localparam integer unsigned NIU_ID_WIDTH        = 8;
    localparam integer unsigned INTR_ID_WIDTH       = 12;
    localparam integer unsigned INTR_RAW_BASE_ADDR  = 32'h0;
    localparam integer unsigned INTR_MERGE_MASK_BASE_ADDR  = 32'h200;
    localparam integer unsigned INTR_PULSE_MODE_BASE_ADDR  = 32'h600;
    localparam integer unsigned INTR_SET_BASE_ADDR  = 32'h1000;
    localparam integer unsigned INTR_CLR_BASE_ADDR  = 32'h1200;
    localparam integer unsigned INTR_INTERNAL_BASE_ADDR  = 32'h1400;
    localparam integer unsigned INTR_CONFLICT_BASE_ADDR  = 32'h4000;
    localparam integer unsigned INTERNAL_INTR_NUM    = 32;

    localparam integer unsigned EVENT_COUNT_MAX     = 16;
    localparam integer unsigned EVENT_COUNT_WIDTH   = $clog2(EVENT_COUNT_MAX);
    localparam integer unsigned CONTEXT_NUM         = 16;
    localparam integer unsigned CONTEXT_NUM_WIDTH   = $clog2(CONTEXT_NUM);

    localparam integer unsigned EVENT_REQ     = 0;
    localparam integer unsigned APB_REQ       = 1;

    localparam integer unsigned INTERNAL_OVERFLOW_ERROR_ID          = 0;
    localparam integer unsigned INTERNAL_ECC_ERROR_ID               = 1;
    localparam integer unsigned INTERNAL_CONFLICT_ERROR_ID          = 2;
    localparam integer unsigned INTERNAL_TGT_ID_ERROR_ID            = 3;
    localparam integer unsigned INTERNAL_TGT_INTR_ID_ERROR_ID       = 4;


    typedef struct packed{

        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic                              toggle_flag;
    } intr_repeater_pkg;

    typedef struct packed{
        logic                              srcid;
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic [CONTEXT_NUM_WIDTH-1:0]      context_id; // used to indicate the context ID
    } event_apb_arb_pkg;

    typedef struct packed{
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic [CONTEXT_NUM_WIDTH-1:0]      context_id; // used to indicate the context ID
    } event_pkg;

    typedef struct packed{
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
    } lut_pkg;

    typedef struct packed{
        // logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
        logic [$clog2($bits(lut_pkg))-1:0] ecc; // used to indicate the interrupt address
    } ecc_pkg;



endpackage
