`define dti_iniu_top_dspss4_INIU_ROUTE_BASE 13
`define dti_iniu_top_dspss4_PAYLOAD_WIDTH 90
`define dti_iniu_top_dspss4_TBU_NUM 1
`define dti_iniu_top_dspss4_TID_WIDTH 6
`define dti_iniu_top_dspss4_TRANSACTION_MAX_NUM 8
