`ifdef ATB_FUNNEL_FIXED_HOLD_TIME
    `undef ATB_FUNNEL_FIXED_HOLD_TIME
`endif

`ifdef ATB_FUNNEL_FIXED_CONFIGURATION
    `undef ATB_FUNNEL_FIXED_CONFIGURATION
`endif

`ifdef ATB_FUNNEL_DATA0_WIDTH
    `undef ATB_FUNNEL_DATA0_WIDTH
`endif

`ifdef ATB_FUNNEL_HOLD_WIDTH
    `undef ATB_FUNNEL_HOLD_WIDTH
`endif

`ifdef ATB_FUNNEL_N_ATB
    `undef ATB_FUNNEL_N_ATB
`endif

`ifdef ATB_NETWORK_ERR_INT_CNT_WIDTH
    `undef ATB_NETWORK_ERR_INT_CNT_WIDTH
`endif

`ifdef ATB_NETWORK_SYNC_STAGE
    `undef ATB_NETWORK_SYNC_STAGE
`endif

`ifdef ATB_NETWORK_FIFO_DEPTH
    `undef ATB_NETWORK_FIFO_DEPTH
`endif

`ifdef _PREFIX_
    `undef _PREFIX_
`endif
