// Common dependencies: fcip + lwnoc_lowpower_component
// Compiled ONCE by the top-level Makefile. Per-block filelists do NOT include
// this file (isolation model). No EXCLUDE_FOUNDATION_IP guard needed here.
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_arb_matrix.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_arb_vrp.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_fix_arb.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_grant_gen_fp.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_grant_gen_rr.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_mtx_gen_age.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_mtx_gen_plru_tree.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_tree_plru_comb.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_arb_vr_matrix.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_age_matrix_list.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_age_matrix.sv
$INTR_NOC_DIR/fcip/ip/arbiter/fcip_arb_vrp_matrix.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_afifo.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_afifo_mst.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_afifo_slv.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_apb_afifo.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_axi_afifo/fcip_axi_afifo_mst.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_axi_afifo/fcip_axi_afifo_slv.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_axi_afifo/fcip_axi_afifo.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_req_rsp_afifo_mst.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_req_rsp_afifo_slv.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_req_rsp_afifo.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_afifo_doub.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_afifo_mst_doub.sv
$INTR_NOC_DIR/fcip/ip/async_fifo/fcip_afifo_slv_doub.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_bin2onehot.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_booth_wallace_mul.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_ip_mimo_queue.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_lead_one.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_lead_one_msb.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_lead_one_rev.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_lfsr4.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_list_lead_one.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_list_lead_one_rev.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_onehot2bin.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_real_mux_onehot.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_rob_id_dec.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_rob_prealloc.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_onehot_demux.sv
$INTR_NOC_DIR/fcip/ip/basic/fcip_onehot_mux_pld.sv
$INTR_NOC_DIR/fcip/ip/mem_model/fcip_dpram_model.sv
$INTR_NOC_DIR/fcip/ip/mem_model/fcip_spram_model.sv
$INTR_NOC_DIR/fcip/ip/memory/mem_fake_2p_sram/fcip_mem_fake_find_new_bit.sv
$INTR_NOC_DIR/fcip/ip/memory/mem_fake_2p_sram/fcip_mem_fake_write_buffer.sv
$INTR_NOC_DIR/fcip/ip/memory/mem_fake_2p_sram/fcip_mem_fake_2p_mem.sv
$INTR_NOC_DIR/fcip/ip/memory/fcip_mem_ctrl_wrap/fcip_mem_ctrl_wrap.sv
$INTR_NOC_DIR/fcip/ip/regslice/fcip_reg_slice.sv
$INTR_NOC_DIR/fcip/ip/regslice/fcip_reg_slice_full_set.sv
$INTR_NOC_DIR/fcip/ip/stdcell_wrap/fcip_marker.sv
$INTR_NOC_DIR/fcip/ip/stdcell_wrap/fcip_clk_marker.sv
$INTR_NOC_DIR/fcip/ip/stdcell_wrap/fcip_data_pipe.sv
$INTR_NOC_DIR/fcip/ip/stdcell_wrap/fcip_sync_arst.sv
$INTR_NOC_DIR/fcip/ip/stdcell_wrap/fcip_sync_aset.sv
$INTR_NOC_DIR/fcip/ip/stdcell_wrap/fcip_sync_cell.sv
$INTR_NOC_DIR/fcip/ip/sync_fifo/fcip_sync_fifo_reg.sv
$INTR_NOC_DIR/fcip/ip/sync_fifo/fcip_sync_fifo_reg_mimo.sv
$INTR_NOC_DIR/fcip/ip/sync_fifo/fcip_sync_fifo_spram/fcip_sfifo_spram_ctrl.sv
$INTR_NOC_DIR/fcip/ip/sync_fifo/fcip_sync_fifo_spram/fcip_sfifo_spram_rob.sv
$INTR_NOC_DIR/fcip/ip/sync_fifo/fcip_sync_fifo_spram/fcip_sfifo_spram_ptr_ctrl.sv
$INTR_NOC_DIR/fcip/ip/sync_fifo/fcip_sync_fifo_spram/fcip_sync_fifo_spram.sv
$INTR_NOC_DIR/fcip/ip/handshake/fcip_hs_fanout.sv
$INTR_NOC_DIR/fcip/tb/fcip_top.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lwnoc_lp_define_package.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lwnoc_lp_struct_package.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lwnoc_lp_endpoint.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lwnoc_lp_nest.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lwnoc_lp_slv_adapter.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lwnoc_lp_slv_wrapper.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lp_fsm/lwnoc_lp_stg2_fsm.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lp_fsm/lwnoc_lp_stg1_fsm.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_common/lp_fsm/lwnoc_lp_niu_fsm.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_hub/lwnoc_lp_subhub.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_hub/lwnoc_lp_hub_3terminal.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_hub/lwnoc_lp_hub_tiny_wrapper.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_hub/lwnoc_lp_hub_small_wrapper.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_hub/lwnoc_lp_hub_large_wrapper.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_hub/lwnoc_lp_hub_wrapper.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_tniu/lwnoc_lp_tniu_async_bridge.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_tniu/lwnoc_lp_tniu_func_tniu.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_tniu/lwnoc_lp_tniu_func_iniu.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_tniu/lwnoc_lp_tniu_dummy_mst.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_tniu/lwnoc_lp_tniu_default_slv.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_tniu/lwnoc_lp_tniu_stall_logic.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_iniu/lwnoc_lp_pchn_niu.sv
$INTR_NOC_DIR/lwnoc_lowpower_component/src/rtl/lp_iniu/lwnoc_lp_iniu.sv

