//[UHDL]Content Start [md5:67b3037e243d582e7f46a3a15f146e17]
module atb_soc_top_wrap (
	output         atb_up_harden_dsp_ss0_top_node_sync_ctrl_porting_dsp_ss0_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_up_harden_dsp_ss0_top_node_sync_ctrl_porting_dsp_ss0_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_up_harden_dsp_ss0_top_node_lp_afifo_rx_porting_dsp_ss0_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_up_harden_dsp_ss0_top_node_lp_afifo_tx_porting_dsp_ss0_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_up_harden_dsp_ss0_top_node_lp_rx_porting_dsp_ss0_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_up_harden_dsp_ss0_top_node_lp_tx_porting_dsp_ss0_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_up_harden_dsp_ss0_top_node_timeout_val_porting_dsp_ss0_top_node_timeout_val_porting_timeout_val                                  ,
	output         atb_up_harden_dsp_ss1_top_node_sync_ctrl_porting_dsp_ss1_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_up_harden_dsp_ss1_top_node_sync_ctrl_porting_dsp_ss1_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_up_harden_dsp_ss1_top_node_lp_afifo_rx_porting_dsp_ss1_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_up_harden_dsp_ss1_top_node_lp_afifo_tx_porting_dsp_ss1_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_up_harden_dsp_ss1_top_node_lp_rx_porting_dsp_ss1_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_up_harden_dsp_ss1_top_node_lp_tx_porting_dsp_ss1_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_up_harden_dsp_ss1_top_node_timeout_val_porting_dsp_ss1_top_node_timeout_val_porting_timeout_val                                  ,
	output         atb_up_harden_dsp_ss2_top_node_sync_ctrl_porting_dsp_ss2_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_up_harden_dsp_ss2_top_node_sync_ctrl_porting_dsp_ss2_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_up_harden_dsp_ss2_top_node_lp_afifo_rx_porting_dsp_ss2_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_up_harden_dsp_ss2_top_node_lp_afifo_tx_porting_dsp_ss2_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_up_harden_dsp_ss2_top_node_lp_rx_porting_dsp_ss2_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_up_harden_dsp_ss2_top_node_lp_tx_porting_dsp_ss2_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_up_harden_dsp_ss2_top_node_timeout_val_porting_dsp_ss2_top_node_timeout_val_porting_timeout_val                                  ,
	output         atb_up_harden_dsp_ss3_top_node_sync_ctrl_porting_dsp_ss3_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_up_harden_dsp_ss3_top_node_sync_ctrl_porting_dsp_ss3_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_up_harden_dsp_ss3_top_node_lp_afifo_rx_porting_dsp_ss3_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_up_harden_dsp_ss3_top_node_lp_afifo_tx_porting_dsp_ss3_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_up_harden_dsp_ss3_top_node_lp_rx_porting_dsp_ss3_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_up_harden_dsp_ss3_top_node_lp_tx_porting_dsp_ss3_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_up_harden_dsp_ss3_top_node_timeout_val_porting_dsp_ss3_top_node_timeout_val_porting_timeout_val                                  ,
	output         atb_up_harden_dsp_ss4_top_node_sync_ctrl_porting_dsp_ss4_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_up_harden_dsp_ss4_top_node_sync_ctrl_porting_dsp_ss4_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_up_harden_dsp_ss4_top_node_lp_afifo_rx_porting_dsp_ss4_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_up_harden_dsp_ss4_top_node_lp_afifo_tx_porting_dsp_ss4_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_up_harden_dsp_ss4_top_node_lp_rx_porting_dsp_ss4_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_up_harden_dsp_ss4_top_node_lp_tx_porting_dsp_ss4_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_up_harden_dsp_ss4_top_node_timeout_val_porting_dsp_ss4_top_node_timeout_val_porting_timeout_val                                  ,
	output         atb_up_harden_dsp_ss5_top_node_sync_ctrl_porting_dsp_ss5_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_up_harden_dsp_ss5_top_node_sync_ctrl_porting_dsp_ss5_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_up_harden_dsp_ss5_top_node_lp_afifo_rx_porting_dsp_ss5_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_up_harden_dsp_ss5_top_node_lp_afifo_tx_porting_dsp_ss5_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_up_harden_dsp_ss5_top_node_lp_rx_porting_dsp_ss5_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_up_harden_dsp_ss5_top_node_lp_tx_porting_dsp_ss5_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_up_harden_dsp_ss5_top_node_timeout_val_porting_dsp_ss5_top_node_timeout_val_porting_timeout_val                                  ,
	input          atb_up_harden_left_funnel_node_atreadym_porting_left_funnel_node_atreadym_porting_atreadym                                           ,
	input          atb_up_harden_left_funnel_node_afvalidm_porting_left_funnel_node_afvalidm_porting_afvalidm                                           ,
	input          atb_up_harden_left_funnel_node_syncreqm_porting_left_funnel_node_syncreqm_porting_syncreqm                                           ,
	output         atb_up_harden_left_funnel_node_atvalidm_porting_left_funnel_node_atvalidm_porting_atvalidm                                           ,
	output         atb_up_harden_left_funnel_node_afreadym_porting_left_funnel_node_afreadym_porting_afreadym                                           ,
	output [6:0]   atb_up_harden_left_funnel_node_atidm_porting_left_funnel_node_atidm_porting_atidm                                                    ,
	output [127:0] atb_up_harden_left_funnel_node_atdatam_porting_left_funnel_node_atdatam_porting_atdatam                                              ,
	output [3:0]   atb_up_harden_left_funnel_node_atbytesm_porting_left_funnel_node_atbytesm_porting_atbytesm                                           ,
	input          atb_up_harden_left_funnel_node_pclkendbg_porting_left_funnel_node_pclkendbg_porting_pclkendbg                                        ,
	input          atb_up_harden_left_funnel_node_pseldbg_porting_left_funnel_node_pseldbg_porting_pseldbg                                              ,
	input          atb_up_harden_left_funnel_node_penabledbg_porting_left_funnel_node_penabledbg_porting_penabledbg                                     ,
	input          atb_up_harden_left_funnel_node_pwritedbg_porting_left_funnel_node_pwritedbg_porting_pwritedbg                                        ,
	input          atb_up_harden_left_funnel_node_paddrdbg31_porting_left_funnel_node_paddrdbg31_porting_paddrdbg31                                     ,
	input  [9:0]   atb_up_harden_left_funnel_node_paddrdbg_porting_left_funnel_node_paddrdbg_porting_paddrdbg                                           ,
	input  [31:0]  atb_up_harden_left_funnel_node_pwdatadbg_porting_left_funnel_node_pwdatadbg_porting_pwdatadbg                                        ,
	output         atb_up_harden_left_funnel_node_preadydbg_porting_left_funnel_node_preadydbg_porting_preadydbg                                        ,
	output         atb_up_harden_left_funnel_node_pslverrdbg_porting_left_funnel_node_pslverrdbg_porting_pslverrdbg                                     ,
	output [31:0]  atb_up_harden_left_funnel_node_prdatadbg_porting_left_funnel_node_prdatadbg_porting_prdatadbg                                        ,
	input          atb_up_harden_async_bridge_slv_node_slv_clk_porting_async_bridge_slv_node_slv_clk_porting_clk_atb_s                                  ,
	input          atb_up_harden_async_bridge_slv_node_slv_rst_n_porting_async_bridge_slv_node_slv_rst_n_porting_rstn_atb_s                             ,
	input          atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_afready                                    ,
	output         atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_afvalid                                    ,
	input  [2:0]   atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atbytes                                    ,
	input  [63:0]  atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atdata                                     ,
	input  [6:0]   atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atid                                       ,
	output         atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atready                                    ,
	input          atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atvalid                                    ,
	input          atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atwakeup                                   ,
	output         atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_syncreq                                    ,
	output         atb_up_harden_async_bridge_slv_node_afifo_slv_full_zero_porting_async_bridge_slv_node_afifo_slv_full_zero_porting_afifo_slv_full_zero,
	input          atb_up_harden_async_bridge_slv_node_flush_req_porting_async_bridge_slv_node_flush_req_porting_flush_req                              ,
	input          atb_dn_harden_async_bridge_mst_node_mst_clk_porting_async_bridge_mst_node_mst_clk_porting_clk_atb_m                                  ,
	input          atb_dn_harden_async_bridge_mst_node_mst_rst_n_porting_async_bridge_mst_node_mst_rst_n_porting_rstn_atb_m                             ,
	output         atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_afready                                    ,
	input          atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_afvalid                                    ,
	output [2:0]   atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atbytes                                    ,
	output [63:0]  atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atdata                                     ,
	output [6:0]   atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atid                                       ,
	input          atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atready                                    ,
	output         atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atvalid                                    ,
	output         atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atwakeup                                   ,
	input          atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_syncreq                                    ,
	output         atb_dn_harden_async_bridge_mst_node_afifo_mst_full_zero_porting_async_bridge_mst_node_afifo_mst_full_zero_porting_afifo_mst_full_zero,
	output         atb_dn_harden_async_bridge_mst_node_afifo_mst_read_idle_porting_async_bridge_mst_node_afifo_mst_read_idle_porting_afifo_mst_read_idle,
	output         atb_dn_harden_async_bridge_mst_node_flush_req_level_porting_async_bridge_mst_node_flush_req_level_porting_flush_req_level            ,
	input          atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_afready                                  ,
	output         atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_afvalid                                  ,
	input  [3:0]   atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atbytes                                  ,
	input  [127:0] atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atdata                                   ,
	input  [6:0]   atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atid                                     ,
	output         atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atready                                  ,
	input          atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atvalid                                  ,
	input          atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atwakeup                                 ,
	output         atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_syncreq                                  ,
	input          atb_dn_harden_right_funnel_node_atreadym_porting_right_funnel_node_atreadym_porting_atreadym                                         ,
	input          atb_dn_harden_right_funnel_node_afvalidm_porting_right_funnel_node_afvalidm_porting_afvalidm                                         ,
	input          atb_dn_harden_right_funnel_node_syncreqm_porting_right_funnel_node_syncreqm_porting_syncreqm                                         ,
	output         atb_dn_harden_right_funnel_node_atvalidm_porting_right_funnel_node_atvalidm_porting_atvalidm                                         ,
	output         atb_dn_harden_right_funnel_node_afreadym_porting_right_funnel_node_afreadym_porting_afreadym                                         ,
	output [6:0]   atb_dn_harden_right_funnel_node_atidm_porting_right_funnel_node_atidm_porting_atidm                                                  ,
	output [127:0] atb_dn_harden_right_funnel_node_atdatam_porting_right_funnel_node_atdatam_porting_atdatam                                            ,
	output [3:0]   atb_dn_harden_right_funnel_node_atbytesm_porting_right_funnel_node_atbytesm_porting_atbytesm                                         ,
	input          atb_dn_harden_right_funnel_node_pclkendbg_porting_right_funnel_node_pclkendbg_porting_pclkendbg                                      ,
	input          atb_dn_harden_right_funnel_node_pseldbg_porting_right_funnel_node_pseldbg_porting_pseldbg                                            ,
	input          atb_dn_harden_right_funnel_node_penabledbg_porting_right_funnel_node_penabledbg_porting_penabledbg                                   ,
	input          atb_dn_harden_right_funnel_node_pwritedbg_porting_right_funnel_node_pwritedbg_porting_pwritedbg                                      ,
	input          atb_dn_harden_right_funnel_node_paddrdbg31_porting_right_funnel_node_paddrdbg31_porting_paddrdbg31                                   ,
	input  [9:0]   atb_dn_harden_right_funnel_node_paddrdbg_porting_right_funnel_node_paddrdbg_porting_paddrdbg                                         ,
	input  [31:0]  atb_dn_harden_right_funnel_node_pwdatadbg_porting_right_funnel_node_pwdatadbg_porting_pwdatadbg                                      ,
	output         atb_dn_harden_right_funnel_node_preadydbg_porting_right_funnel_node_preadydbg_porting_preadydbg                                      ,
	output         atb_dn_harden_right_funnel_node_pslverrdbg_porting_right_funnel_node_pslverrdbg_porting_pslverrdbg                                   ,
	output [31:0]  atb_dn_harden_right_funnel_node_prdatadbg_porting_right_funnel_node_prdatadbg_porting_prdatadbg                                      ,
	output         atb_dn_harden_camera_ss_top_node_sync_ctrl_porting_camera_ss_top_node_sync_ctrl_porting_flush_req_level                              ,
	output         atb_dn_harden_camera_ss_top_node_sync_ctrl_porting_camera_ss_top_node_sync_ctrl_porting_syncreq_level                                ,
	input  [12:0]  atb_dn_harden_camera_ss_top_node_lp_afifo_rx_porting_camera_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                         ,
	output [12:0]  atb_dn_harden_camera_ss_top_node_lp_afifo_tx_porting_camera_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                         ,
	input  [142:0] atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_pld_sync                                   ,
	output [15:0]  atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_rptr_async                                 ,
	output [15:0]  atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_rptr_sync                                  ,
	input  [15:0]  atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_wptr_async                                 ,
	input  [12:0]  atb_dn_harden_camera_ss_top_node_lp_rx_porting_camera_ss_top_node_lp_rx_porting_lw_rx_req                                            ,
	output [12:0]  atb_dn_harden_camera_ss_top_node_lp_tx_porting_camera_ss_top_node_lp_tx_porting_lw_tx_req                                            ,
	input  [9:0]   atb_dn_harden_camera_ss_top_node_timeout_val_porting_camera_ss_top_node_timeout_val_porting_timeout_val                              ,
	output         atb_dn_harden_mipi_ss_top_node_sync_ctrl_porting_mipi_ss_top_node_sync_ctrl_porting_flush_req_level                                  ,
	output         atb_dn_harden_mipi_ss_top_node_sync_ctrl_porting_mipi_ss_top_node_sync_ctrl_porting_syncreq_level                                    ,
	input  [12:0]  atb_dn_harden_mipi_ss_top_node_lp_afifo_rx_porting_mipi_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                             ,
	output [12:0]  atb_dn_harden_mipi_ss_top_node_lp_afifo_tx_porting_mipi_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                             ,
	input  [142:0] atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_pld_sync                                       ,
	output [15:0]  atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_rptr_async                                     ,
	output [15:0]  atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_rptr_sync                                      ,
	input  [15:0]  atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_wptr_async                                     ,
	input  [12:0]  atb_dn_harden_mipi_ss_top_node_lp_rx_porting_mipi_ss_top_node_lp_rx_porting_lw_rx_req                                                ,
	output [12:0]  atb_dn_harden_mipi_ss_top_node_lp_tx_porting_mipi_ss_top_node_lp_tx_porting_lw_tx_req                                                ,
	input  [9:0]   atb_dn_harden_mipi_ss_top_node_timeout_val_porting_mipi_ss_top_node_timeout_val_porting_timeout_val                                  ,
	input          atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_afready                                  ,
	output         atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_afvalid                                  ,
	input  [3:0]   atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atbytes                                  ,
	input  [127:0] atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atdata                                   ,
	input  [6:0]   atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atid                                     ,
	output         atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atready                                  ,
	input          atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atvalid                                  ,
	input          atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atwakeup                                 ,
	output         atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_syncreq                                  ,
	input          atb_dn_harden_debug_tniu_ss_top_node_flush_req_porting_debug_tniu_ss_top_node_flush_req_porting_flush_req                            ,
	output [142:0] atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_pld_sync                           ,
	input  [15:0]  atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_rptr_async                         ,
	input  [15:0]  atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_rptr_sync                          ,
	output [15:0]  atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_wptr_async                         ,
	input          atb_dn_harden_debug_tniu_ss_top_node_syncreq_level_porting_debug_tniu_ss_top_node_syncreq_level_porting_syncreq_level                ,
	input  [12:0]  atb_dn_harden_debug_tniu_ss_top_node_lp_lw_porting_debug_tniu_ss_top_node_lp_lw_porting_lw_rx_req                                    ,
	output [12:0]  atb_dn_harden_debug_tniu_ss_top_node_lp_lw_porting_debug_tniu_ss_top_node_lp_lw_porting_lw_tx_req                                    ,
	input  [12:0]  atb_dn_harden_debug_tniu_ss_top_node_lp_afifo_porting_debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_rx_req                       ,
	output [12:0]  atb_dn_harden_debug_tniu_ss_top_node_lp_afifo_porting_debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_tx_req                       ,
	input  [9:0]   atb_dn_harden_debug_tniu_ss_top_node_timeout_val_porting_debug_tniu_ss_top_node_timeout_val_porting_timeout_val                      ,
	input          u_dn_harden_clk_dn_func_porting                                                                                                      ,
	input          u_dn_harden_rst_dn_func_n_porting                                                                                                    );

	//Wire define for this module.

	//Wire define for sub module.
	wire [15:0] u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_rptr_async   ;
	wire [15:0] u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_rptr_sync    ;
	wire        u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_syncreq_level;
	wire [77:0] u_up_harden_TO_u_dn_harden_SIG_async_bridge_slv_node_sync_porting_pld_sync     ;
	wire [15:0] u_up_harden_TO_u_dn_harden_SIG_async_bridge_slv_node_sync_porting_wptr_async   ;

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	atb_up_harden u_up_harden (
		.clk_up_func(u_dn_harden_clk_dn_func_porting),
		.rst_up_func_n(u_dn_harden_rst_dn_func_n_porting),
		.dsp_ss0_top_node_sync_ctrl_porting_flush_req_level(atb_up_harden_dsp_ss0_top_node_sync_ctrl_porting_dsp_ss0_top_node_sync_ctrl_porting_flush_req_level),
		.dsp_ss0_top_node_sync_ctrl_porting_syncreq_level(atb_up_harden_dsp_ss0_top_node_sync_ctrl_porting_dsp_ss0_top_node_sync_ctrl_porting_syncreq_level),
		.dsp_ss0_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_up_harden_dsp_ss0_top_node_lp_afifo_rx_porting_dsp_ss0_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.dsp_ss0_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_up_harden_dsp_ss0_top_node_lp_afifo_tx_porting_dsp_ss0_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.dsp_ss0_top_node_async_fifo_porting_pld_sync(atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_pld_sync),
		.dsp_ss0_top_node_async_fifo_porting_rptr_async(atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_rptr_async),
		.dsp_ss0_top_node_async_fifo_porting_rptr_sync(atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_rptr_sync),
		.dsp_ss0_top_node_async_fifo_porting_wptr_async(atb_up_harden_dsp_ss0_top_node_async_fifo_porting_dsp_ss0_top_node_async_fifo_porting_wptr_async),
		.dsp_ss0_top_node_lp_rx_porting_lw_rx_req(atb_up_harden_dsp_ss0_top_node_lp_rx_porting_dsp_ss0_top_node_lp_rx_porting_lw_rx_req),
		.dsp_ss0_top_node_lp_tx_porting_lw_tx_req(atb_up_harden_dsp_ss0_top_node_lp_tx_porting_dsp_ss0_top_node_lp_tx_porting_lw_tx_req),
		.dsp_ss0_top_node_timeout_val_porting_timeout_val(atb_up_harden_dsp_ss0_top_node_timeout_val_porting_dsp_ss0_top_node_timeout_val_porting_timeout_val),
		.dsp_ss1_top_node_sync_ctrl_porting_flush_req_level(atb_up_harden_dsp_ss1_top_node_sync_ctrl_porting_dsp_ss1_top_node_sync_ctrl_porting_flush_req_level),
		.dsp_ss1_top_node_sync_ctrl_porting_syncreq_level(atb_up_harden_dsp_ss1_top_node_sync_ctrl_porting_dsp_ss1_top_node_sync_ctrl_porting_syncreq_level),
		.dsp_ss1_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_up_harden_dsp_ss1_top_node_lp_afifo_rx_porting_dsp_ss1_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.dsp_ss1_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_up_harden_dsp_ss1_top_node_lp_afifo_tx_porting_dsp_ss1_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.dsp_ss1_top_node_async_fifo_porting_pld_sync(atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_pld_sync),
		.dsp_ss1_top_node_async_fifo_porting_rptr_async(atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_rptr_async),
		.dsp_ss1_top_node_async_fifo_porting_rptr_sync(atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_rptr_sync),
		.dsp_ss1_top_node_async_fifo_porting_wptr_async(atb_up_harden_dsp_ss1_top_node_async_fifo_porting_dsp_ss1_top_node_async_fifo_porting_wptr_async),
		.dsp_ss1_top_node_lp_rx_porting_lw_rx_req(atb_up_harden_dsp_ss1_top_node_lp_rx_porting_dsp_ss1_top_node_lp_rx_porting_lw_rx_req),
		.dsp_ss1_top_node_lp_tx_porting_lw_tx_req(atb_up_harden_dsp_ss1_top_node_lp_tx_porting_dsp_ss1_top_node_lp_tx_porting_lw_tx_req),
		.dsp_ss1_top_node_timeout_val_porting_timeout_val(atb_up_harden_dsp_ss1_top_node_timeout_val_porting_dsp_ss1_top_node_timeout_val_porting_timeout_val),
		.dsp_ss2_top_node_sync_ctrl_porting_flush_req_level(atb_up_harden_dsp_ss2_top_node_sync_ctrl_porting_dsp_ss2_top_node_sync_ctrl_porting_flush_req_level),
		.dsp_ss2_top_node_sync_ctrl_porting_syncreq_level(atb_up_harden_dsp_ss2_top_node_sync_ctrl_porting_dsp_ss2_top_node_sync_ctrl_porting_syncreq_level),
		.dsp_ss2_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_up_harden_dsp_ss2_top_node_lp_afifo_rx_porting_dsp_ss2_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.dsp_ss2_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_up_harden_dsp_ss2_top_node_lp_afifo_tx_porting_dsp_ss2_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.dsp_ss2_top_node_async_fifo_porting_pld_sync(atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_pld_sync),
		.dsp_ss2_top_node_async_fifo_porting_rptr_async(atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_rptr_async),
		.dsp_ss2_top_node_async_fifo_porting_rptr_sync(atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_rptr_sync),
		.dsp_ss2_top_node_async_fifo_porting_wptr_async(atb_up_harden_dsp_ss2_top_node_async_fifo_porting_dsp_ss2_top_node_async_fifo_porting_wptr_async),
		.dsp_ss2_top_node_lp_rx_porting_lw_rx_req(atb_up_harden_dsp_ss2_top_node_lp_rx_porting_dsp_ss2_top_node_lp_rx_porting_lw_rx_req),
		.dsp_ss2_top_node_lp_tx_porting_lw_tx_req(atb_up_harden_dsp_ss2_top_node_lp_tx_porting_dsp_ss2_top_node_lp_tx_porting_lw_tx_req),
		.dsp_ss2_top_node_timeout_val_porting_timeout_val(atb_up_harden_dsp_ss2_top_node_timeout_val_porting_dsp_ss2_top_node_timeout_val_porting_timeout_val),
		.dsp_ss3_top_node_sync_ctrl_porting_flush_req_level(atb_up_harden_dsp_ss3_top_node_sync_ctrl_porting_dsp_ss3_top_node_sync_ctrl_porting_flush_req_level),
		.dsp_ss3_top_node_sync_ctrl_porting_syncreq_level(atb_up_harden_dsp_ss3_top_node_sync_ctrl_porting_dsp_ss3_top_node_sync_ctrl_porting_syncreq_level),
		.dsp_ss3_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_up_harden_dsp_ss3_top_node_lp_afifo_rx_porting_dsp_ss3_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.dsp_ss3_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_up_harden_dsp_ss3_top_node_lp_afifo_tx_porting_dsp_ss3_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.dsp_ss3_top_node_async_fifo_porting_pld_sync(atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_pld_sync),
		.dsp_ss3_top_node_async_fifo_porting_rptr_async(atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_rptr_async),
		.dsp_ss3_top_node_async_fifo_porting_rptr_sync(atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_rptr_sync),
		.dsp_ss3_top_node_async_fifo_porting_wptr_async(atb_up_harden_dsp_ss3_top_node_async_fifo_porting_dsp_ss3_top_node_async_fifo_porting_wptr_async),
		.dsp_ss3_top_node_lp_rx_porting_lw_rx_req(atb_up_harden_dsp_ss3_top_node_lp_rx_porting_dsp_ss3_top_node_lp_rx_porting_lw_rx_req),
		.dsp_ss3_top_node_lp_tx_porting_lw_tx_req(atb_up_harden_dsp_ss3_top_node_lp_tx_porting_dsp_ss3_top_node_lp_tx_porting_lw_tx_req),
		.dsp_ss3_top_node_timeout_val_porting_timeout_val(atb_up_harden_dsp_ss3_top_node_timeout_val_porting_dsp_ss3_top_node_timeout_val_porting_timeout_val),
		.dsp_ss4_top_node_sync_ctrl_porting_flush_req_level(atb_up_harden_dsp_ss4_top_node_sync_ctrl_porting_dsp_ss4_top_node_sync_ctrl_porting_flush_req_level),
		.dsp_ss4_top_node_sync_ctrl_porting_syncreq_level(atb_up_harden_dsp_ss4_top_node_sync_ctrl_porting_dsp_ss4_top_node_sync_ctrl_porting_syncreq_level),
		.dsp_ss4_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_up_harden_dsp_ss4_top_node_lp_afifo_rx_porting_dsp_ss4_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.dsp_ss4_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_up_harden_dsp_ss4_top_node_lp_afifo_tx_porting_dsp_ss4_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.dsp_ss4_top_node_async_fifo_porting_pld_sync(atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_pld_sync),
		.dsp_ss4_top_node_async_fifo_porting_rptr_async(atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_rptr_async),
		.dsp_ss4_top_node_async_fifo_porting_rptr_sync(atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_rptr_sync),
		.dsp_ss4_top_node_async_fifo_porting_wptr_async(atb_up_harden_dsp_ss4_top_node_async_fifo_porting_dsp_ss4_top_node_async_fifo_porting_wptr_async),
		.dsp_ss4_top_node_lp_rx_porting_lw_rx_req(atb_up_harden_dsp_ss4_top_node_lp_rx_porting_dsp_ss4_top_node_lp_rx_porting_lw_rx_req),
		.dsp_ss4_top_node_lp_tx_porting_lw_tx_req(atb_up_harden_dsp_ss4_top_node_lp_tx_porting_dsp_ss4_top_node_lp_tx_porting_lw_tx_req),
		.dsp_ss4_top_node_timeout_val_porting_timeout_val(atb_up_harden_dsp_ss4_top_node_timeout_val_porting_dsp_ss4_top_node_timeout_val_porting_timeout_val),
		.dsp_ss5_top_node_sync_ctrl_porting_flush_req_level(atb_up_harden_dsp_ss5_top_node_sync_ctrl_porting_dsp_ss5_top_node_sync_ctrl_porting_flush_req_level),
		.dsp_ss5_top_node_sync_ctrl_porting_syncreq_level(atb_up_harden_dsp_ss5_top_node_sync_ctrl_porting_dsp_ss5_top_node_sync_ctrl_porting_syncreq_level),
		.dsp_ss5_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_up_harden_dsp_ss5_top_node_lp_afifo_rx_porting_dsp_ss5_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.dsp_ss5_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_up_harden_dsp_ss5_top_node_lp_afifo_tx_porting_dsp_ss5_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.dsp_ss5_top_node_async_fifo_porting_pld_sync(atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_pld_sync),
		.dsp_ss5_top_node_async_fifo_porting_rptr_async(atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_rptr_async),
		.dsp_ss5_top_node_async_fifo_porting_rptr_sync(atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_rptr_sync),
		.dsp_ss5_top_node_async_fifo_porting_wptr_async(atb_up_harden_dsp_ss5_top_node_async_fifo_porting_dsp_ss5_top_node_async_fifo_porting_wptr_async),
		.dsp_ss5_top_node_lp_rx_porting_lw_rx_req(atb_up_harden_dsp_ss5_top_node_lp_rx_porting_dsp_ss5_top_node_lp_rx_porting_lw_rx_req),
		.dsp_ss5_top_node_lp_tx_porting_lw_tx_req(atb_up_harden_dsp_ss5_top_node_lp_tx_porting_dsp_ss5_top_node_lp_tx_porting_lw_tx_req),
		.dsp_ss5_top_node_timeout_val_porting_timeout_val(atb_up_harden_dsp_ss5_top_node_timeout_val_porting_dsp_ss5_top_node_timeout_val_porting_timeout_val),
		.left_funnel_node_atreadym_porting_atreadym(atb_up_harden_left_funnel_node_atreadym_porting_left_funnel_node_atreadym_porting_atreadym),
		.left_funnel_node_afvalidm_porting_afvalidm(atb_up_harden_left_funnel_node_afvalidm_porting_left_funnel_node_afvalidm_porting_afvalidm),
		.left_funnel_node_syncreqm_porting_syncreqm(atb_up_harden_left_funnel_node_syncreqm_porting_left_funnel_node_syncreqm_porting_syncreqm),
		.left_funnel_node_atvalidm_porting_atvalidm(atb_up_harden_left_funnel_node_atvalidm_porting_left_funnel_node_atvalidm_porting_atvalidm),
		.left_funnel_node_afreadym_porting_afreadym(atb_up_harden_left_funnel_node_afreadym_porting_left_funnel_node_afreadym_porting_afreadym),
		.left_funnel_node_atidm_porting_atidm(atb_up_harden_left_funnel_node_atidm_porting_left_funnel_node_atidm_porting_atidm),
		.left_funnel_node_atdatam_porting_atdatam(atb_up_harden_left_funnel_node_atdatam_porting_left_funnel_node_atdatam_porting_atdatam),
		.left_funnel_node_atbytesm_porting_atbytesm(atb_up_harden_left_funnel_node_atbytesm_porting_left_funnel_node_atbytesm_porting_atbytesm),
		.left_funnel_node_pclkendbg_porting_pclkendbg(atb_up_harden_left_funnel_node_pclkendbg_porting_left_funnel_node_pclkendbg_porting_pclkendbg),
		.left_funnel_node_pseldbg_porting_pseldbg(atb_up_harden_left_funnel_node_pseldbg_porting_left_funnel_node_pseldbg_porting_pseldbg),
		.left_funnel_node_penabledbg_porting_penabledbg(atb_up_harden_left_funnel_node_penabledbg_porting_left_funnel_node_penabledbg_porting_penabledbg),
		.left_funnel_node_pwritedbg_porting_pwritedbg(atb_up_harden_left_funnel_node_pwritedbg_porting_left_funnel_node_pwritedbg_porting_pwritedbg),
		.left_funnel_node_paddrdbg31_porting_paddrdbg31(atb_up_harden_left_funnel_node_paddrdbg31_porting_left_funnel_node_paddrdbg31_porting_paddrdbg31),
		.left_funnel_node_paddrdbg_porting_paddrdbg(atb_up_harden_left_funnel_node_paddrdbg_porting_left_funnel_node_paddrdbg_porting_paddrdbg),
		.left_funnel_node_pwdatadbg_porting_pwdatadbg(atb_up_harden_left_funnel_node_pwdatadbg_porting_left_funnel_node_pwdatadbg_porting_pwdatadbg),
		.left_funnel_node_preadydbg_porting_preadydbg(atb_up_harden_left_funnel_node_preadydbg_porting_left_funnel_node_preadydbg_porting_preadydbg),
		.left_funnel_node_pslverrdbg_porting_pslverrdbg(atb_up_harden_left_funnel_node_pslverrdbg_porting_left_funnel_node_pslverrdbg_porting_pslverrdbg),
		.left_funnel_node_prdatadbg_porting_prdatadbg(atb_up_harden_left_funnel_node_prdatadbg_porting_left_funnel_node_prdatadbg_porting_prdatadbg),
		.async_bridge_slv_node_slv_clk_porting_clk_atb_s(atb_up_harden_async_bridge_slv_node_slv_clk_porting_async_bridge_slv_node_slv_clk_porting_clk_atb_s),
		.async_bridge_slv_node_slv_rst_n_porting_rstn_atb_s(atb_up_harden_async_bridge_slv_node_slv_rst_n_porting_async_bridge_slv_node_slv_rst_n_porting_rstn_atb_s),
		.async_bridge_slv_node_s_chan_porting_s_afready(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_afready),
		.async_bridge_slv_node_s_chan_porting_s_afvalid(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_afvalid),
		.async_bridge_slv_node_s_chan_porting_s_atbytes(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atbytes),
		.async_bridge_slv_node_s_chan_porting_s_atdata(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atdata),
		.async_bridge_slv_node_s_chan_porting_s_atid(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atid),
		.async_bridge_slv_node_s_chan_porting_s_atready(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atready),
		.async_bridge_slv_node_s_chan_porting_s_atvalid(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atvalid),
		.async_bridge_slv_node_s_chan_porting_s_atwakeup(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_atwakeup),
		.async_bridge_slv_node_s_chan_porting_s_syncreq(atb_up_harden_async_bridge_slv_node_s_chan_porting_async_bridge_slv_node_s_chan_porting_s_syncreq),
		.async_bridge_slv_node_sync_porting_pld_sync(u_up_harden_TO_u_dn_harden_SIG_async_bridge_slv_node_sync_porting_pld_sync),
		.async_bridge_slv_node_sync_porting_rptr_async(u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_rptr_async),
		.async_bridge_slv_node_sync_porting_rptr_sync(u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_rptr_sync),
		.async_bridge_slv_node_sync_porting_syncreq_level(u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_syncreq_level),
		.async_bridge_slv_node_sync_porting_wptr_async(u_up_harden_TO_u_dn_harden_SIG_async_bridge_slv_node_sync_porting_wptr_async),
		.async_bridge_slv_node_afifo_slv_full_zero_porting_afifo_slv_full_zero(atb_up_harden_async_bridge_slv_node_afifo_slv_full_zero_porting_async_bridge_slv_node_afifo_slv_full_zero_porting_afifo_slv_full_zero),
		.async_bridge_slv_node_flush_req_porting_flush_req(atb_up_harden_async_bridge_slv_node_flush_req_porting_async_bridge_slv_node_flush_req_porting_flush_req));
	atb_dn_harden u_dn_harden (
		.clk_dn_func(u_dn_harden_clk_dn_func_porting),
		.rst_dn_func_n(u_dn_harden_rst_dn_func_n_porting),
		.async_bridge_mst_node_mst_clk_porting_clk_atb_m(atb_dn_harden_async_bridge_mst_node_mst_clk_porting_async_bridge_mst_node_mst_clk_porting_clk_atb_m),
		.async_bridge_mst_node_mst_rst_n_porting_rstn_atb_m(atb_dn_harden_async_bridge_mst_node_mst_rst_n_porting_async_bridge_mst_node_mst_rst_n_porting_rstn_atb_m),
		.async_bridge_mst_node_m_chan_porting_m_afready(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_afready),
		.async_bridge_mst_node_m_chan_porting_m_afvalid(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_afvalid),
		.async_bridge_mst_node_m_chan_porting_m_atbytes(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atbytes),
		.async_bridge_mst_node_m_chan_porting_m_atdata(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atdata),
		.async_bridge_mst_node_m_chan_porting_m_atid(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atid),
		.async_bridge_mst_node_m_chan_porting_m_atready(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atready),
		.async_bridge_mst_node_m_chan_porting_m_atvalid(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atvalid),
		.async_bridge_mst_node_m_chan_porting_m_atwakeup(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_atwakeup),
		.async_bridge_mst_node_m_chan_porting_m_syncreq(atb_dn_harden_async_bridge_mst_node_m_chan_porting_async_bridge_mst_node_m_chan_porting_m_syncreq),
		.async_bridge_mst_node_sync_porting_pld_sync(u_up_harden_TO_u_dn_harden_SIG_async_bridge_slv_node_sync_porting_pld_sync),
		.async_bridge_mst_node_sync_porting_rptr_async(u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_rptr_async),
		.async_bridge_mst_node_sync_porting_rptr_sync(u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_rptr_sync),
		.async_bridge_mst_node_sync_porting_syncreq_level(u_dn_harden_TO_u_up_harden_SIG_async_bridge_mst_node_sync_porting_syncreq_level),
		.async_bridge_mst_node_sync_porting_wptr_async(u_up_harden_TO_u_dn_harden_SIG_async_bridge_slv_node_sync_porting_wptr_async),
		.async_bridge_mst_node_afifo_mst_full_zero_porting_afifo_mst_full_zero(atb_dn_harden_async_bridge_mst_node_afifo_mst_full_zero_porting_async_bridge_mst_node_afifo_mst_full_zero_porting_afifo_mst_full_zero),
		.async_bridge_mst_node_afifo_mst_read_idle_porting_afifo_mst_read_idle(atb_dn_harden_async_bridge_mst_node_afifo_mst_read_idle_porting_async_bridge_mst_node_afifo_mst_read_idle_porting_afifo_mst_read_idle),
		.async_bridge_mst_node_flush_req_level_porting_flush_req_level(atb_dn_harden_async_bridge_mst_node_flush_req_level_porting_async_bridge_mst_node_flush_req_level_porting_flush_req_level),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_afready(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_afready),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_afvalid(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_afvalid),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_atbytes(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atbytes),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_atdata(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atdata),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_atid(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atid),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_atready(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atready),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_atvalid(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atvalid),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_atwakeup(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_atwakeup),
		.right_agg_agg_node_ch2_chan_porting_ch2_m_syncreq(atb_dn_harden_right_agg_agg_node_ch2_chan_porting_right_agg_agg_node_ch2_chan_porting_ch2_m_syncreq),
		.right_funnel_node_atreadym_porting_atreadym(atb_dn_harden_right_funnel_node_atreadym_porting_right_funnel_node_atreadym_porting_atreadym),
		.right_funnel_node_afvalidm_porting_afvalidm(atb_dn_harden_right_funnel_node_afvalidm_porting_right_funnel_node_afvalidm_porting_afvalidm),
		.right_funnel_node_syncreqm_porting_syncreqm(atb_dn_harden_right_funnel_node_syncreqm_porting_right_funnel_node_syncreqm_porting_syncreqm),
		.right_funnel_node_atvalidm_porting_atvalidm(atb_dn_harden_right_funnel_node_atvalidm_porting_right_funnel_node_atvalidm_porting_atvalidm),
		.right_funnel_node_afreadym_porting_afreadym(atb_dn_harden_right_funnel_node_afreadym_porting_right_funnel_node_afreadym_porting_afreadym),
		.right_funnel_node_atidm_porting_atidm(atb_dn_harden_right_funnel_node_atidm_porting_right_funnel_node_atidm_porting_atidm),
		.right_funnel_node_atdatam_porting_atdatam(atb_dn_harden_right_funnel_node_atdatam_porting_right_funnel_node_atdatam_porting_atdatam),
		.right_funnel_node_atbytesm_porting_atbytesm(atb_dn_harden_right_funnel_node_atbytesm_porting_right_funnel_node_atbytesm_porting_atbytesm),
		.right_funnel_node_pclkendbg_porting_pclkendbg(atb_dn_harden_right_funnel_node_pclkendbg_porting_right_funnel_node_pclkendbg_porting_pclkendbg),
		.right_funnel_node_pseldbg_porting_pseldbg(atb_dn_harden_right_funnel_node_pseldbg_porting_right_funnel_node_pseldbg_porting_pseldbg),
		.right_funnel_node_penabledbg_porting_penabledbg(atb_dn_harden_right_funnel_node_penabledbg_porting_right_funnel_node_penabledbg_porting_penabledbg),
		.right_funnel_node_pwritedbg_porting_pwritedbg(atb_dn_harden_right_funnel_node_pwritedbg_porting_right_funnel_node_pwritedbg_porting_pwritedbg),
		.right_funnel_node_paddrdbg31_porting_paddrdbg31(atb_dn_harden_right_funnel_node_paddrdbg31_porting_right_funnel_node_paddrdbg31_porting_paddrdbg31),
		.right_funnel_node_paddrdbg_porting_paddrdbg(atb_dn_harden_right_funnel_node_paddrdbg_porting_right_funnel_node_paddrdbg_porting_paddrdbg),
		.right_funnel_node_pwdatadbg_porting_pwdatadbg(atb_dn_harden_right_funnel_node_pwdatadbg_porting_right_funnel_node_pwdatadbg_porting_pwdatadbg),
		.right_funnel_node_preadydbg_porting_preadydbg(atb_dn_harden_right_funnel_node_preadydbg_porting_right_funnel_node_preadydbg_porting_preadydbg),
		.right_funnel_node_pslverrdbg_porting_pslverrdbg(atb_dn_harden_right_funnel_node_pslverrdbg_porting_right_funnel_node_pslverrdbg_porting_pslverrdbg),
		.right_funnel_node_prdatadbg_porting_prdatadbg(atb_dn_harden_right_funnel_node_prdatadbg_porting_right_funnel_node_prdatadbg_porting_prdatadbg),
		.camera_ss_top_node_sync_ctrl_porting_flush_req_level(atb_dn_harden_camera_ss_top_node_sync_ctrl_porting_camera_ss_top_node_sync_ctrl_porting_flush_req_level),
		.camera_ss_top_node_sync_ctrl_porting_syncreq_level(atb_dn_harden_camera_ss_top_node_sync_ctrl_porting_camera_ss_top_node_sync_ctrl_porting_syncreq_level),
		.camera_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_dn_harden_camera_ss_top_node_lp_afifo_rx_porting_camera_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.camera_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_dn_harden_camera_ss_top_node_lp_afifo_tx_porting_camera_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.camera_ss_top_node_async_fifo_porting_pld_sync(atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_pld_sync),
		.camera_ss_top_node_async_fifo_porting_rptr_async(atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_rptr_async),
		.camera_ss_top_node_async_fifo_porting_rptr_sync(atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_rptr_sync),
		.camera_ss_top_node_async_fifo_porting_wptr_async(atb_dn_harden_camera_ss_top_node_async_fifo_porting_camera_ss_top_node_async_fifo_porting_wptr_async),
		.camera_ss_top_node_lp_rx_porting_lw_rx_req(atb_dn_harden_camera_ss_top_node_lp_rx_porting_camera_ss_top_node_lp_rx_porting_lw_rx_req),
		.camera_ss_top_node_lp_tx_porting_lw_tx_req(atb_dn_harden_camera_ss_top_node_lp_tx_porting_camera_ss_top_node_lp_tx_porting_lw_tx_req),
		.camera_ss_top_node_timeout_val_porting_timeout_val(atb_dn_harden_camera_ss_top_node_timeout_val_porting_camera_ss_top_node_timeout_val_porting_timeout_val),
		.mipi_ss_top_node_sync_ctrl_porting_flush_req_level(atb_dn_harden_mipi_ss_top_node_sync_ctrl_porting_mipi_ss_top_node_sync_ctrl_porting_flush_req_level),
		.mipi_ss_top_node_sync_ctrl_porting_syncreq_level(atb_dn_harden_mipi_ss_top_node_sync_ctrl_porting_mipi_ss_top_node_sync_ctrl_porting_syncreq_level),
		.mipi_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req(atb_dn_harden_mipi_ss_top_node_lp_afifo_rx_porting_mipi_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.mipi_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req(atb_dn_harden_mipi_ss_top_node_lp_afifo_tx_porting_mipi_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.mipi_ss_top_node_async_fifo_porting_pld_sync(atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_pld_sync),
		.mipi_ss_top_node_async_fifo_porting_rptr_async(atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_rptr_async),
		.mipi_ss_top_node_async_fifo_porting_rptr_sync(atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_rptr_sync),
		.mipi_ss_top_node_async_fifo_porting_wptr_async(atb_dn_harden_mipi_ss_top_node_async_fifo_porting_mipi_ss_top_node_async_fifo_porting_wptr_async),
		.mipi_ss_top_node_lp_rx_porting_lw_rx_req(atb_dn_harden_mipi_ss_top_node_lp_rx_porting_mipi_ss_top_node_lp_rx_porting_lw_rx_req),
		.mipi_ss_top_node_lp_tx_porting_lw_tx_req(atb_dn_harden_mipi_ss_top_node_lp_tx_porting_mipi_ss_top_node_lp_tx_porting_lw_tx_req),
		.mipi_ss_top_node_timeout_val_porting_timeout_val(atb_dn_harden_mipi_ss_top_node_timeout_val_porting_mipi_ss_top_node_timeout_val_porting_timeout_val),
		.debug_tniu_ss_top_node_s_chan_porting_s_afready(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_afready),
		.debug_tniu_ss_top_node_s_chan_porting_s_afvalid(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_afvalid),
		.debug_tniu_ss_top_node_s_chan_porting_s_atbytes(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atbytes),
		.debug_tniu_ss_top_node_s_chan_porting_s_atdata(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atdata),
		.debug_tniu_ss_top_node_s_chan_porting_s_atid(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atid),
		.debug_tniu_ss_top_node_s_chan_porting_s_atready(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atready),
		.debug_tniu_ss_top_node_s_chan_porting_s_atvalid(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atvalid),
		.debug_tniu_ss_top_node_s_chan_porting_s_atwakeup(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_atwakeup),
		.debug_tniu_ss_top_node_s_chan_porting_s_syncreq(atb_dn_harden_debug_tniu_ss_top_node_s_chan_porting_debug_tniu_ss_top_node_s_chan_porting_s_syncreq),
		.debug_tniu_ss_top_node_flush_req_porting_flush_req(atb_dn_harden_debug_tniu_ss_top_node_flush_req_porting_debug_tniu_ss_top_node_flush_req_porting_flush_req),
		.debug_tniu_ss_top_node_async_fifo_porting_pld_sync(atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_pld_sync),
		.debug_tniu_ss_top_node_async_fifo_porting_rptr_async(atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_rptr_async),
		.debug_tniu_ss_top_node_async_fifo_porting_rptr_sync(atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_rptr_sync),
		.debug_tniu_ss_top_node_async_fifo_porting_wptr_async(atb_dn_harden_debug_tniu_ss_top_node_async_fifo_porting_debug_tniu_ss_top_node_async_fifo_porting_wptr_async),
		.debug_tniu_ss_top_node_syncreq_level_porting_syncreq_level(atb_dn_harden_debug_tniu_ss_top_node_syncreq_level_porting_debug_tniu_ss_top_node_syncreq_level_porting_syncreq_level),
		.debug_tniu_ss_top_node_lp_lw_porting_lw_rx_req(atb_dn_harden_debug_tniu_ss_top_node_lp_lw_porting_debug_tniu_ss_top_node_lp_lw_porting_lw_rx_req),
		.debug_tniu_ss_top_node_lp_lw_porting_lw_tx_req(atb_dn_harden_debug_tniu_ss_top_node_lp_lw_porting_debug_tniu_ss_top_node_lp_lw_porting_lw_tx_req),
		.debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_rx_req(atb_dn_harden_debug_tniu_ss_top_node_lp_afifo_porting_debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_rx_req),
		.debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_tx_req(atb_dn_harden_debug_tniu_ss_top_node_lp_afifo_porting_debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_tx_req),
		.debug_tniu_ss_top_node_timeout_val_porting_timeout_val(atb_dn_harden_debug_tniu_ss_top_node_timeout_val_porting_debug_tniu_ss_top_node_timeout_val_porting_timeout_val));

endmodule
//[UHDL]Content End [md5:67b3037e243d582e7f46a3a15f146e17]

