-f $INTR_NOC_DEMO_DIR/filelist/intr_common_dep.f
-f $INTR_NOC_DEMO_DIR/filelist/intr_niu_core.f
-f $INTR_NOC_DEMO_DIR/filelist/intr_network_core.f
-f $INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_wrap/filelist.f
