$DTI_INIU_TOP_NPU_SS3_DIR/dti_iniu_top_side_npu_ss3_macros_49ce854355.sv
$DTI_INIU_TOP_NPU_SS3_DIR/dti_iniu_top_npu_ss3_dti_pr_iniu_define.sv
$DTI_INIU_TOP_NPU_SS3_DIR/dti_iniu_top_npu_ss3_dti_iniu_pack.sv
$DTI_INIU_TOP_NPU_SS3_DIR/dti_iniu_top_npu_ss3_dti_pr_iniu_async_top_side.sv
$DTI_INIU_TOP_NPU_SS3_DIR/dti_iniu_top_npu_ss3_dti_pr_iniu_undef.sv
