-f $INTR_NOC_DEMO_DIR/filelist/intr_common_dep.f
-f $SOC_INTR_AON_SS_INIU_SYS_OUT_DIR/aon_ss_iniu_filelist.f
-f $SOC_INTR_AON_SS_TNIU_SYS_OUT_DIR/aon_ss_tniu_filelist.f
-f $SOC_INTR_AUDIO_SS_INIU_SYS_OUT_DIR/audio_ss_iniu_filelist.f
-f $SOC_INTR_CAMERA_SS_INIU_SYS_OUT_DIR/camera_ss_iniu_filelist.f
-f $SOC_INTR_CAMERA_SS_TNIU_SYS_OUT_DIR/camera_ss_tniu_filelist.f
-f $SOC_INTR_CPU_SS_INIU_SYS_OUT_DIR/cpu_ss_iniu_filelist.f
-f $SOC_INTR_CPU_SS_TNIU_SYS_OUT_DIR/cpu_ss_tniu_filelist.f
-f $SOC_INTR_DDR_INIU_SYS_OUT_DIR/ddr_iniu_filelist.f
-f $SOC_INTR_DDR_TNIU_SYS_OUT_DIR/ddr_tniu_filelist.f
-f $SOC_INTR_DEBUG_SS_INIU_SYS_OUT_DIR/debug_ss_iniu_filelist.f
-f $SOC_INTR_DISPLAY_SS_TNIU_SYS_OUT_DIR/display_ss_tniu_filelist.f
-f $SOC_INTR_DP_SS_INIU_SYS_OUT_DIR/dp_ss_iniu_filelist.f
-f $SOC_INTR_DSPSS_INIU_SYS_OUT_DIR/dspss_iniu_filelist.f
-f $SOC_INTR_DSPSS_TNIU_SYS_OUT_DIR/dspss_tniu_filelist.f
-f $SOC_INTR_GPU_SS_INIU_SYS_OUT_DIR/gpu_ss_iniu_filelist.f
-f $SOC_INTR_GPU_SS_TNIU_SYS_OUT_DIR/gpu_ss_tniu_filelist.f
-f $SOC_INTR_MIPI_SS_INIU_SYS_OUT_DIR/mipi_ss_iniu_filelist.f
-f $SOC_INTR_PCIE_ETH_SS_INIU_SYS_OUT_DIR/pcie_eth_ss_iniu_filelist.f
-f $SOC_INTR_PERI_SS_TNIU_SYS_OUT_DIR/peri_ss_tniu_filelist.f
-f $SOC_INTR_UCIE_SS_INIU_SYS_OUT_DIR/ucie_ss_iniu_filelist.f
-f $SOC_INTR_UCIE_SS_TNIU_SYS_OUT_DIR/ucie_ss_tniu_filelist.f
-f $SOC_INTR_UFS_SS_INIU_SYS_OUT_DIR/ufs_ss_iniu_filelist.f
-f $SOC_INTR_VPU_SS_INIU_SYS_OUT_DIR/vpu_ss_iniu_filelist.f
-f $INTR_INIU_TOP_OUT_DIR/filelist.f
-f $INTR_TNIU_TOP_OUT_DIR/filelist.f
-f $INTR_RING_NETWORK_OUT_DIR/filelist.f
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/aon_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/aon_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/aon_ss_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/aon_ss_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/audio_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/audio_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/camera_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/camera_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/camera_ss_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/camera_ss_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/cpu_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/cpu_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/cpu_ss_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/cpu_ss_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr0_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr0_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr10_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr10_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr11_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr11_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr1_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr1_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr2_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr2_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr3_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr3_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr4_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr4_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr5_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr5_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr6_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr6_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr7_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr7_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr8_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr8_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ddr9_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ddr9_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/debug_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/debug_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/default_tgtid_sink.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/default_tgtid_sink_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/display_ss_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/display_ss_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dp_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dp_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dspss0_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dspss0_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dspss1_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dspss1_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dspss2_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dspss2_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dspss3_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dspss3_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dspss4_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dspss4_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/dspss5_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/dspss5_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/gpu_ss0_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/gpu_ss0_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/gpu_ss1_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/gpu_ss1_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/mipi_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/mipi_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/pcie_eth_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/pcie_eth_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/peri_ss_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/peri_ss_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ring_async_cut_dn_to_up.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ring_async_cut_up_to_dn.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ucie_ss0_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ucie_ss0_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ucie_ss0_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ucie_ss0_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ucie_ss1_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ucie_ss1_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ucie_ss1_tniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ucie_ss1_tniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/ufs_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/ufs_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/vpu_ss_iniu_top_wrap.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_noc_topo/vpu_ss_iniu_ring.v
$INTR_NOC_DEMO_DIR/build_logic/soc_intr_ring_top/soc_intr_ring_top.v
