$PCIE_ETHSS_TNIU_SYS_OUT_DIR/pcie_ethss_tniu_sys_macros_2ecd970412.sv
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/sts_tniu_define.sv
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/lwnoc_sts_pack.sv
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/RegSpaceBase_cfg_reg_bank_table_sys.v
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/sts_tniu_apb_dec.sv
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/sts_tniu_apb.sv
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/sts_tniu_sys.sv
$PCIE_ETHSS_TNIU_SYS_OUT_DIR/sts_tniu_undefine.sv
