$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/safetyss_aon_local_tniu_sys_macros_4e16b3e113.sv
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/sts_tniu_define.sv
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/lwnoc_sts_pack.sv
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/RegSpaceBase_cfg_reg_bank_table_sys.v
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/sts_tniu_apb_dec.sv
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/sts_tniu_apb.sv
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/sts_tniu_sys.sv
$SAFETYSS_AON_LOCAL_TNIU_SYS_OUT_DIR/sts_tniu_undefine.sv
