`ifdef _PREFIX_
    `undef _PREFIX_
`endif

`ifdef STS_SRC_ID_WIDTH
    `undef STS_SRC_ID_WIDTH
`endif
`ifdef STS_TGT_ID_WIDTH
    `undef STS_TGT_ID_WIDTH
`endif
`ifdef STS_TXN_ID_WIDTH
    `undef STS_TXN_ID_WIDTH
`endif
`ifdef STS_CTI_EVENT_WIDTH
    `undef STS_CTI_EVENT_WIDTH
`endif
`ifdef STS_CTI_CHANNEL_WIDTH
    `undef STS_CTI_CHANNEL_WIDTH
`endif
`ifdef STS_CTM_TRIG_WIDTH
    `undef STS_CTM_TRIG_WIDTH
`endif
`ifdef STS_INIU_REQ_FIFO_DEPTH
    `undef STS_INIU_REQ_FIFO_DEPTH
`endif
`ifdef STS_INIU_RSP_FIFO_DEPTH
    `undef STS_INIU_RSP_FIFO_DEPTH
`endif
`ifdef STS_TNIU_REQ_FIFO_DEPTH
    `undef STS_TNIU_REQ_FIFO_DEPTH
`endif
`ifdef STS_TNIU_RSP_FIFO_DEPTH
    `undef STS_TNIU_RSP_FIFO_DEPTH
`endif
`ifdef STS_INIU_SINGLE_OT
    `undef STS_INIU_SINGLE_OT
`endif
`ifdef STS_INIU_NUM
    `undef STS_INIU_NUM
`endif
`ifdef STS_INIU_OT_TOTAL
    `undef STS_INIU_OT_TOTAL
`endif

`ifdef STS_TNIU_DBG_TIMESTAMP_WIDTH
    `undef STS_TNIU_DBG_TIMESTAMP_WIDTH
`endif
`ifdef STS_TNIU_DBG_DATA_WIDTH
    `undef STS_TNIU_DBG_DATA_WIDTH
`endif
`ifdef STS_TNIU_APB_ADDR_WIDTH
    `undef STS_TNIU_APB_ADDR_WIDTH
`endif
`ifdef STS_TNIU_SYNC_STAGE
    `undef STS_TNIU_SYNC_STAGE
`endif
`ifdef STS_TNIU_ASYNC_FIFO_DEPTH
    `undef STS_TNIU_ASYNC_FIFO_DEPTH
`endif
`ifdef STS_TNIU_FIFO_DEPTH
    `undef STS_TNIU_FIFO_DEPTH
`endif
`ifdef STS_TNIU_TGT_TYPE_WIDTH
    `undef STS_TNIU_TGT_TYPE_WIDTH
`endif
`ifdef STS_TNIU_LOCAL_APB_TGT_TYPE
    `undef STS_TNIU_LOCAL_APB_TGT_TYPE
`endif
`ifdef STS_TNIU_LOCAL_INIU_CTI_TGT_ID
    `undef STS_TNIU_LOCAL_INIU_CTI_TGT_ID
`endif
`ifdef STS_TNIU_LOCAL_INIU_CTI_TGT_MASK
    `undef STS_TNIU_LOCAL_INIU_CTI_TGT_MASK
`endif
`ifdef STS_TNIU_LOCAL_REGBANK_TGT_ID
    `undef STS_TNIU_LOCAL_REGBANK_TGT_ID
`endif
`ifdef STS_TNIU_LOCAL_REGBANK_TGT_MASK
    `undef STS_TNIU_LOCAL_REGBANK_TGT_MASK
`endif
`ifdef STS_TNIU_LOCAL_CTI_TGT_ID
    `undef STS_TNIU_LOCAL_CTI_TGT_ID
`endif
`ifdef STS_TNIU_LOCAL_CTI_TGT_MASK
    `undef STS_TNIU_LOCAL_CTI_TGT_MASK
`endif
`ifdef STS_TNIU_HAS_INIU_CTI_APB
    `undef STS_TNIU_HAS_INIU_CTI_APB
`endif
`ifdef STS_TNIU_SYS_REG_ROUTE_BASE
    `undef STS_TNIU_SYS_REG_ROUTE_BASE
`endif
`ifdef STS_TNIU_SYS_REG_ROUTE_MASK
    `undef STS_TNIU_SYS_REG_ROUTE_MASK
`endif
`ifdef STS_TNIU_SYS_APB_ROUTE_BASE
    `undef STS_TNIU_SYS_APB_ROUTE_BASE
`endif
`ifdef STS_TNIU_SYS_APB_ROUTE_MASK
    `undef STS_TNIU_SYS_APB_ROUTE_MASK
`endif
`ifdef STS_TNIU_ERR_INT_CNT_WIDTH
    `undef STS_TNIU_ERR_INT_CNT_WIDTH
`endif
