$DTI_INIU_TOP_NPU_SS0_DIR/dti_iniu_top_side_npu_ss0_macros_f04668d612.sv
$DTI_INIU_TOP_NPU_SS0_DIR/dti_iniu_top_npu_ss0_dti_pr_iniu_define.sv
$DTI_INIU_TOP_NPU_SS0_DIR/dti_iniu_top_npu_ss0_dti_iniu_pack.sv
$DTI_INIU_TOP_NPU_SS0_DIR/dti_iniu_top_npu_ss0_dti_pr_iniu_async_top_side.sv
$DTI_INIU_TOP_NPU_SS0_DIR/dti_iniu_top_npu_ss0_dti_pr_iniu_undef.sv
