`define dti_iniu_top_npu_ss0_INIU_ROUTE_BASE 0
`define dti_iniu_top_npu_ss0_PAYLOAD_WIDTH 90
`define dti_iniu_top_npu_ss0_TBU_NUM 1
`define dti_iniu_top_npu_ss0_TID_WIDTH 6
`define dti_iniu_top_npu_ss0_TRANSACTION_MAX_NUM 8
