$VDSPSS2_TNIU_SYS_OUT_DIR/vdspss2_tniu_sys_macros_c7e5ea4769.sv
$VDSPSS2_TNIU_SYS_OUT_DIR/sts_tniu_define.sv
$VDSPSS2_TNIU_SYS_OUT_DIR/lwnoc_sts_pack.sv
$VDSPSS2_TNIU_SYS_OUT_DIR/RegSpaceBase_cfg_reg_bank_table_sys.v
$VDSPSS2_TNIU_SYS_OUT_DIR/sts_tniu_apb_dec.sv
$VDSPSS2_TNIU_SYS_OUT_DIR/sts_tniu_apb.sv
$VDSPSS2_TNIU_SYS_OUT_DIR/sts_tniu_sys.sv
$VDSPSS2_TNIU_SYS_OUT_DIR/sts_tniu_undefine.sv
