//[UHDL]Content Start [md5:03ca6049b0bd0a598619140923b2e6bd]
module dti_noc_top_wrap
	import lwnoc_lp_struct_package::*;
	(
	input                                                 dti_harden_dn_clk_dn_func_porting                                                                                        ,
	input                                                 dti_harden_dn_rst_dn_func_n_porting                                                                                      ,
	output                                                dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_almost_empty                                               ,
	output                                                dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_almost_full                                                ,
	input                                                 dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_clear                                                      ,
	output                                                dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_empty                                                      ,
	output                                                dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_full                                                       ,
	output                                                dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_idle                                                       ,
	input                                                 dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_stall                                                      ,
	input  [104:0]                                        dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp0_top_wrap_lp_top_tx_porting_dsp0_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp0_top_wrap_lp_top_rx_porting_dsp0_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp1_top_wrap_lp_top_tx_porting_dsp1_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp1_top_wrap_lp_top_rx_porting_dsp1_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp2_top_wrap_lp_top_tx_porting_dsp2_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp2_top_wrap_lp_top_rx_porting_dsp2_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp3_top_wrap_lp_top_tx_porting_dsp3_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp3_top_wrap_lp_top_rx_porting_dsp3_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp4_top_wrap_lp_top_tx_porting_dsp4_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp4_top_wrap_lp_top_rx_porting_dsp4_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp5_top_wrap_lp_top_tx_porting_dsp5_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dsp5_top_wrap_lp_top_rx_porting_dsp5_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                    ,
	output [15:0]                                         dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                  ,
	output [15:0]                                         dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                   ,
	input  [15:0]                                         dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                  ,
	output [104:0]                                        dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                    ,
	input  [15:0]                                         dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                  ,
	input  [15:0]                                         dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                   ,
	output [15:0]                                         dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                  ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_cpu_top_wrap_lp_top_tx_porting_cpu_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                      ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_cpu_top_wrap_lp_top_rx_porting_cpu_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                      ,
	input  [104:0]                                        dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_pld_sync          ,
	output [15:0]                                         dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_rptr_async        ,
	output [15:0]                                         dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync         ,
	input  [15:0]                                         dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_wptr_async        ,
	output [104:0]                                        dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync          ,
	input  [15:0]                                         dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async        ,
	input  [15:0]                                         dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync         ,
	output [15:0]                                         dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async        ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_pcie_eth_top_wrap_lp_top_tx_porting_pcie_eth_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req            ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_pcie_eth_top_wrap_lp_top_rx_porting_pcie_eth_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req            ,
	input  [104:0]                                        dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_pld_sync            ,
	output [15:0]                                         dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_rptr_async          ,
	output [15:0]                                         dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync           ,
	input  [15:0]                                         dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_wptr_async          ,
	output [104:0]                                        dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync            ,
	input  [15:0]                                         dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async          ,
	input  [15:0]                                         dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync           ,
	output [15:0]                                         dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async          ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_usb_ufs_top_wrap_lp_top_tx_porting_usb_ufs_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req              ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_usb_ufs_top_wrap_lp_top_rx_porting_usb_ufs_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req              ,
	input  [104:0]                                        dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_pld_sync              ,
	output [15:0]                                         dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_rptr_async            ,
	output [15:0]                                         dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync             ,
	input  [15:0]                                         dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_wptr_async            ,
	output [104:0]                                        dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync              ,
	input  [15:0]                                         dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async            ,
	input  [15:0]                                         dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync             ,
	output [15:0]                                         dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async            ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_camera_top_wrap_lp_top_tx_porting_camera_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_camera_top_wrap_lp_top_rx_porting_camera_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                ,
	input  [104:0]                                        dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_mipi_top_wrap_lp_top_tx_porting_mipi_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_mipi_top_wrap_lp_top_rx_porting_mipi_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_gpu0_top_wrap_lp_top_tx_porting_gpu0_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_gpu0_top_wrap_lp_top_rx_porting_gpu0_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                  ,
	output [15:0]                                         dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                ,
	output [15:0]                                         dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                 ,
	input  [15:0]                                         dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                ,
	output [104:0]                                        dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                  ,
	input  [15:0]                                         dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                ,
	input  [15:0]                                         dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                 ,
	output [15:0]                                         dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_gpu1_top_wrap_lp_top_tx_porting_gpu1_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_gpu1_top_wrap_lp_top_rx_porting_gpu1_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                    ,
	input  [104:0]                                        dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_pld_sync                      ,
	output [15:0]                                         dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_rptr_async                    ,
	output [15:0]                                         dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync                     ,
	input  [15:0]                                         dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_wptr_async                    ,
	output [104:0]                                        dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync                      ,
	input  [15:0]                                         dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async                    ,
	input  [15:0]                                         dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync                     ,
	output [15:0]                                         dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async                    ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dp_top_wrap_lp_top_tx_porting_dp_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req                        ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_dp_top_wrap_lp_top_rx_porting_dp_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req                        ,
	input  [104:0]                                        dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_pld_sync            ,
	output [15:0]                                         dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_rptr_async          ,
	output [15:0]                                         dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync           ,
	input  [15:0]                                         dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_wptr_async          ,
	output [104:0]                                        dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync            ,
	input  [15:0]                                         dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async          ,
	input  [15:0]                                         dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync           ,
	output [15:0]                                         dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async          ,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_display_top_wrap_lp_top_tx_porting_display_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req              ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_dn_display_top_wrap_lp_top_rx_porting_display_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req              ,
	input                                                 dti_harden_up_clk_up_func_porting                                                                                        ,
	input                                                 dti_harden_up_rst_up_func_n_porting                                                                                      ,
	output [104:0]                                        dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_pld_sync  ,
	input  [9:0]                                          dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_rptr_async,
	input  [9:0]                                          dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync ,
	output [9:0]                                          dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_wptr_async,
	input  [104:0]                                        dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync  ,
	output [9:0]                                          dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async,
	output [9:0]                                          dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync ,
	input  [9:0]                                          dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async,
	output lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_up_sys_tcu_tniu_top_wrap_lp_top_tx_porting_sys_tcu_tniu_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req    ,
	input  lwnoc_lp_struct_package::lwnoc_lp_req_signal_t dti_harden_up_sys_tcu_tniu_top_wrap_lp_top_rx_porting_sys_tcu_tniu_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req    );

	//Wire define for this module.

	//Wire define for sub module.
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_req_porting_iniu0_req_ready               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_req_porting_iniu0_req_threshold           ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_last                ;
	wire [89:0]  u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_payload             ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_qos                 ;
	wire [5:0]   u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_srcid               ;
	wire [5:0]   u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_tgtid               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_valid               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_req_porting_iniu1_req_ready               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_req_porting_iniu1_req_threshold           ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_last                ;
	wire [89:0]  u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_payload             ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_qos                 ;
	wire [5:0]   u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_srcid               ;
	wire [5:0]   u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_tgtid               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_valid               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_last                ;
	wire [89:0]  u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_payload             ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_qos                 ;
	wire [5:0]   u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_srcid               ;
	wire [5:0]   u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_tgtid               ;
	wire         u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_valid               ;
	wire [15:0]  u_up_harden_TO_u_dn_harden_SIG_dti_req_rsp_async_bridge_mst_sync_porting_rptr_async;
	wire [15:0]  u_up_harden_TO_u_dn_harden_SIG_dti_req_rsp_async_bridge_mst_sync_porting_rptr_sync ;
	wire [104:0] u_dn_harden_TO_u_up_harden_SIG_dti_req_rsp_async_bridge_slv_sync_porting_pld_sync  ;
	wire [15:0]  u_dn_harden_TO_u_up_harden_SIG_dti_req_rsp_async_bridge_slv_sync_porting_wptr_async;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_last                  ;
	wire [89:0]  u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_payload               ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_qos                   ;
	wire [5:0]   u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_srcid                 ;
	wire [5:0]   u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_tgtid                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_valid                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_rsp_porting_tniu_rsp_ready                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_rsp_porting_tniu_rsp_threshold             ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_last                  ;
	wire [89:0]  u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_payload               ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_qos                   ;
	wire [5:0]   u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_srcid                 ;
	wire [5:0]   u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_tgtid                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_valid                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_rsp_porting_tniu_rsp_ready                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_rsp_porting_tniu_rsp_threshold             ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw2_tniu_rsp_porting_tniu_rsp_ready                 ;
	wire         u_dn_harden_TO_u_up_harden_SIG_sw2_tniu_rsp_porting_tniu_rsp_threshold             ;

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	dti_harden_dn u_dn_harden (
		.clk_dn_func(dti_harden_dn_clk_dn_func_porting),
		.rst_dn_func_n(dti_harden_dn_rst_dn_func_n_porting),
		.sw0_tniu_req_porting_tniu_req_last(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_last),
		.sw0_tniu_req_porting_tniu_req_payload(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_payload),
		.sw0_tniu_req_porting_tniu_req_qos(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_qos),
		.sw0_tniu_req_porting_tniu_req_ready(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_req_porting_iniu0_req_ready),
		.sw0_tniu_req_porting_tniu_req_srcid(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_srcid),
		.sw0_tniu_req_porting_tniu_req_tgtid(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_tgtid),
		.sw0_tniu_req_porting_tniu_req_threshold(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_req_porting_iniu0_req_threshold),
		.sw0_tniu_req_porting_tniu_req_valid(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_valid),
		.sw0_tniu_rsp_porting_tniu_rsp_last(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_last),
		.sw0_tniu_rsp_porting_tniu_rsp_payload(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_payload),
		.sw0_tniu_rsp_porting_tniu_rsp_qos(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_qos),
		.sw0_tniu_rsp_porting_tniu_rsp_ready(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_rsp_porting_tniu_rsp_ready),
		.sw0_tniu_rsp_porting_tniu_rsp_srcid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_srcid),
		.sw0_tniu_rsp_porting_tniu_rsp_tgtid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_tgtid),
		.sw0_tniu_rsp_porting_tniu_rsp_threshold(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_rsp_porting_tniu_rsp_threshold),
		.sw0_tniu_rsp_porting_tniu_rsp_valid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_valid),
		.sw1_tniu_req_porting_tniu_req_last(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_last),
		.sw1_tniu_req_porting_tniu_req_payload(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_payload),
		.sw1_tniu_req_porting_tniu_req_qos(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_qos),
		.sw1_tniu_req_porting_tniu_req_ready(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_req_porting_iniu1_req_ready),
		.sw1_tniu_req_porting_tniu_req_srcid(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_srcid),
		.sw1_tniu_req_porting_tniu_req_tgtid(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_tgtid),
		.sw1_tniu_req_porting_tniu_req_threshold(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_req_porting_iniu1_req_threshold),
		.sw1_tniu_req_porting_tniu_req_valid(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_valid),
		.sw1_tniu_rsp_porting_tniu_rsp_last(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_last),
		.sw1_tniu_rsp_porting_tniu_rsp_payload(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_payload),
		.sw1_tniu_rsp_porting_tniu_rsp_qos(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_qos),
		.sw1_tniu_rsp_porting_tniu_rsp_ready(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_rsp_porting_tniu_rsp_ready),
		.sw1_tniu_rsp_porting_tniu_rsp_srcid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_srcid),
		.sw1_tniu_rsp_porting_tniu_rsp_tgtid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_tgtid),
		.sw1_tniu_rsp_porting_tniu_rsp_threshold(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_rsp_porting_tniu_rsp_threshold),
		.sw1_tniu_rsp_porting_tniu_rsp_valid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_valid),
		.sw2_tniu_rsp_porting_tniu_rsp_last(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_last),
		.sw2_tniu_rsp_porting_tniu_rsp_payload(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_payload),
		.sw2_tniu_rsp_porting_tniu_rsp_qos(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_qos),
		.sw2_tniu_rsp_porting_tniu_rsp_ready(u_dn_harden_TO_u_up_harden_SIG_sw2_tniu_rsp_porting_tniu_rsp_ready),
		.sw2_tniu_rsp_porting_tniu_rsp_srcid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_srcid),
		.sw2_tniu_rsp_porting_tniu_rsp_tgtid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_tgtid),
		.sw2_tniu_rsp_porting_tniu_rsp_threshold(u_dn_harden_TO_u_up_harden_SIG_sw2_tniu_rsp_porting_tniu_rsp_threshold),
		.sw2_tniu_rsp_porting_tniu_rsp_valid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_valid),
		.dti_buffer_ctrl_porting_almost_empty(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_almost_empty),
		.dti_buffer_ctrl_porting_almost_full(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_almost_full),
		.dti_buffer_ctrl_porting_clear(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_clear),
		.dti_buffer_ctrl_porting_empty(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_empty),
		.dti_buffer_ctrl_porting_full(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_full),
		.dti_buffer_ctrl_porting_idle(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_idle),
		.dti_buffer_ctrl_porting_stall(dti_harden_dn_dti_buffer_ctrl_porting_dti_buffer_ctrl_porting_stall),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dsp0_top_wrap_async_fifo_porting_dsp0_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dsp0_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dsp0_top_wrap_lp_top_tx_porting_dsp0_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dsp0_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dsp0_top_wrap_lp_top_rx_porting_dsp0_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dsp1_top_wrap_async_fifo_porting_dsp1_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dsp1_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dsp1_top_wrap_lp_top_tx_porting_dsp1_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dsp1_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dsp1_top_wrap_lp_top_rx_porting_dsp1_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dsp2_top_wrap_async_fifo_porting_dsp2_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dsp2_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dsp2_top_wrap_lp_top_tx_porting_dsp2_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dsp2_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dsp2_top_wrap_lp_top_rx_porting_dsp2_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dsp3_top_wrap_async_fifo_porting_dsp3_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dsp3_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dsp3_top_wrap_lp_top_tx_porting_dsp3_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dsp3_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dsp3_top_wrap_lp_top_rx_porting_dsp3_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dsp4_top_wrap_async_fifo_porting_dsp4_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dsp4_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dsp4_top_wrap_lp_top_tx_porting_dsp4_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dsp4_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dsp4_top_wrap_lp_top_rx_porting_dsp4_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dsp5_top_wrap_async_fifo_porting_dsp5_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dsp5_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dsp5_top_wrap_lp_top_tx_porting_dsp5_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dsp5_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dsp5_top_wrap_lp_top_rx_porting_dsp5_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.cpu_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.cpu_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.cpu_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.cpu_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.cpu_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.cpu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.cpu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.cpu_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_cpu_top_wrap_async_fifo_porting_cpu_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.cpu_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_cpu_top_wrap_lp_top_tx_porting_cpu_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.cpu_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_cpu_top_wrap_lp_top_rx_porting_cpu_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_pcie_eth_top_wrap_async_fifo_porting_pcie_eth_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.pcie_eth_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_pcie_eth_top_wrap_lp_top_tx_porting_pcie_eth_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.pcie_eth_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_pcie_eth_top_wrap_lp_top_rx_porting_pcie_eth_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_usb_ufs_top_wrap_async_fifo_porting_usb_ufs_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.usb_ufs_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_usb_ufs_top_wrap_lp_top_tx_porting_usb_ufs_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.usb_ufs_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_usb_ufs_top_wrap_lp_top_rx_porting_usb_ufs_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.camera_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.camera_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.camera_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.camera_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.camera_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.camera_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.camera_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.camera_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_camera_top_wrap_async_fifo_porting_camera_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.camera_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_camera_top_wrap_lp_top_tx_porting_camera_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.camera_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_camera_top_wrap_lp_top_rx_porting_camera_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.mipi_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.mipi_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.mipi_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.mipi_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.mipi_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.mipi_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.mipi_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.mipi_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_mipi_top_wrap_async_fifo_porting_mipi_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.mipi_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_mipi_top_wrap_lp_top_tx_porting_mipi_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.mipi_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_mipi_top_wrap_lp_top_rx_porting_mipi_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_gpu0_top_wrap_async_fifo_porting_gpu0_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.gpu0_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_gpu0_top_wrap_lp_top_tx_porting_gpu0_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.gpu0_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_gpu0_top_wrap_lp_top_rx_porting_gpu0_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_gpu1_top_wrap_async_fifo_porting_gpu1_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.gpu1_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_gpu1_top_wrap_lp_top_tx_porting_gpu1_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.gpu1_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_gpu1_top_wrap_lp_top_rx_porting_gpu1_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dp_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.dp_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.dp_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.dp_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.dp_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.dp_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.dp_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.dp_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_dp_top_wrap_async_fifo_porting_dp_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.dp_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_dp_top_wrap_lp_top_tx_porting_dp_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.dp_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_dp_top_wrap_lp_top_rx_porting_dp_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.display_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.display_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.display_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.display_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.display_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.display_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.display_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.display_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_dn_display_top_wrap_async_fifo_porting_display_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.display_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_dn_display_top_wrap_lp_top_tx_porting_display_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.display_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_dn_display_top_wrap_lp_top_rx_porting_display_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req),
		.dti_req_rsp_async_bridge_slv_sync_porting_pld_sync(u_dn_harden_TO_u_up_harden_SIG_dti_req_rsp_async_bridge_slv_sync_porting_pld_sync),
		.dti_req_rsp_async_bridge_slv_sync_porting_rptr_async(u_up_harden_TO_u_dn_harden_SIG_dti_req_rsp_async_bridge_mst_sync_porting_rptr_async),
		.dti_req_rsp_async_bridge_slv_sync_porting_rptr_sync(u_up_harden_TO_u_dn_harden_SIG_dti_req_rsp_async_bridge_mst_sync_porting_rptr_sync),
		.dti_req_rsp_async_bridge_slv_sync_porting_wptr_async(u_dn_harden_TO_u_up_harden_SIG_dti_req_rsp_async_bridge_slv_sync_porting_wptr_async));
	dti_harden_up u_up_harden (
		.clk_up_func(dti_harden_up_clk_up_func_porting),
		.rst_up_func_n(dti_harden_up_rst_up_func_n_porting),
		.dti_req_rsp_async_bridge_mst_sync_porting_pld_sync(u_dn_harden_TO_u_up_harden_SIG_dti_req_rsp_async_bridge_slv_sync_porting_pld_sync),
		.dti_req_rsp_async_bridge_mst_sync_porting_rptr_async(u_up_harden_TO_u_dn_harden_SIG_dti_req_rsp_async_bridge_mst_sync_porting_rptr_async),
		.dti_req_rsp_async_bridge_mst_sync_porting_rptr_sync(u_up_harden_TO_u_dn_harden_SIG_dti_req_rsp_async_bridge_mst_sync_porting_rptr_sync),
		.dti_req_rsp_async_bridge_mst_sync_porting_wptr_async(u_dn_harden_TO_u_up_harden_SIG_dti_req_rsp_async_bridge_slv_sync_porting_wptr_async),
		.sw3_iniu0_req_porting_iniu0_req_last(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_last),
		.sw3_iniu0_req_porting_iniu0_req_payload(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_payload),
		.sw3_iniu0_req_porting_iniu0_req_qos(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_qos),
		.sw3_iniu0_req_porting_iniu0_req_ready(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_req_porting_iniu0_req_ready),
		.sw3_iniu0_req_porting_iniu0_req_srcid(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_srcid),
		.sw3_iniu0_req_porting_iniu0_req_tgtid(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_tgtid),
		.sw3_iniu0_req_porting_iniu0_req_threshold(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_req_porting_iniu0_req_threshold),
		.sw3_iniu0_req_porting_iniu0_req_valid(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_req_porting_tniu_req_valid),
		.sw3_iniu0_rsp_porting_iniu0_rsp_last(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_last),
		.sw3_iniu0_rsp_porting_iniu0_rsp_payload(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_payload),
		.sw3_iniu0_rsp_porting_iniu0_rsp_qos(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_qos),
		.sw3_iniu0_rsp_porting_iniu0_rsp_ready(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_rsp_porting_tniu_rsp_ready),
		.sw3_iniu0_rsp_porting_iniu0_rsp_srcid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_srcid),
		.sw3_iniu0_rsp_porting_iniu0_rsp_tgtid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_tgtid),
		.sw3_iniu0_rsp_porting_iniu0_rsp_threshold(u_dn_harden_TO_u_up_harden_SIG_sw0_tniu_rsp_porting_tniu_rsp_threshold),
		.sw3_iniu0_rsp_porting_iniu0_rsp_valid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu0_rsp_porting_iniu0_rsp_valid),
		.sw3_iniu1_req_porting_iniu1_req_last(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_last),
		.sw3_iniu1_req_porting_iniu1_req_payload(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_payload),
		.sw3_iniu1_req_porting_iniu1_req_qos(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_qos),
		.sw3_iniu1_req_porting_iniu1_req_ready(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_req_porting_iniu1_req_ready),
		.sw3_iniu1_req_porting_iniu1_req_srcid(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_srcid),
		.sw3_iniu1_req_porting_iniu1_req_tgtid(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_tgtid),
		.sw3_iniu1_req_porting_iniu1_req_threshold(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_req_porting_iniu1_req_threshold),
		.sw3_iniu1_req_porting_iniu1_req_valid(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_req_porting_tniu_req_valid),
		.sw3_iniu1_rsp_porting_iniu1_rsp_last(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_last),
		.sw3_iniu1_rsp_porting_iniu1_rsp_payload(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_payload),
		.sw3_iniu1_rsp_porting_iniu1_rsp_qos(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_qos),
		.sw3_iniu1_rsp_porting_iniu1_rsp_ready(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_rsp_porting_tniu_rsp_ready),
		.sw3_iniu1_rsp_porting_iniu1_rsp_srcid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_srcid),
		.sw3_iniu1_rsp_porting_iniu1_rsp_tgtid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_tgtid),
		.sw3_iniu1_rsp_porting_iniu1_rsp_threshold(u_dn_harden_TO_u_up_harden_SIG_sw1_tniu_rsp_porting_tniu_rsp_threshold),
		.sw3_iniu1_rsp_porting_iniu1_rsp_valid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu1_rsp_porting_iniu1_rsp_valid),
		.sw3_iniu2_rsp_porting_iniu2_rsp_last(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_last),
		.sw3_iniu2_rsp_porting_iniu2_rsp_payload(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_payload),
		.sw3_iniu2_rsp_porting_iniu2_rsp_qos(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_qos),
		.sw3_iniu2_rsp_porting_iniu2_rsp_ready(u_dn_harden_TO_u_up_harden_SIG_sw2_tniu_rsp_porting_tniu_rsp_ready),
		.sw3_iniu2_rsp_porting_iniu2_rsp_srcid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_srcid),
		.sw3_iniu2_rsp_porting_iniu2_rsp_tgtid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_tgtid),
		.sw3_iniu2_rsp_porting_iniu2_rsp_threshold(u_dn_harden_TO_u_up_harden_SIG_sw2_tniu_rsp_porting_tniu_rsp_threshold),
		.sw3_iniu2_rsp_porting_iniu2_rsp_valid(u_up_harden_TO_u_dn_harden_SIG_sw3_iniu2_rsp_porting_iniu2_rsp_valid),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_pld_sync(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_pld_sync),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_rptr_async(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_rptr_async),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_rptr_sync),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_wptr_async(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_req_wptr_async),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_pld_sync),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_async),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_rptr_sync),
		.sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async(dti_harden_up_sys_tcu_tniu_top_wrap_async_fifo_porting_sys_tcu_tniu_top_wrap_async_fifo_porting_async_fifo_rsp_wptr_async),
		.sys_tcu_tniu_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req(dti_harden_up_sys_tcu_tniu_top_wrap_lp_top_tx_porting_sys_tcu_tniu_top_wrap_lp_top_tx_porting_lp_top_tx_lp_hub_tx_req),
		.sys_tcu_tniu_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req(dti_harden_up_sys_tcu_tniu_top_wrap_lp_top_rx_porting_sys_tcu_tniu_top_wrap_lp_top_rx_porting_lp_top_rx_lp_hub_rx_req));

endmodule
//[UHDL]Content End [md5:03ca6049b0bd0a598619140923b2e6bd]

