//[UHDL]Content Start [md5:98ec9509865ab06a4d58631e1d913dc6]
module soc_sts_up_harden (
	input  [-1:0]  dspss0_tniu_top_req_porting_in_req_pld                     ,
	output         dspss0_tniu_top_req_porting_in_req_rdy                     ,
	input          dspss0_tniu_top_req_porting_in_req_vld                     ,
	output [-1:0]  dspss0_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          dspss0_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         dspss0_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  dspss0_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         dspss0_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   dspss0_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  dspss0_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          dspss0_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         dspss0_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          dspss0_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   dspss0_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  dspss0_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         dspss0_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  dspss0_tniu_top_sys_apb_porting_m_paddr                    ,
	output         dspss0_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   dspss0_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  dspss0_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   dspss0_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   dspss0_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   dspss0_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   dspss0_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  dspss0_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         dspss0_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  dspss0_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  dspss0_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  dspss0_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  dspss0_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   dspss0_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   dspss0_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   dspss0_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   dspss0_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   dspss0_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   dspss0_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   dspss0_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   dspss0_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	input  [-1:0]  dspss1_tniu_top_req_porting_in_req_pld                     ,
	output         dspss1_tniu_top_req_porting_in_req_rdy                     ,
	input          dspss1_tniu_top_req_porting_in_req_vld                     ,
	output [-1:0]  dspss1_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          dspss1_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         dspss1_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  dspss1_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         dspss1_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   dspss1_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  dspss1_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          dspss1_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         dspss1_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          dspss1_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   dspss1_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  dspss1_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         dspss1_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  dspss1_tniu_top_sys_apb_porting_m_paddr                    ,
	output         dspss1_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   dspss1_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  dspss1_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   dspss1_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   dspss1_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   dspss1_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   dspss1_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  dspss1_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         dspss1_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  dspss1_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  dspss1_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  dspss1_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  dspss1_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   dspss1_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   dspss1_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   dspss1_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   dspss1_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   dspss1_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   dspss1_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   dspss1_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   dspss1_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	input  [-1:0]  dspss2_tniu_top_req_porting_in_req_pld                     ,
	output         dspss2_tniu_top_req_porting_in_req_rdy                     ,
	input          dspss2_tniu_top_req_porting_in_req_vld                     ,
	output [-1:0]  dspss2_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          dspss2_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         dspss2_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  dspss2_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         dspss2_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   dspss2_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  dspss2_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          dspss2_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         dspss2_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          dspss2_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   dspss2_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  dspss2_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         dspss2_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  dspss2_tniu_top_sys_apb_porting_m_paddr                    ,
	output         dspss2_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   dspss2_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  dspss2_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   dspss2_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   dspss2_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   dspss2_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   dspss2_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  dspss2_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         dspss2_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  dspss2_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  dspss2_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  dspss2_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  dspss2_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   dspss2_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   dspss2_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   dspss2_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   dspss2_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   dspss2_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   dspss2_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   dspss2_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   dspss2_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	input  [-1:0]  dspss3_tniu_top_req_porting_in_req_pld                     ,
	output         dspss3_tniu_top_req_porting_in_req_rdy                     ,
	input          dspss3_tniu_top_req_porting_in_req_vld                     ,
	output [-1:0]  dspss3_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          dspss3_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         dspss3_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  dspss3_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         dspss3_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   dspss3_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  dspss3_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          dspss3_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         dspss3_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          dspss3_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   dspss3_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  dspss3_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         dspss3_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  dspss3_tniu_top_sys_apb_porting_m_paddr                    ,
	output         dspss3_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   dspss3_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  dspss3_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   dspss3_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   dspss3_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   dspss3_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   dspss3_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  dspss3_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         dspss3_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  dspss3_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  dspss3_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  dspss3_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  dspss3_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   dspss3_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   dspss3_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   dspss3_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   dspss3_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   dspss3_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   dspss3_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   dspss3_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   dspss3_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	input  [-1:0]  dspss4_tniu_top_req_porting_in_req_pld                     ,
	output         dspss4_tniu_top_req_porting_in_req_rdy                     ,
	input          dspss4_tniu_top_req_porting_in_req_vld                     ,
	output [-1:0]  dspss4_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          dspss4_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         dspss4_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  dspss4_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         dspss4_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   dspss4_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  dspss4_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          dspss4_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         dspss4_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          dspss4_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   dspss4_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  dspss4_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         dspss4_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  dspss4_tniu_top_sys_apb_porting_m_paddr                    ,
	output         dspss4_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   dspss4_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  dspss4_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   dspss4_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   dspss4_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   dspss4_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   dspss4_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  dspss4_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         dspss4_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  dspss4_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  dspss4_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  dspss4_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  dspss4_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   dspss4_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   dspss4_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   dspss4_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   dspss4_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   dspss4_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   dspss4_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   dspss4_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   dspss4_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	input  [-1:0]  dspss5_tniu_top_req_porting_in_req_pld                     ,
	output         dspss5_tniu_top_req_porting_in_req_rdy                     ,
	input          dspss5_tniu_top_req_porting_in_req_vld                     ,
	output [-1:0]  dspss5_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          dspss5_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         dspss5_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  dspss5_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         dspss5_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   dspss5_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  dspss5_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          dspss5_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         dspss5_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          dspss5_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   dspss5_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  dspss5_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         dspss5_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  dspss5_tniu_top_sys_apb_porting_m_paddr                    ,
	output         dspss5_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   dspss5_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  dspss5_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   dspss5_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   dspss5_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   dspss5_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   dspss5_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  dspss5_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         dspss5_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  dspss5_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  dspss5_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  dspss5_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  dspss5_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   dspss5_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   dspss5_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   dspss5_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   dspss5_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   dspss5_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   dspss5_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   dspss5_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   dspss5_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	output [118:0] harden_up_async_bridge_mst_m_chan_porting_out_rsp_pld      ,
	input          harden_up_async_bridge_mst_m_chan_porting_out_rsp_rdy      ,
	output         harden_up_async_bridge_mst_m_chan_porting_out_rsp_vld      ,
	input  [119:0] harden_up_async_bridge_mst_sync_porting_pld_sync           ,
	output [15:0]  harden_up_async_bridge_mst_sync_porting_rptr_async         ,
	output [15:0]  harden_up_async_bridge_mst_sync_porting_rptr_sync          ,
	input  [15:0]  harden_up_async_bridge_mst_sync_porting_wptr_async         ,
	input          async_bridge_mst_clk_harden_up_func_porting                ,
	input          async_bridge_mst_rst_harden_up_func_n_porting              ,
	input          dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting     ,
	input          dspss0_top_aon_ss_iniu_clk_sys_porting_porting             ,
	input          dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting   ,
	input          dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting           );

	//Wire define for this module.

	//Wire define for sub module.

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	sts_tniu_top dspss0_top (
		.clk_src(dspss0_top_aon_ss_iniu_clk_sys_porting_porting),
		.clk_dst(async_bridge_mst_clk_harden_up_func_porting),
		.clk_dbg_timer(dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting),
		.rstn_src(dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting),
		.rstn_dst(async_bridge_mst_rst_harden_up_func_n_porting),
		.rstn_dbg_timer(dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting),
		.in_req_vld(dspss0_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(dspss0_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(dspss0_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(dspss0_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(dspss0_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(dspss0_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(dspss0_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(dspss0_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(dspss0_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(dspss0_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(dspss0_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(dspss0_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(dspss0_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(dspss0_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(dspss0_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(dspss0_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(dspss0_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(dspss0_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(dspss0_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(dspss0_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(dspss0_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(dspss0_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(dspss0_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(dspss0_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(dspss0_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(dspss0_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(dspss0_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(dspss0_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(dspss0_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(dspss0_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(dspss0_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(dspss0_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(dspss0_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(dspss0_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(dspss0_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(dspss0_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(dspss0_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(dspss0_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_tniu_top dspss1_top (
		.clk_src(dspss0_top_aon_ss_iniu_clk_sys_porting_porting),
		.clk_dst(async_bridge_mst_clk_harden_up_func_porting),
		.clk_dbg_timer(dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting),
		.rstn_src(dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting),
		.rstn_dst(async_bridge_mst_rst_harden_up_func_n_porting),
		.rstn_dbg_timer(dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting),
		.in_req_vld(dspss1_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(dspss1_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(dspss1_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(dspss1_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(dspss1_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(dspss1_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(dspss1_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(dspss1_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(dspss1_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(dspss1_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(dspss1_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(dspss1_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(dspss1_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(dspss1_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(dspss1_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(dspss1_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(dspss1_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(dspss1_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(dspss1_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(dspss1_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(dspss1_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(dspss1_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(dspss1_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(dspss1_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(dspss1_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(dspss1_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(dspss1_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(dspss1_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(dspss1_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(dspss1_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(dspss1_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(dspss1_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(dspss1_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(dspss1_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(dspss1_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(dspss1_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(dspss1_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(dspss1_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_tniu_top dspss2_top (
		.clk_src(dspss0_top_aon_ss_iniu_clk_sys_porting_porting),
		.clk_dst(async_bridge_mst_clk_harden_up_func_porting),
		.clk_dbg_timer(dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting),
		.rstn_src(dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting),
		.rstn_dst(async_bridge_mst_rst_harden_up_func_n_porting),
		.rstn_dbg_timer(dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting),
		.in_req_vld(dspss2_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(dspss2_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(dspss2_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(dspss2_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(dspss2_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(dspss2_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(dspss2_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(dspss2_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(dspss2_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(dspss2_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(dspss2_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(dspss2_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(dspss2_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(dspss2_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(dspss2_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(dspss2_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(dspss2_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(dspss2_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(dspss2_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(dspss2_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(dspss2_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(dspss2_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(dspss2_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(dspss2_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(dspss2_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(dspss2_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(dspss2_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(dspss2_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(dspss2_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(dspss2_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(dspss2_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(dspss2_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(dspss2_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(dspss2_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(dspss2_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(dspss2_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(dspss2_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(dspss2_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_tniu_top dspss3_top (
		.clk_src(dspss0_top_aon_ss_iniu_clk_sys_porting_porting),
		.clk_dst(async_bridge_mst_clk_harden_up_func_porting),
		.clk_dbg_timer(dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting),
		.rstn_src(dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting),
		.rstn_dst(async_bridge_mst_rst_harden_up_func_n_porting),
		.rstn_dbg_timer(dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting),
		.in_req_vld(dspss3_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(dspss3_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(dspss3_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(dspss3_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(dspss3_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(dspss3_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(dspss3_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(dspss3_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(dspss3_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(dspss3_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(dspss3_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(dspss3_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(dspss3_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(dspss3_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(dspss3_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(dspss3_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(dspss3_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(dspss3_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(dspss3_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(dspss3_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(dspss3_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(dspss3_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(dspss3_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(dspss3_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(dspss3_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(dspss3_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(dspss3_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(dspss3_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(dspss3_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(dspss3_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(dspss3_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(dspss3_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(dspss3_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(dspss3_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(dspss3_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(dspss3_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(dspss3_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(dspss3_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_tniu_top dspss4_top (
		.clk_src(dspss0_top_aon_ss_iniu_clk_sys_porting_porting),
		.clk_dst(async_bridge_mst_clk_harden_up_func_porting),
		.clk_dbg_timer(dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting),
		.rstn_src(dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting),
		.rstn_dst(async_bridge_mst_rst_harden_up_func_n_porting),
		.rstn_dbg_timer(dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting),
		.in_req_vld(dspss4_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(dspss4_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(dspss4_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(dspss4_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(dspss4_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(dspss4_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(dspss4_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(dspss4_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(dspss4_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(dspss4_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(dspss4_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(dspss4_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(dspss4_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(dspss4_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(dspss4_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(dspss4_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(dspss4_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(dspss4_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(dspss4_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(dspss4_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(dspss4_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(dspss4_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(dspss4_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(dspss4_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(dspss4_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(dspss4_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(dspss4_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(dspss4_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(dspss4_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(dspss4_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(dspss4_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(dspss4_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(dspss4_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(dspss4_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(dspss4_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(dspss4_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(dspss4_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(dspss4_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_tniu_top dspss5_top (
		.clk_src(dspss0_top_aon_ss_iniu_clk_sys_porting_porting),
		.clk_dst(async_bridge_mst_clk_harden_up_func_porting),
		.clk_dbg_timer(dspss0_top_camera_ss_top_clk_dbg_timer_porting_porting),
		.rstn_src(dspss0_top_aon_ss_iniu_rst_sys_n_porting_porting),
		.rstn_dst(async_bridge_mst_rst_harden_up_func_n_porting),
		.rstn_dbg_timer(dspss0_top_camera_ss_top_rst_dbg_timer_n_porting_porting),
		.in_req_vld(dspss5_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(dspss5_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(dspss5_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(dspss5_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(dspss5_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(dspss5_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(dspss5_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(dspss5_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(dspss5_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(dspss5_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(dspss5_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(dspss5_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(dspss5_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(dspss5_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(dspss5_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(dspss5_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(dspss5_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(dspss5_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(dspss5_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(dspss5_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(dspss5_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(dspss5_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(dspss5_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(dspss5_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(dspss5_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(dspss5_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(dspss5_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(dspss5_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(dspss5_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(dspss5_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(dspss5_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(dspss5_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(dspss5_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(dspss5_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(dspss5_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(dspss5_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(dspss5_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(dspss5_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_async_bridge_mst async_bridge_mst (
		.clk(async_bridge_mst_clk_harden_up_func_porting),
		.rst_n(async_bridge_mst_rst_harden_up_func_n_porting),
		.stall(),
		.clear(),
		.full_zero(),
		.idle(),
		.out_rsp_vld(harden_up_async_bridge_mst_m_chan_porting_out_rsp_vld),
		.out_rsp_pld(harden_up_async_bridge_mst_m_chan_porting_out_rsp_pld),
		.out_rsp_rdy(harden_up_async_bridge_mst_m_chan_porting_out_rsp_rdy),
		.almost_empty(),
		.wptr_async(harden_up_async_bridge_mst_sync_porting_wptr_async),
		.rptr_async(harden_up_async_bridge_mst_sync_porting_rptr_async),
		.rptr_sync(harden_up_async_bridge_mst_sync_porting_rptr_sync),
		.pld_sync(harden_up_async_bridge_mst_sync_porting_pld_sync));

endmodule
//[UHDL]Content End [md5:98ec9509865ab06a4d58631e1d913dc6]

