$DTI_TEST_DIR/build_logic/soc_dti_harden_up/dti_iniu_top_dti_pr_iniu_define.sv
$DTI_TEST_DIR/build_logic/soc_dti_harden_up/dti_iniu_top_dti_iniu_pack.sv
$DTI_TEST_DIR/build_logic/soc_dti_harden_up/dti_iniu_top_dti_pr_iniu_async_top_side.sv
