$VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/vdspss1_tniu_noc_side_macros_d48321a35a.sv
$VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/sts_tniu_define.sv
$VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/lwnoc_sts_pack.sv
$VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/sts_tniu_noc.sv
$VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/sts_tniu_undefine.sv
