//[UHDL]Content Start [md5:c10fadc3066b0ca541495c43e677e341]
module dspss4_tniu (
	input          clk_src_clk_src                    ,
	input          rstn_src_rstn_src                  ,
	input          clk_dst_clk_dst                    ,
	input          rstn_dst_rstn_dst                  ,
	input          clk_dbg_timer                      ,
	input          rstn_dbg_timer                     ,
	input  [118:0] req_in_req_pld                     ,
	output         req_in_req_rdy                     ,
	input          req_in_req_vld                     ,
	output [64:0]  rsp_out_rsp_pld                    ,
	input          rsp_out_rsp_rdy                    ,
	output         rsp_out_rsp_vld                    ,
	output [31:0]  pmc_apb_pmc_paddr                  ,
	output         pmc_apb_pmc_penable                ,
	output [2:0]   pmc_apb_pmc_pprot                  ,
	input  [31:0]  pmc_apb_pmc_prdata                 ,
	input          pmc_apb_pmc_pready                 ,
	output         pmc_apb_pmc_psel                   ,
	input          pmc_apb_pmc_pslverr                ,
	output [3:0]   pmc_apb_pmc_pstrb                  ,
	output [31:0]  pmc_apb_pmc_pwdata                 ,
	output         pmc_apb_pmc_pwrite                 ,
	output [31:0]  sys_apb_m_paddr                    ,
	output         sys_apb_m_penable                  ,
	output [2:0]   sys_apb_m_pprot                    ,
	input  [63:0]  sys_apb_m_prdata                   ,
	input  [1:0]   sys_apb_m_pready                   ,
	output [1:0]   sys_apb_m_psel                     ,
	input  [1:0]   sys_apb_m_pslverr                  ,
	output [3:0]   sys_apb_m_pstrb                    ,
	output [31:0]  sys_apb_m_pwdata                   ,
	output         sys_apb_m_pwrite                   ,
	input  [31:0]  dbg_data_dbg_data_in               ,
	output [31:0]  dbg_data_dbg_data_out              ,
	input  [63:0]  dbg_timestamp_dbg_timestamp_in     ,
	output [63:0]  dbg_timestamp_dbg_timestamp_out    ,
	input  [7:0]   sys_cti_event_sys_cti_event_in     ,
	output [7:0]   sys_cti_event_sys_cti_event_out    ,
	input  [7:0]   noc_cti_event_noc_cti_event_in     ,
	output [7:0]   noc_cti_event_noc_cti_event_out    ,
	input  [7:0]   sys_cti_channel_sys_cti_channel_in ,
	output [7:0]   sys_cti_channel_sys_cti_channel_out,
	input  [7:0]   noc_cti_channel_noc_cti_channel_in ,
	output [7:0]   noc_cti_channel_noc_cti_channel_out);

	//Wire define for this module.

	//Wire define for sub module.

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	sts_tniu_sys sys_side (
		.clk_src(),
		.clk_dst(),
		.clk_dbg_timer(),
		.rstn_src(),
		.rstn_dst(),
		.rstn_dbg_timer(),
		.req_wptr_async(),
		.req_rptr_async(),
		.req_rptr_sync(),
		.req_pld_sync(),
		.rsp_wptr_async(),
		.rsp_rptr_async(),
		.rsp_rptr_sync(),
		.rsp_pld_sync(),
		.m_psel(),
		.m_paddr(),
		.m_pready(),
		.m_prdata(),
		.m_pslverr(),
		.m_pprot(),
		.m_penable(),
		.m_pwrite(),
		.m_pwdata(),
		.m_pstrb(),
		.cti_event_in(),
		.cti_event_in_req(),
		.cti_event_in_ack(),
		.cti_event_out(),
		.cti_event_out_req(),
		.cti_event_out_ack(),
		.cti_channel_in(),
		.cti_channel_in_req(),
		.cti_channel_in_ack(),
		.cti_channel_out(),
		.cti_channel_out_req(),
		.cti_channel_out_ack(),
		.dbg_data_in(),
		.dbg_data_out(),
		.dbg_timestamp_in(),
		.dbg_timestamp_out());
	sts_tniu_top top_side (
		.clk_src(clk_src_clk_src),
		.clk_dst(clk_dst_clk_dst),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_src(rstn_src_rstn_src),
		.rstn_dst(rstn_dst_rstn_dst),
		.rstn_dbg_timer(rstn_dbg_timer),
		.in_req_vld(req_in_req_vld),
		.in_req_rdy(req_in_req_rdy),
		.in_req_pld(req_in_req_pld),
		.out_rsp_vld(rsp_out_rsp_vld),
		.out_rsp_rdy(rsp_out_rsp_rdy),
		.out_rsp_pld(rsp_out_rsp_pld),
		.pmc_psel(pmc_apb_pmc_psel),
		.pmc_penable(pmc_apb_pmc_penable),
		.pmc_paddr(pmc_apb_pmc_paddr),
		.pmc_pwrite(pmc_apb_pmc_pwrite),
		.pmc_pwdata(pmc_apb_pmc_pwdata),
		.pmc_prdata(pmc_apb_pmc_prdata),
		.pmc_pready(pmc_apb_pmc_pready),
		.pmc_pstrb(pmc_apb_pmc_pstrb),
		.pmc_pprot(pmc_apb_pmc_pprot),
		.pmc_pslverr(pmc_apb_pmc_pslverr),
		.m_psel(sys_apb_m_psel),
		.m_paddr(sys_apb_m_paddr),
		.m_pready(sys_apb_m_pready),
		.m_prdata(sys_apb_m_prdata),
		.m_pslverr(sys_apb_m_pslverr),
		.m_pprot(sys_apb_m_pprot),
		.m_penable(sys_apb_m_penable),
		.m_pwrite(sys_apb_m_pwrite),
		.m_pwdata(sys_apb_m_pwdata),
		.m_pstrb(sys_apb_m_pstrb),
		.dbg_data_in(dbg_data_dbg_data_in),
		.dbg_data_out(dbg_data_dbg_data_out),
		.dbg_timestamp_in(dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_out(dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_in(sys_cti_event_sys_cti_event_in),
		.sys_cti_event_out(sys_cti_event_sys_cti_event_out),
		.noc_cti_event_out(noc_cti_event_noc_cti_event_out),
		.noc_cti_event_in(noc_cti_event_noc_cti_event_in),
		.sys_cti_channel_in(sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_out(sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_out(noc_cti_channel_noc_cti_channel_out),
		.noc_cti_channel_in(noc_cti_channel_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());

endmodule
//[UHDL]Content End [md5:c10fadc3066b0ca541495c43e677e341]

