//[UHDL]Content Start [md5:121ec702cd13918b6b11987bd5ad610c]
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_apb32_to_cti_apb12.v
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_apb_idle_target.v
-f $STS_VPUSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vpu_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vpu_ss_tniu_top_wrap.v
-f $STS_VDSPSS5_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss5_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss5_tniu_top_wrap.v
-f $STS_VDSPSS4_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss4_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss4_tniu_top_wrap.v
-f $STS_VDSPSS3_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss3_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss3_tniu_top_wrap.v
-f $STS_VDSPSS2_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss2_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss2_tniu_top_wrap.v
-f $STS_VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss1_tniu_top_wrap.v
-f $STS_VDSPSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss0_tniu_top_wrap.v
-f $STS_USB_DPSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_usb_dpss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_usb_dpss_tniu_top_wrap.v
-f $STS_UFSSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ufs_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ufs_ss_tniu_top_wrap.v
-f $STS_AON_LOCAL_TNIU_NOC_SIDE_OUT_DIR/sts_noc_aon_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_aon_ss_tniu_top_wrap.v
-f $STS_PERISS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_peri_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_peri_ss_tniu_top_wrap.v
-f $STS_PCIE_ETHSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_pcie_eth_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_pcie_eth_ss_tniu_top_wrap.v
-f $STS_NPUSS4_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss4_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss4_tniu_top_wrap.v
-f $STS_NPUSS3_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss3_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss3_tniu_top_wrap.v
-f $STS_NPUSS2_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss2_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss2_tniu_top_wrap.v
-f $STS_NPUSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss1_tniu_top_wrap.v
-f $STS_NPUSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss0_tniu_top_wrap.v
-f $STS_NOCSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_noc_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_noc_ss_tniu_top_wrap.v
-f $STS_MIPISS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_mipi_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_mipi_ss_tniu_top_wrap.v
-f $STS_MCUSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_mcu_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_mcu_ss_tniu_top_wrap.v
-f $STS_GPUSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_gpu_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_gpu_ss1_tniu_top_wrap.v
-f $STS_GPUSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_gpu_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_gpu_ss0_tniu_top_wrap.v
-f $STS_DISPLAYSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_display_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_display_ss_tniu_top_wrap.v
-f $STS_DEBUGSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_debug_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_debug_ss_tniu_top_wrap.v
-f $STS_DDRSS9_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss9_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss9_tniu_top_wrap.v
-f $STS_DDRSS8_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss8_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss8_tniu_top_wrap.v
-f $STS_DDRSS7_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss7_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss7_tniu_top_wrap.v
-f $STS_DDRSS6_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss6_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss6_tniu_top_wrap.v
-f $STS_DDRSS5_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss5_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss5_tniu_top_wrap.v
-f $STS_DDRSS4_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss4_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss4_tniu_top_wrap.v
-f $STS_DDRSS3_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss3_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss3_tniu_top_wrap.v
-f $STS_DDRSS2_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss2_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss2_tniu_top_wrap.v
-f $STS_DDRSS11_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss11_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss11_tniu_top_wrap.v
-f $STS_DDRSS10_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss10_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss10_tniu_top_wrap.v
-f $STS_DDRSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss1_tniu_top_wrap.v
-f $STS_DDRSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss0_tniu_top_wrap.v
-f $STS_CPUSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_cpu_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_cpu_ss_tniu_top_wrap.v
-f $STS_CAMERASS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_camera_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_camera_ss_tniu_top_wrap.v
-f $STS_DEC_L3_LOWER_MID_OUT_DIR/sts_noc_sts_dec_l3_lower_mid_filelist.f
-f $STS_DEC_L2_RIGHT_LOWER_OUT_DIR/sts_noc_sts_dec_l2_right_lower_filelist.f
-f $STS_DEC_L1_RIGHT_UPPER_OUT_DIR/sts_noc_sts_dec_l1_right_upper_filelist.f
-f $STS_DEC_L2_LEFT_DDR_OUT_DIR/sts_noc_sts_dec_l2_left_ddr_filelist.f
-f $STS_DEC_L1_UPPER_CTRL_OUT_DIR/sts_noc_sts_dec_l1_upper_ctrl_filelist.f
-f $STS_DEC_L0_ROOT_OUT_DIR/sts_noc_sts_dec_l0_root_filelist.f
-f $STS_AON_SS_INIU_NOC_SIDE_OUT_DIR/sts_noc_aon_ss_iniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_aon_ss_iniu_top_wrap.v
$STS_SOC_NOC/sts_soc_top_wrap/sts_soc_top_wrap.v
//[UHDL]Content End [md5:121ec702cd13918b6b11987bd5ad610c]

