//[UHDL]Content Start [md5:96d81f2f52c577bb7491b7115e423c32]
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_apb32_to_cti_apb12.v
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_apb_idle_target.v
-f $VPUSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vpu_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vpu_ss_tniu_top_wrap.v
-f $VDSPSS5_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss5_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss5_tniu_top_wrap.v
-f $VDSPSS4_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss4_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss4_tniu_top_wrap.v
-f $VDSPSS3_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss3_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss3_tniu_top_wrap.v
-f $VDSPSS2_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss2_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss2_tniu_top_wrap.v
-f $VDSPSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss1_tniu_top_wrap.v
-f $VDSPSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_vdsp_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_vdsp_ss0_tniu_top_wrap.v
-f $USB_DPSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_usb_dpss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_usb_dpss_tniu_top_wrap.v
-f $UFSSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ufs_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ufs_ss_tniu_top_wrap.v
-f $AON_LOCAL_TNIU_NOC_SIDE_OUT_DIR/sts_noc_aon_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_aon_ss_tniu_top_wrap.v
-f $PERISS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_peri_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_peri_ss_tniu_top_wrap.v
-f $PCIE_ETHSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_pcie_eth_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_pcie_eth_ss_tniu_top_wrap.v
-f $NPUSS4_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss4_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss4_tniu_top_wrap.v
-f $NPUSS3_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss3_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss3_tniu_top_wrap.v
-f $NPUSS2_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss2_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss2_tniu_top_wrap.v
-f $NPUSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss1_tniu_top_wrap.v
-f $NPUSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_npu_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_npu_ss0_tniu_top_wrap.v
-f $NOCSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_noc_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_noc_ss_tniu_top_wrap.v
-f $MIPISS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_mipi_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_mipi_ss_tniu_top_wrap.v
-f $MCUSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_mcu_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_mcu_ss_tniu_top_wrap.v
-f $GPUSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_gpu_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_gpu_ss1_tniu_top_wrap.v
-f $GPUSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_gpu_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_gpu_ss0_tniu_top_wrap.v
-f $DISPLAYSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_display_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_display_ss_tniu_top_wrap.v
-f $DEBUGSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_debug_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_debug_ss_tniu_top_wrap.v
-f $DDRSS9_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss9_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss9_tniu_top_wrap.v
-f $DDRSS8_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss8_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss8_tniu_top_wrap.v
-f $DDRSS7_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss7_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss7_tniu_top_wrap.v
-f $DDRSS6_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss6_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss6_tniu_top_wrap.v
-f $DDRSS5_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss5_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss5_tniu_top_wrap.v
-f $DDRSS4_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss4_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss4_tniu_top_wrap.v
-f $DDRSS3_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss3_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss3_tniu_top_wrap.v
-f $DDRSS2_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss2_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss2_tniu_top_wrap.v
-f $DDRSS11_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss11_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss11_tniu_top_wrap.v
-f $DDRSS10_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss10_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss10_tniu_top_wrap.v
-f $DDRSS1_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss1_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss1_tniu_top_wrap.v
-f $DDRSS0_TNIU_NOC_SIDE_OUT_DIR/sts_noc_ddr_ss0_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_ddr_ss0_tniu_top_wrap.v
-f $CPUSS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_cpu_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_cpu_ss_tniu_top_wrap.v
-f $CAMERASS_TNIU_NOC_SIDE_OUT_DIR/sts_noc_camera_ss_tniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_camera_ss_tniu_top_wrap.v
-f $STS_DEC_L3_LOWER_MID_OUT_DIR/filelist.f
-f $STS_DEC_L2_RIGHT_LOWER_OUT_DIR/filelist.f
-f $STS_DEC_L1_RIGHT_UPPER_OUT_DIR/filelist.f
-f $STS_DEC_L2_LEFT_DDR_OUT_DIR/filelist.f
-f $STS_DEC_L1_UPPER_CTRL_OUT_DIR/filelist.f
-f $STS_DEC_L0_ROOT_OUT_DIR/filelist.f
-f $AON_SS_INIU_NOC_SIDE_OUT_DIR/sts_noc_aon_ss_iniu_filelist.f
$STS_SOC_NOC/sts_soc_top_wrap/sts_noc_aon_ss_iniu_top_wrap.v
$STS_SOC_NOC/sts_soc_top_wrap/sts_soc_top_wrap.v
//[UHDL]Content End [md5:96d81f2f52c577bb7491b7115e423c32]

