//[UHDL]Content Start [md5:96001bd15b758d3b60f2740daea15b5a]
module soc_sts_noc (
	input          clk_sys                                                                                                            ,
	input          rst_sys_n                                                                                                          ,
	input          clk_harden_dn_func                                                                                                 ,
	input          rst_harden_dn_func_n                                                                                               ,
	input          clk_harden_up_func                                                                                                 ,
	input          rst_harden_up_func_n                                                                                               ,
	input          clk_dbg_timer                                                                                                      ,
	input          rst_dbg_timer_n                                                                                                    ,
	input  [7:0]   aon_ss_iniu_node_id_porting_node_id_node_id                                                                        ,
	input  [31:0]  aon_ss_iniu_axi_porting_axi_sts_iniu_s_araddr                                                                      ,
	input  [1:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arburst                                                                     ,
	input  [3:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arcache                                                                     ,
	input  [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arid                                                                        ,
	input  [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arlen                                                                       ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_arlock                                                                      ,
	input  [2:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arprot                                                                      ,
	input  [3:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arqos                                                                       ,
	output         aon_ss_iniu_axi_porting_axi_sts_iniu_s_arready                                                                     ,
	input  [2:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_arsize                                                                      ,
	input  [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_aruser                                                                      ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_arvalid                                                                     ,
	input  [31:0]  aon_ss_iniu_axi_porting_axi_sts_iniu_s_awaddr                                                                      ,
	input  [1:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awburst                                                                     ,
	input  [3:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awcache                                                                     ,
	input  [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awid                                                                        ,
	input  [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awlen                                                                       ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_awlock                                                                      ,
	input  [2:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awprot                                                                      ,
	input  [3:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awqos                                                                       ,
	output         aon_ss_iniu_axi_porting_axi_sts_iniu_s_awready                                                                     ,
	input  [2:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awsize                                                                      ,
	input  [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_awuser                                                                      ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_awvalid                                                                     ,
	output [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_bid                                                                         ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_bready                                                                      ,
	output [1:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_bresp                                                                       ,
	output         aon_ss_iniu_axi_porting_axi_sts_iniu_s_bvalid                                                                      ,
	output [31:0]  aon_ss_iniu_axi_porting_axi_sts_iniu_s_rdata                                                                       ,
	output [7:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_rid                                                                         ,
	output         aon_ss_iniu_axi_porting_axi_sts_iniu_s_rlast                                                                       ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_rready                                                                      ,
	output [1:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_rresp                                                                       ,
	output         aon_ss_iniu_axi_porting_axi_sts_iniu_s_rvalid                                                                      ,
	input  [31:0]  aon_ss_iniu_axi_porting_axi_sts_iniu_s_wdata                                                                       ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_wlast                                                                       ,
	output         aon_ss_iniu_axi_porting_axi_sts_iniu_s_wready                                                                      ,
	input  [3:0]   aon_ss_iniu_axi_porting_axi_sts_iniu_s_wstrb                                                                       ,
	input          aon_ss_iniu_axi_porting_axi_sts_iniu_s_wvalid                                                                      ,
	input  [7:0]   aon_ss_iniu_cti_event_porting_cti_event_noc_cti_event_in                                                           ,
	output [7:0]   aon_ss_iniu_cti_event_porting_cti_event_noc_cti_event_out                                                          ,
	input  [7:0]   aon_ss_iniu_cti_event_porting_cti_event_sys_cti_event_in                                                           ,
	output [7:0]   aon_ss_iniu_cti_event_porting_cti_event_sys_cti_event_out                                                          ,
	input  [7:0]   aon_ss_iniu_cti_channel_porting_cti_channel_noc_cti_channel_in                                                     ,
	output [7:0]   aon_ss_iniu_cti_channel_porting_cti_channel_noc_cti_channel_out                                                    ,
	input  [7:0]   aon_ss_iniu_cti_channel_porting_cti_channel_sys_cti_channel_in                                                     ,
	output [7:0]   aon_ss_iniu_cti_channel_porting_cti_channel_sys_cti_channel_out                                                    ,
	input  [63:0]  aon_ss_iniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  aon_ss_iniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [31:0]  aon_ss_iniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  aon_ss_iniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_node_id_porting_aon_ss_iniu_sys_side_node_id_porting_node_id                      ,
	input  [31:0]  aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_araddr                             ,
	input  [1:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arburst                            ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arcache                            ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arid                               ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arlen                              ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arlock                             ,
	input  [2:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arprot                             ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arqos                              ,
	output         aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arready                            ,
	input  [2:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arsize                             ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_aruser                             ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arvalid                            ,
	input  [31:0]  aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awaddr                             ,
	input  [1:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awburst                            ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awcache                            ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awid                               ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awlen                              ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awlock                             ,
	input  [2:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awprot                             ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awqos                              ,
	output         aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awready                            ,
	input  [2:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awsize                             ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awuser                             ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awvalid                            ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bid                                ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bready                             ,
	output [1:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bresp                              ,
	output         aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bvalid                             ,
	output [31:0]  aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rdata                              ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rid                                ,
	output         aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rlast                              ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rready                             ,
	output [1:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rresp                              ,
	output         aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rvalid                             ,
	input  [31:0]  aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wdata                              ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wlast                              ,
	output         aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wready                             ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wstrb                              ,
	input          aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wvalid                             ,
	output [120:0] aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_pld_sync             ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_rptr_async           ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_rptr_sync            ,
	output [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_wptr_async           ,
	input  [66:0]  aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_pld_sync             ,
	output [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_async           ,
	output [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_sync            ,
	input  [3:0]   aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_wptr_async           ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_in             ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_ack         ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_req         ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_out            ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_ack        ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_req        ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in       ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_ack   ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_req   ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out      ,
	output [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_ack  ,
	input  [7:0]   aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_req  ,
	input  [63:0]  aon_ss_iniu_aon_ss_iniu_sys_side_dbg_timestamp_porting_aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_in ,
	output [63:0]  aon_ss_iniu_aon_ss_iniu_sys_side_dbg_timestamp_porting_aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_out,
	input  [31:0]  aon_ss_iniu_aon_ss_iniu_sys_side_dbg_data_porting_aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_in                ,
	output [31:0]  aon_ss_iniu_aon_ss_iniu_sys_side_dbg_data_porting_aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_out               ,
	output [31:0]  vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  vpu_ss_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         vpu_ss_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   vpu_ss_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  vpu_ss_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   vpu_ss_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   vpu_ss_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   vpu_ss_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   vpu_ss_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  vpu_ss_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         vpu_ss_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  vpu_ss_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  vpu_ss_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  vpu_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  vpu_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   vpu_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   vpu_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   vpu_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   vpu_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   vpu_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   vpu_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   vpu_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   vpu_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            ,
	output [31:0]  camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                   ,
	output         camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                 ,
	output [2:0]   camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                   ,
	input  [31:0]  camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                  ,
	input          camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                  ,
	output         camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                    ,
	input          camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                 ,
	output [3:0]   camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                   ,
	output [31:0]  camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                  ,
	output         camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                  ,
	output [31:0]  camera_ss_tniu_sys_apb_porting_sys_apb_m_paddr                                                                     ,
	output         camera_ss_tniu_sys_apb_porting_sys_apb_m_penable                                                                   ,
	output [2:0]   camera_ss_tniu_sys_apb_porting_sys_apb_m_pprot                                                                     ,
	input  [63:0]  camera_ss_tniu_sys_apb_porting_sys_apb_m_prdata                                                                    ,
	input  [1:0]   camera_ss_tniu_sys_apb_porting_sys_apb_m_pready                                                                    ,
	output [1:0]   camera_ss_tniu_sys_apb_porting_sys_apb_m_psel                                                                      ,
	input  [1:0]   camera_ss_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                   ,
	output [3:0]   camera_ss_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                     ,
	output [31:0]  camera_ss_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                    ,
	output         camera_ss_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                    ,
	input  [31:0]  camera_ss_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                               ,
	output [31:0]  camera_ss_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                              ,
	input  [63:0]  camera_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                ,
	output [63:0]  camera_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                               ,
	input  [7:0]   camera_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                ,
	output [7:0]   camera_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                               ,
	input  [7:0]   camera_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                ,
	output [7:0]   camera_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                               ,
	input  [7:0]   camera_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                          ,
	output [7:0]   camera_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                         ,
	input  [7:0]   camera_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                          ,
	output [7:0]   camera_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                         ,
	output [31:0]  dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  dspss0_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         dspss0_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   dspss0_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  dspss0_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   dspss0_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   dspss0_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   dspss0_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   dspss0_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  dspss0_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         dspss0_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  dspss0_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  dspss0_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  dspss0_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  dspss0_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   dspss0_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   dspss0_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   dspss0_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   dspss0_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   dspss0_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   dspss0_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   dspss0_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   dspss0_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            ,
	output [31:0]  dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  dspss1_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         dspss1_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   dspss1_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  dspss1_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   dspss1_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   dspss1_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   dspss1_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   dspss1_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  dspss1_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         dspss1_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  dspss1_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  dspss1_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  dspss1_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  dspss1_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   dspss1_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   dspss1_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   dspss1_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   dspss1_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   dspss1_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   dspss1_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   dspss1_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   dspss1_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            ,
	output [31:0]  dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  dspss2_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         dspss2_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   dspss2_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  dspss2_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   dspss2_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   dspss2_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   dspss2_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   dspss2_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  dspss2_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         dspss2_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  dspss2_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  dspss2_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  dspss2_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  dspss2_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   dspss2_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   dspss2_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   dspss2_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   dspss2_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   dspss2_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   dspss2_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   dspss2_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   dspss2_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            ,
	output [31:0]  dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  dspss3_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         dspss3_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   dspss3_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  dspss3_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   dspss3_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   dspss3_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   dspss3_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   dspss3_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  dspss3_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         dspss3_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  dspss3_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  dspss3_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  dspss3_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  dspss3_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   dspss3_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   dspss3_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   dspss3_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   dspss3_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   dspss3_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   dspss3_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   dspss3_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   dspss3_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            ,
	output [31:0]  dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  dspss4_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         dspss4_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   dspss4_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  dspss4_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   dspss4_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   dspss4_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   dspss4_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   dspss4_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  dspss4_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         dspss4_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  dspss4_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  dspss4_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  dspss4_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  dspss4_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   dspss4_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   dspss4_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   dspss4_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   dspss4_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   dspss4_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   dspss4_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   dspss4_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   dspss4_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            ,
	output [31:0]  dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_paddr                                                                      ,
	output         dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_penable                                                                    ,
	output [2:0]   dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pprot                                                                      ,
	input  [31:0]  dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_prdata                                                                     ,
	input          dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pready                                                                     ,
	output         dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_psel                                                                       ,
	input          dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr                                                                    ,
	output [3:0]   dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb                                                                      ,
	output [31:0]  dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata                                                                     ,
	output         dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite                                                                     ,
	output [31:0]  dspss5_tniu_sys_apb_porting_sys_apb_m_paddr                                                                        ,
	output         dspss5_tniu_sys_apb_porting_sys_apb_m_penable                                                                      ,
	output [2:0]   dspss5_tniu_sys_apb_porting_sys_apb_m_pprot                                                                        ,
	input  [63:0]  dspss5_tniu_sys_apb_porting_sys_apb_m_prdata                                                                       ,
	input  [1:0]   dspss5_tniu_sys_apb_porting_sys_apb_m_pready                                                                       ,
	output [1:0]   dspss5_tniu_sys_apb_porting_sys_apb_m_psel                                                                         ,
	input  [1:0]   dspss5_tniu_sys_apb_porting_sys_apb_m_pslverr                                                                      ,
	output [3:0]   dspss5_tniu_sys_apb_porting_sys_apb_m_pstrb                                                                        ,
	output [31:0]  dspss5_tniu_sys_apb_porting_sys_apb_m_pwdata                                                                       ,
	output         dspss5_tniu_sys_apb_porting_sys_apb_m_pwrite                                                                       ,
	input  [31:0]  dspss5_tniu_dbg_data_porting_dbg_data_dbg_data_in                                                                  ,
	output [31:0]  dspss5_tniu_dbg_data_porting_dbg_data_dbg_data_out                                                                 ,
	input  [63:0]  dspss5_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in                                                   ,
	output [63:0]  dspss5_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out                                                  ,
	input  [7:0]   dspss5_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in                                                   ,
	output [7:0]   dspss5_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out                                                  ,
	input  [7:0]   dspss5_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in                                                   ,
	output [7:0]   dspss5_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out                                                  ,
	input  [7:0]   dspss5_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in                                             ,
	output [7:0]   dspss5_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out                                            ,
	input  [7:0]   dspss5_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in                                             ,
	output [7:0]   dspss5_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out                                            );

	//Wire define for this module.

	//Wire define for sub module.
	wire         dec0_TO_aon_ss_iniu_SIG_mst_req_rdy                                    ;
	wire [64:0]  dec0_TO_aon_ss_iniu_SIG_mst_rsp_pld                                    ;
	wire         dec0_TO_aon_ss_iniu_SIG_mst_rsp_vld                                    ;
	wire         aon_ss_iniu_TO_dec0_SIG_req_out_req_vld                                ;
	wire [118:0] aon_ss_iniu_TO_dec0_SIG_req_out_req_pld                                ;
	wire         aon_ss_iniu_TO_dec0_SIG_rsp_in_rsp_rdy                                 ;
	wire         harden_up_async_bridge_mst_TO_dec2_SIG_out_rsp_vld                     ;
	wire [118:0] harden_up_async_bridge_mst_TO_dec2_SIG_out_rsp_pld                     ;
	wire [15:0]  harden_up_async_bridge_mst_TO_harden_dn_async_bridge_slv_SIG_rptr_async;
	wire [15:0]  harden_up_async_bridge_mst_TO_harden_dn_async_bridge_slv_SIG_rptr_sync ;
	wire         dec2_TO_harden_up_async_bridge_mst_SIG_mst_req_rdy                     ;
	wire [15:0]  harden_dn_async_bridge_slv_TO_harden_up_async_bridge_mst_SIG_wptr_async;
	wire [119:0] harden_dn_async_bridge_slv_TO_harden_up_async_bridge_mst_SIG_pld_sync  ;

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	aon_ss_iniu aon_ss_iniu (
		.clk_src(clk_sys),
		.rstn_src(rst_sys_n),
		.clk_dst(clk_harden_dn_func),
		.rstn_dst(rst_harden_dn_func_n),
		.node_id_node_id(aon_ss_iniu_node_id_porting_node_id_node_id),
		.axi_sts_iniu_s_araddr(aon_ss_iniu_axi_porting_axi_sts_iniu_s_araddr),
		.axi_sts_iniu_s_arburst(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arburst),
		.axi_sts_iniu_s_arcache(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arcache),
		.axi_sts_iniu_s_arid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arid),
		.axi_sts_iniu_s_arlen(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arlen),
		.axi_sts_iniu_s_arlock(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arlock),
		.axi_sts_iniu_s_arprot(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arprot),
		.axi_sts_iniu_s_arqos(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arqos),
		.axi_sts_iniu_s_arready(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arready),
		.axi_sts_iniu_s_arsize(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arsize),
		.axi_sts_iniu_s_aruser(aon_ss_iniu_axi_porting_axi_sts_iniu_s_aruser),
		.axi_sts_iniu_s_arvalid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_arvalid),
		.axi_sts_iniu_s_awaddr(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awaddr),
		.axi_sts_iniu_s_awburst(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awburst),
		.axi_sts_iniu_s_awcache(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awcache),
		.axi_sts_iniu_s_awid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awid),
		.axi_sts_iniu_s_awlen(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awlen),
		.axi_sts_iniu_s_awlock(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awlock),
		.axi_sts_iniu_s_awprot(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awprot),
		.axi_sts_iniu_s_awqos(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awqos),
		.axi_sts_iniu_s_awready(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awready),
		.axi_sts_iniu_s_awsize(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awsize),
		.axi_sts_iniu_s_awuser(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awuser),
		.axi_sts_iniu_s_awvalid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_awvalid),
		.axi_sts_iniu_s_bid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_bid),
		.axi_sts_iniu_s_bready(aon_ss_iniu_axi_porting_axi_sts_iniu_s_bready),
		.axi_sts_iniu_s_bresp(aon_ss_iniu_axi_porting_axi_sts_iniu_s_bresp),
		.axi_sts_iniu_s_bvalid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_bvalid),
		.axi_sts_iniu_s_rdata(aon_ss_iniu_axi_porting_axi_sts_iniu_s_rdata),
		.axi_sts_iniu_s_rid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_rid),
		.axi_sts_iniu_s_rlast(aon_ss_iniu_axi_porting_axi_sts_iniu_s_rlast),
		.axi_sts_iniu_s_rready(aon_ss_iniu_axi_porting_axi_sts_iniu_s_rready),
		.axi_sts_iniu_s_rresp(aon_ss_iniu_axi_porting_axi_sts_iniu_s_rresp),
		.axi_sts_iniu_s_rvalid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_rvalid),
		.axi_sts_iniu_s_wdata(aon_ss_iniu_axi_porting_axi_sts_iniu_s_wdata),
		.axi_sts_iniu_s_wlast(aon_ss_iniu_axi_porting_axi_sts_iniu_s_wlast),
		.axi_sts_iniu_s_wready(aon_ss_iniu_axi_porting_axi_sts_iniu_s_wready),
		.axi_sts_iniu_s_wstrb(aon_ss_iniu_axi_porting_axi_sts_iniu_s_wstrb),
		.axi_sts_iniu_s_wvalid(aon_ss_iniu_axi_porting_axi_sts_iniu_s_wvalid),
		.req_out_req_pld(aon_ss_iniu_TO_dec0_SIG_req_out_req_pld),
		.req_out_req_rdy(dec0_TO_aon_ss_iniu_SIG_mst_req_rdy),
		.req_out_req_vld(aon_ss_iniu_TO_dec0_SIG_req_out_req_vld),
		.rsp_in_rsp_pld(dec0_TO_aon_ss_iniu_SIG_mst_rsp_pld),
		.rsp_in_rsp_rdy(aon_ss_iniu_TO_dec0_SIG_rsp_in_rsp_rdy),
		.rsp_in_rsp_vld(dec0_TO_aon_ss_iniu_SIG_mst_rsp_vld),
		.cti_event_noc_cti_event_in(aon_ss_iniu_cti_event_porting_cti_event_noc_cti_event_in),
		.cti_event_noc_cti_event_out(aon_ss_iniu_cti_event_porting_cti_event_noc_cti_event_out),
		.cti_event_sys_cti_event_in(aon_ss_iniu_cti_event_porting_cti_event_sys_cti_event_in),
		.cti_event_sys_cti_event_out(aon_ss_iniu_cti_event_porting_cti_event_sys_cti_event_out),
		.cti_channel_noc_cti_channel_in(aon_ss_iniu_cti_channel_porting_cti_channel_noc_cti_channel_in),
		.cti_channel_noc_cti_channel_out(aon_ss_iniu_cti_channel_porting_cti_channel_noc_cti_channel_out),
		.cti_channel_sys_cti_channel_in(aon_ss_iniu_cti_channel_porting_cti_channel_sys_cti_channel_in),
		.cti_channel_sys_cti_channel_out(aon_ss_iniu_cti_channel_porting_cti_channel_sys_cti_channel_out),
		.dbg_timestamp_dbg_timestamp_in(aon_ss_iniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(aon_ss_iniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.dbg_data_dbg_data_in(aon_ss_iniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(aon_ss_iniu_dbg_data_porting_dbg_data_dbg_data_out),
		.aon_ss_iniu_sys_side_node_id_porting_node_id(aon_ss_iniu_aon_ss_iniu_sys_side_node_id_porting_aon_ss_iniu_sys_side_node_id_porting_node_id),
		.aon_ss_iniu_sys_side_axi_porting_s_araddr(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_araddr),
		.aon_ss_iniu_sys_side_axi_porting_s_arburst(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arburst),
		.aon_ss_iniu_sys_side_axi_porting_s_arcache(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arcache),
		.aon_ss_iniu_sys_side_axi_porting_s_arid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arid),
		.aon_ss_iniu_sys_side_axi_porting_s_arlen(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arlen),
		.aon_ss_iniu_sys_side_axi_porting_s_arlock(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arlock),
		.aon_ss_iniu_sys_side_axi_porting_s_arprot(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arprot),
		.aon_ss_iniu_sys_side_axi_porting_s_arqos(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arqos),
		.aon_ss_iniu_sys_side_axi_porting_s_arready(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arready),
		.aon_ss_iniu_sys_side_axi_porting_s_arsize(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arsize),
		.aon_ss_iniu_sys_side_axi_porting_s_aruser(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_aruser),
		.aon_ss_iniu_sys_side_axi_porting_s_arvalid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_arvalid),
		.aon_ss_iniu_sys_side_axi_porting_s_awaddr(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awaddr),
		.aon_ss_iniu_sys_side_axi_porting_s_awburst(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awburst),
		.aon_ss_iniu_sys_side_axi_porting_s_awcache(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awcache),
		.aon_ss_iniu_sys_side_axi_porting_s_awid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awid),
		.aon_ss_iniu_sys_side_axi_porting_s_awlen(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awlen),
		.aon_ss_iniu_sys_side_axi_porting_s_awlock(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awlock),
		.aon_ss_iniu_sys_side_axi_porting_s_awprot(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awprot),
		.aon_ss_iniu_sys_side_axi_porting_s_awqos(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awqos),
		.aon_ss_iniu_sys_side_axi_porting_s_awready(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awready),
		.aon_ss_iniu_sys_side_axi_porting_s_awsize(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awsize),
		.aon_ss_iniu_sys_side_axi_porting_s_awuser(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awuser),
		.aon_ss_iniu_sys_side_axi_porting_s_awvalid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_awvalid),
		.aon_ss_iniu_sys_side_axi_porting_s_bid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bid),
		.aon_ss_iniu_sys_side_axi_porting_s_bready(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bready),
		.aon_ss_iniu_sys_side_axi_porting_s_bresp(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bresp),
		.aon_ss_iniu_sys_side_axi_porting_s_bvalid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_bvalid),
		.aon_ss_iniu_sys_side_axi_porting_s_rdata(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rdata),
		.aon_ss_iniu_sys_side_axi_porting_s_rid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rid),
		.aon_ss_iniu_sys_side_axi_porting_s_rlast(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rlast),
		.aon_ss_iniu_sys_side_axi_porting_s_rready(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rready),
		.aon_ss_iniu_sys_side_axi_porting_s_rresp(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rresp),
		.aon_ss_iniu_sys_side_axi_porting_s_rvalid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_rvalid),
		.aon_ss_iniu_sys_side_axi_porting_s_wdata(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wdata),
		.aon_ss_iniu_sys_side_axi_porting_s_wlast(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wlast),
		.aon_ss_iniu_sys_side_axi_porting_s_wready(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wready),
		.aon_ss_iniu_sys_side_axi_porting_s_wstrb(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wstrb),
		.aon_ss_iniu_sys_side_axi_porting_s_wvalid(aon_ss_iniu_aon_ss_iniu_sys_side_axi_porting_aon_ss_iniu_sys_side_axi_porting_s_wvalid),
		.aon_ss_iniu_sys_side_req_async_porting_req_pld_sync(aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_pld_sync),
		.aon_ss_iniu_sys_side_req_async_porting_req_rptr_async(aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_rptr_async),
		.aon_ss_iniu_sys_side_req_async_porting_req_rptr_sync(aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_rptr_sync),
		.aon_ss_iniu_sys_side_req_async_porting_req_wptr_async(aon_ss_iniu_aon_ss_iniu_sys_side_req_async_porting_aon_ss_iniu_sys_side_req_async_porting_req_wptr_async),
		.aon_ss_iniu_sys_side_rsp_async_porting_rsp_pld_sync(aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_pld_sync),
		.aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_async(aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_async),
		.aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_sync(aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_sync),
		.aon_ss_iniu_sys_side_rsp_async_porting_rsp_wptr_async(aon_ss_iniu_aon_ss_iniu_sys_side_rsp_async_porting_aon_ss_iniu_sys_side_rsp_async_porting_rsp_wptr_async),
		.aon_ss_iniu_sys_side_cti_event_porting_cti_event_in(aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_in),
		.aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_ack(aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_ack),
		.aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_req(aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_req),
		.aon_ss_iniu_sys_side_cti_event_porting_cti_event_out(aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_out),
		.aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_ack(aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_ack),
		.aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_req(aon_ss_iniu_aon_ss_iniu_sys_side_cti_event_porting_aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_req),
		.aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in(aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in),
		.aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_ack(aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_ack),
		.aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_req(aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_req),
		.aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out(aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out),
		.aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_ack(aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_ack),
		.aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_req(aon_ss_iniu_aon_ss_iniu_sys_side_cti_channel_porting_aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_req),
		.aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_in(aon_ss_iniu_aon_ss_iniu_sys_side_dbg_timestamp_porting_aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_in),
		.aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_out(aon_ss_iniu_aon_ss_iniu_sys_side_dbg_timestamp_porting_aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_out),
		.aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_in(aon_ss_iniu_aon_ss_iniu_sys_side_dbg_data_porting_aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_in),
		.aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_out(aon_ss_iniu_aon_ss_iniu_sys_side_dbg_data_porting_aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_out));
	sts_noc_dec_node dec0 (
		.clk(clk_harden_dn_func),
		.rst_n(rst_harden_dn_func_n),
		.mst_req_vld(aon_ss_iniu_TO_dec0_SIG_req_out_req_vld),
		.mst_req_rdy(dec0_TO_aon_ss_iniu_SIG_mst_req_rdy),
		.mst_req_pld(aon_ss_iniu_TO_dec0_SIG_req_out_req_pld),
		.mst_rsp_vld(dec0_TO_aon_ss_iniu_SIG_mst_rsp_vld),
		.mst_rsp_rdy(aon_ss_iniu_TO_dec0_SIG_rsp_in_rsp_rdy),
		.mst_rsp_pld(dec0_TO_aon_ss_iniu_SIG_mst_rsp_pld),
		.slv_req_vld(),
		.slv_req_rdy(),
		.slv_req_pld(),
		.slv_rsp_vld(),
		.slv_rsp_rdy(),
		.slv_rsp_pld(),
		.mst_cti_channel_in(),
		.mst_cti_channel_out(),
		.slv_cti_channel_in(),
		.slv_cti_channel_out(),
		.mst_cti_event_in(),
		.mst_cti_event_out(),
		.slv_cti_event_in(),
		.slv_cti_event_out(),
		.mst_dbg_timestamp(),
		.slv_dbg_timestamp(),
		.slv_dbg_data(),
		.mst_dbg_data());
	sts_noc_dec_node dec1 (
		.clk(clk_harden_dn_func),
		.rst_n(rst_harden_dn_func_n),
		.mst_req_vld(),
		.mst_req_rdy(),
		.mst_req_pld(),
		.mst_rsp_vld(),
		.mst_rsp_rdy(),
		.mst_rsp_pld(),
		.slv_req_vld(),
		.slv_req_rdy(),
		.slv_req_pld(),
		.slv_rsp_vld(),
		.slv_rsp_rdy(),
		.slv_rsp_pld(),
		.mst_cti_channel_in(),
		.mst_cti_channel_out(),
		.slv_cti_channel_in(),
		.slv_cti_channel_out(),
		.mst_cti_event_in(),
		.mst_cti_event_out(),
		.slv_cti_event_in(),
		.slv_cti_event_out(),
		.mst_dbg_timestamp(),
		.slv_dbg_timestamp(),
		.slv_dbg_data(),
		.mst_dbg_data());
	sts_noc_dec_node dec2 (
		.clk(clk_harden_up_func),
		.rst_n(rst_harden_up_func_n),
		.mst_req_vld(harden_up_async_bridge_mst_TO_dec2_SIG_out_rsp_vld),
		.mst_req_rdy(dec2_TO_harden_up_async_bridge_mst_SIG_mst_req_rdy),
		.mst_req_pld(harden_up_async_bridge_mst_TO_dec2_SIG_out_rsp_pld),
		.mst_rsp_vld(),
		.mst_rsp_rdy(),
		.mst_rsp_pld(),
		.slv_req_vld(),
		.slv_req_rdy(),
		.slv_req_pld(),
		.slv_rsp_vld(),
		.slv_rsp_rdy(),
		.slv_rsp_pld(),
		.mst_cti_channel_in(),
		.mst_cti_channel_out(),
		.slv_cti_channel_in(),
		.slv_cti_channel_out(),
		.mst_cti_event_in(),
		.mst_cti_event_out(),
		.slv_cti_event_in(),
		.slv_cti_event_out(),
		.mst_dbg_timestamp(),
		.slv_dbg_timestamp(),
		.slv_dbg_data(),
		.mst_dbg_data());
	sts_noc_dec_node dec2_ext (
		.clk(clk_harden_up_func),
		.rst_n(rst_harden_up_func_n),
		.mst_req_vld(),
		.mst_req_rdy(),
		.mst_req_pld(),
		.mst_rsp_vld(),
		.mst_rsp_rdy(),
		.mst_rsp_pld(),
		.slv_req_vld(),
		.slv_req_rdy(),
		.slv_req_pld(),
		.slv_rsp_vld(),
		.slv_rsp_rdy(),
		.slv_rsp_pld(),
		.mst_cti_channel_in(),
		.mst_cti_channel_out(),
		.slv_cti_channel_in(),
		.slv_cti_channel_out(),
		.mst_cti_event_in(),
		.mst_cti_event_out(),
		.slv_cti_event_in(),
		.slv_cti_event_out(),
		.mst_dbg_timestamp(),
		.slv_dbg_timestamp(),
		.slv_dbg_data(),
		.mst_dbg_data());
	sts_async_bridge_slv harden_dn_async_bridge_slv (
		.clk(clk_harden_dn_func),
		.rst_n(rst_harden_dn_func_n),
		.stall(),
		.clear(),
		.full_zero(),
		.in_req_vld(),
		.in_req_rdy(),
		.in_req_pld(),
		.almost_full(),
		.wptr_async(harden_dn_async_bridge_slv_TO_harden_up_async_bridge_mst_SIG_wptr_async),
		.rptr_async(harden_up_async_bridge_mst_TO_harden_dn_async_bridge_slv_SIG_rptr_async),
		.rptr_sync(harden_up_async_bridge_mst_TO_harden_dn_async_bridge_slv_SIG_rptr_sync),
		.pld_sync(harden_dn_async_bridge_slv_TO_harden_up_async_bridge_mst_SIG_pld_sync));
	sts_async_bridge_mst harden_up_async_bridge_mst (
		.clk(clk_harden_up_func),
		.rst_n(rst_harden_up_func_n),
		.stall(),
		.clear(),
		.full_zero(),
		.idle(),
		.out_rsp_vld(harden_up_async_bridge_mst_TO_dec2_SIG_out_rsp_vld),
		.out_rsp_pld(harden_up_async_bridge_mst_TO_dec2_SIG_out_rsp_pld),
		.out_rsp_rdy(dec2_TO_harden_up_async_bridge_mst_SIG_mst_req_rdy),
		.almost_empty(),
		.wptr_async(harden_dn_async_bridge_slv_TO_harden_up_async_bridge_mst_SIG_wptr_async),
		.rptr_async(harden_up_async_bridge_mst_TO_harden_dn_async_bridge_slv_SIG_rptr_async),
		.rptr_sync(harden_up_async_bridge_mst_TO_harden_dn_async_bridge_slv_SIG_rptr_sync),
		.pld_sync(harden_dn_async_bridge_slv_TO_harden_up_async_bridge_mst_SIG_pld_sync));
	vpu_ss_tniu vpu_ss_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_dn_func),
		.rstn_dst_rstn_dst(rst_harden_dn_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(vpu_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(vpu_ss_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(vpu_ss_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(vpu_ss_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(vpu_ss_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(vpu_ss_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(vpu_ss_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(vpu_ss_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(vpu_ss_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(vpu_ss_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(vpu_ss_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(vpu_ss_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(vpu_ss_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(vpu_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(vpu_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(vpu_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(vpu_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(vpu_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(vpu_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(vpu_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(vpu_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(vpu_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(vpu_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	camera_ss_tniu camera_ss_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_dn_func),
		.rstn_dst_rstn_dst(rst_harden_dn_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(camera_ss_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(camera_ss_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(camera_ss_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(camera_ss_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(camera_ss_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(camera_ss_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(camera_ss_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(camera_ss_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(camera_ss_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(camera_ss_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(camera_ss_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(camera_ss_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(camera_ss_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(camera_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(camera_ss_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(camera_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(camera_ss_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(camera_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(camera_ss_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(camera_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(camera_ss_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(camera_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(camera_ss_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	dspss0_tniu dspss0_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_up_func),
		.rstn_dst_rstn_dst(rst_harden_up_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(dspss0_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(dspss0_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(dspss0_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(dspss0_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(dspss0_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(dspss0_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(dspss0_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(dspss0_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(dspss0_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(dspss0_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(dspss0_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(dspss0_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(dspss0_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(dspss0_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(dspss0_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(dspss0_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(dspss0_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(dspss0_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(dspss0_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(dspss0_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(dspss0_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(dspss0_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(dspss0_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	dspss1_tniu dspss1_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_up_func),
		.rstn_dst_rstn_dst(rst_harden_up_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(dspss1_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(dspss1_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(dspss1_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(dspss1_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(dspss1_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(dspss1_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(dspss1_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(dspss1_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(dspss1_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(dspss1_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(dspss1_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(dspss1_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(dspss1_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(dspss1_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(dspss1_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(dspss1_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(dspss1_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(dspss1_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(dspss1_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(dspss1_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(dspss1_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(dspss1_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(dspss1_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	dspss2_tniu dspss2_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_up_func),
		.rstn_dst_rstn_dst(rst_harden_up_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(dspss2_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(dspss2_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(dspss2_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(dspss2_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(dspss2_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(dspss2_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(dspss2_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(dspss2_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(dspss2_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(dspss2_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(dspss2_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(dspss2_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(dspss2_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(dspss2_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(dspss2_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(dspss2_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(dspss2_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(dspss2_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(dspss2_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(dspss2_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(dspss2_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(dspss2_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(dspss2_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	dspss3_tniu dspss3_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_up_func),
		.rstn_dst_rstn_dst(rst_harden_up_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(dspss3_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(dspss3_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(dspss3_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(dspss3_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(dspss3_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(dspss3_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(dspss3_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(dspss3_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(dspss3_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(dspss3_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(dspss3_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(dspss3_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(dspss3_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(dspss3_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(dspss3_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(dspss3_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(dspss3_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(dspss3_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(dspss3_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(dspss3_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(dspss3_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(dspss3_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(dspss3_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	dspss4_tniu dspss4_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_up_func),
		.rstn_dst_rstn_dst(rst_harden_up_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(dspss4_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(dspss4_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(dspss4_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(dspss4_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(dspss4_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(dspss4_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(dspss4_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(dspss4_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(dspss4_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(dspss4_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(dspss4_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(dspss4_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(dspss4_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(dspss4_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(dspss4_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(dspss4_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(dspss4_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(dspss4_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(dspss4_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(dspss4_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(dspss4_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(dspss4_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(dspss4_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));
	dspss5_tniu dspss5_tniu (
		.clk_src_clk_src(clk_sys),
		.rstn_src_rstn_src(rst_sys_n),
		.clk_dst_clk_dst(clk_harden_up_func),
		.rstn_dst_rstn_dst(rst_harden_up_func_n),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_dbg_timer(rst_dbg_timer_n),
		.req_in_req_pld(),
		.req_in_req_rdy(),
		.req_in_req_vld(),
		.rsp_out_rsp_pld(),
		.rsp_out_rsp_rdy(),
		.rsp_out_rsp_vld(),
		.pmc_apb_pmc_paddr(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_paddr),
		.pmc_apb_pmc_penable(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_penable),
		.pmc_apb_pmc_pprot(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pprot),
		.pmc_apb_pmc_prdata(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_prdata),
		.pmc_apb_pmc_pready(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pready),
		.pmc_apb_pmc_psel(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_psel),
		.pmc_apb_pmc_pslverr(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pslverr),
		.pmc_apb_pmc_pstrb(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pstrb),
		.pmc_apb_pmc_pwdata(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pwdata),
		.pmc_apb_pmc_pwrite(dspss5_tniu_pmc_apb_porting_pmc_apb_pmc_pwrite),
		.sys_apb_m_paddr(dspss5_tniu_sys_apb_porting_sys_apb_m_paddr),
		.sys_apb_m_penable(dspss5_tniu_sys_apb_porting_sys_apb_m_penable),
		.sys_apb_m_pprot(dspss5_tniu_sys_apb_porting_sys_apb_m_pprot),
		.sys_apb_m_prdata(dspss5_tniu_sys_apb_porting_sys_apb_m_prdata),
		.sys_apb_m_pready(dspss5_tniu_sys_apb_porting_sys_apb_m_pready),
		.sys_apb_m_psel(dspss5_tniu_sys_apb_porting_sys_apb_m_psel),
		.sys_apb_m_pslverr(dspss5_tniu_sys_apb_porting_sys_apb_m_pslverr),
		.sys_apb_m_pstrb(dspss5_tniu_sys_apb_porting_sys_apb_m_pstrb),
		.sys_apb_m_pwdata(dspss5_tniu_sys_apb_porting_sys_apb_m_pwdata),
		.sys_apb_m_pwrite(dspss5_tniu_sys_apb_porting_sys_apb_m_pwrite),
		.dbg_data_dbg_data_in(dspss5_tniu_dbg_data_porting_dbg_data_dbg_data_in),
		.dbg_data_dbg_data_out(dspss5_tniu_dbg_data_porting_dbg_data_dbg_data_out),
		.dbg_timestamp_dbg_timestamp_in(dspss5_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_dbg_timestamp_out(dspss5_tniu_dbg_timestamp_porting_dbg_timestamp_dbg_timestamp_out),
		.sys_cti_event_sys_cti_event_in(dspss5_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_in),
		.sys_cti_event_sys_cti_event_out(dspss5_tniu_sys_cti_event_porting_sys_cti_event_sys_cti_event_out),
		.noc_cti_event_noc_cti_event_in(dspss5_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_in),
		.noc_cti_event_noc_cti_event_out(dspss5_tniu_noc_cti_event_porting_noc_cti_event_noc_cti_event_out),
		.sys_cti_channel_sys_cti_channel_in(dspss5_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_in),
		.sys_cti_channel_sys_cti_channel_out(dspss5_tniu_sys_cti_channel_porting_sys_cti_channel_sys_cti_channel_out),
		.noc_cti_channel_noc_cti_channel_in(dspss5_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_in),
		.noc_cti_channel_noc_cti_channel_out(dspss5_tniu_noc_cti_channel_porting_noc_cti_channel_noc_cti_channel_out));

endmodule
//[UHDL]Content End [md5:96001bd15b758d3b60f2740daea15b5a]

