`define dti_iniu_top_dspss0_INIU_ROUTE_BASE 9
`define dti_iniu_top_dspss0_PAYLOAD_WIDTH 90
`define dti_iniu_top_dspss0_TBU_NUM 1
`define dti_iniu_top_dspss0_TID_WIDTH 6
`define dti_iniu_top_dspss0_TRANSACTION_MAX_NUM 8
