`define dti_iniu_top_npu_ss4_INIU_ROUTE_BASE 2
`define dti_iniu_top_npu_ss4_PAYLOAD_WIDTH 90
`define dti_iniu_top_npu_ss4_TBU_NUM 1
`define dti_iniu_top_npu_ss4_TID_WIDTH 6
`define dti_iniu_top_npu_ss4_TRANSACTION_MAX_NUM 8
