$DTI_INIU_TOP_NPU_SS4_DIR/dti_iniu_top_side_npu_ss4_macros_f49fed7ba2.sv
$DTI_INIU_TOP_NPU_SS4_DIR/dti_iniu_top_npu_ss4_dti_pr_iniu_define.sv
$DTI_INIU_TOP_NPU_SS4_DIR/dti_iniu_top_npu_ss4_dti_iniu_pack.sv
$DTI_INIU_TOP_NPU_SS4_DIR/dti_iniu_top_npu_ss4_dti_pr_iniu_async_top_side.sv
$DTI_INIU_TOP_NPU_SS4_DIR/dti_iniu_top_npu_ss4_dti_pr_iniu_undef.sv
