//[UHDL]Content Start [md5:a553f1197c6cf2ef208c140d9ec38812]
-f $INTR_RING_REQ_SINK_OUT_DIR/filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ring_sink_station.v
-f $INTR_RING_BUF_OUT_DIR/filelist.f
-f $INTR_INIU_TOP_OUT_DIR/intr_iniu_top_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/soc_intr_xbar_routing_lut_w8_c1.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_50_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr5_iniu_node_top_wrap.v
-f $SOC_INTR_DDR_INIU_SYS_OUT_DIR/ddr_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr5_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_49_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr4_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr4_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_48_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr3_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr3_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_47_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr2_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr2_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_46_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr1_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr1_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_45_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr0_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr0_iniu_node.v
-f $INTR_TNIU_TOP_OUT_DIR/intr_tniu_top_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_44_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss4_tniu_node_top_wrap.v
-f $SOC_INTR_NPU_SS_TNIU_SYS_OUT_DIR/npu_ss_tniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss4_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_43_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss4_iniu_node_top_wrap.v
-f $SOC_INTR_NPU_SS_INIU_SYS_OUT_DIR/npu_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss4_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_42_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/mcu_ss_tniu_node_top_wrap.v
-f $SOC_INTR_MCU_SS_TNIU_SYS_OUT_DIR/mcu_ss_tniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/mcu_ss_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_41_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/mcu_ss_iniu_node_top_wrap.v
-f $SOC_INTR_MCU_SS_INIU_SYS_OUT_DIR/mcu_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/mcu_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_40_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/pcie_eth_ss_iniu_node_top_wrap.v
-f $SOC_INTR_PCIE_ETH_SS_INIU_SYS_OUT_DIR/pcie_eth_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/pcie_eth_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_39_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ufs_ss_iniu_node_top_wrap.v
-f $SOC_INTR_UFS_SS_INIU_SYS_OUT_DIR/ufs_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ufs_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_38_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/camera_ss_iniu_node_top_wrap.v
-f $SOC_INTR_CAMERA_SS_INIU_SYS_OUT_DIR/camera_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/camera_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_37_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/gpu_ss0_iniu_node_top_wrap.v
-f $SOC_INTR_GPU_SS_INIU_SYS_OUT_DIR/gpu_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/gpu_ss0_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_36_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/peri_ss_iniu_node_top_wrap.v
-f $SOC_INTR_PERI_SS_INIU_SYS_OUT_DIR/peri_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/peri_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_35_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss3_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss3_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_34_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss3_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss3_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_33_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/noc_ss_iniu_node_top_wrap.v
-f $SOC_INTR_NOC_SS_INIU_SYS_OUT_DIR/noc_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/noc_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_32_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr11_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr11_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_31_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr10_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr10_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_30_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr9_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr9_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_29_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr8_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr8_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_28_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr7_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr7_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_27_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr6_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/ddr6_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_26_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss0_tniu_node_top_wrap.v
-f $SOC_INTR_DSP_SS_TNIU_SYS_OUT_DIR/dsp_ss_tniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss0_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_25_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss0_iniu_node_top_wrap.v
-f $SOC_INTR_DSP_SS_INIU_SYS_OUT_DIR/dsp_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss0_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_24_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss1_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss1_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_23_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss1_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss1_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_22_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss2_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss2_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_21_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss2_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss2_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_20_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss3_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss3_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_19_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss3_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss3_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_18_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss4_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss4_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_17_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss4_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss4_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_16_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss5_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss5_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_15_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss5_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dsp_ss5_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_14_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/aon_ss_tniu_node_top_wrap.v
-f $SOC_INTR_AON_SS_TNIU_SYS_OUT_DIR/aon_ss_tniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/aon_ss_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_13_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/aon_ss_iniu_node_top_wrap.v
-f $SOC_INTR_AON_SS_INIU_SYS_OUT_DIR/aon_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/aon_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_12_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/vpu_ss_iniu_node_top_wrap.v
-f $SOC_INTR_VPU_SS_INIU_SYS_OUT_DIR/vpu_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/vpu_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_11_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/display_ss_iniu_node_top_wrap.v
-f $SOC_INTR_DISPLAY_SS_INIU_SYS_OUT_DIR/display_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/display_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_10_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dp_ss_iniu_node_top_wrap.v
-f $SOC_INTR_DP_SS_INIU_SYS_OUT_DIR/dp_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/dp_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_9_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/mipi_ss_iniu_node_top_wrap.v
-f $SOC_INTR_MIPI_SS_INIU_SYS_OUT_DIR/mipi_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/mipi_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_8_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/gpu_ss1_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/gpu_ss1_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_7_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss2_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss2_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_6_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss2_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss2_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_5_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss1_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss1_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_4_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss1_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss1_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_3_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss0_tniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss0_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_2_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss0_iniu_node_top_wrap.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/npu_ss0_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_1_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/cpu_ss_tniu_node_top_wrap.v
-f $SOC_INTR_CPU_SS_TNIU_SYS_OUT_DIR/cpu_ss_tniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/cpu_ss_tniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/SocIntrNodeIdGen_node_id_value_0_node_id_width_8.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/cpu_ss_iniu_node_top_wrap.v
-f $SOC_INTR_CPU_SS_INIU_SYS_OUT_DIR/cpu_ss_iniu_filelist.f
$SOC_INTR_RING_NOC/soc_intr_ring_noc/cpu_ss_iniu_node.v
$SOC_INTR_RING_NOC/soc_intr_ring_noc/soc_intr_ring_noc.v
//[UHDL]Content End [md5:a553f1197c6cf2ef208c140d9ec38812]

