//[UHDL]Content Start [md5:da39a31644380dc3277104d91cbf861a]
module aon_ss_iniu (
	input          clk_src                                                     ,
	input          rstn_src                                                    ,
	input          clk_dst                                                     ,
	input          rstn_dst                                                    ,
	input  [7:0]   node_id_node_id                                             ,
	input  [31:0]  axi_sts_iniu_s_araddr                                       ,
	input  [1:0]   axi_sts_iniu_s_arburst                                      ,
	input  [3:0]   axi_sts_iniu_s_arcache                                      ,
	input  [7:0]   axi_sts_iniu_s_arid                                         ,
	input  [7:0]   axi_sts_iniu_s_arlen                                        ,
	input          axi_sts_iniu_s_arlock                                       ,
	input  [2:0]   axi_sts_iniu_s_arprot                                       ,
	input  [3:0]   axi_sts_iniu_s_arqos                                        ,
	output         axi_sts_iniu_s_arready                                      ,
	input  [2:0]   axi_sts_iniu_s_arsize                                       ,
	input  [7:0]   axi_sts_iniu_s_aruser                                       ,
	input          axi_sts_iniu_s_arvalid                                      ,
	input  [31:0]  axi_sts_iniu_s_awaddr                                       ,
	input  [1:0]   axi_sts_iniu_s_awburst                                      ,
	input  [3:0]   axi_sts_iniu_s_awcache                                      ,
	input  [7:0]   axi_sts_iniu_s_awid                                         ,
	input  [7:0]   axi_sts_iniu_s_awlen                                        ,
	input          axi_sts_iniu_s_awlock                                       ,
	input  [2:0]   axi_sts_iniu_s_awprot                                       ,
	input  [3:0]   axi_sts_iniu_s_awqos                                        ,
	output         axi_sts_iniu_s_awready                                      ,
	input  [2:0]   axi_sts_iniu_s_awsize                                       ,
	input  [7:0]   axi_sts_iniu_s_awuser                                       ,
	input          axi_sts_iniu_s_awvalid                                      ,
	output [7:0]   axi_sts_iniu_s_bid                                          ,
	input          axi_sts_iniu_s_bready                                       ,
	output [1:0]   axi_sts_iniu_s_bresp                                        ,
	output         axi_sts_iniu_s_bvalid                                       ,
	output [31:0]  axi_sts_iniu_s_rdata                                        ,
	output [7:0]   axi_sts_iniu_s_rid                                          ,
	output         axi_sts_iniu_s_rlast                                        ,
	input          axi_sts_iniu_s_rready                                       ,
	output [1:0]   axi_sts_iniu_s_rresp                                        ,
	output         axi_sts_iniu_s_rvalid                                       ,
	input  [31:0]  axi_sts_iniu_s_wdata                                        ,
	input          axi_sts_iniu_s_wlast                                        ,
	output         axi_sts_iniu_s_wready                                       ,
	input  [3:0]   axi_sts_iniu_s_wstrb                                        ,
	input          axi_sts_iniu_s_wvalid                                       ,
	output [118:0] req_out_req_pld                                             ,
	input          req_out_req_rdy                                             ,
	output         req_out_req_vld                                             ,
	input  [64:0]  rsp_in_rsp_pld                                              ,
	output         rsp_in_rsp_rdy                                              ,
	input          rsp_in_rsp_vld                                              ,
	input  [7:0]   cti_event_noc_cti_event_in                                  ,
	output [7:0]   cti_event_noc_cti_event_out                                 ,
	input  [7:0]   cti_event_sys_cti_event_in                                  ,
	output [7:0]   cti_event_sys_cti_event_out                                 ,
	input  [7:0]   cti_channel_noc_cti_channel_in                              ,
	output [7:0]   cti_channel_noc_cti_channel_out                             ,
	input  [7:0]   cti_channel_sys_cti_channel_in                              ,
	output [7:0]   cti_channel_sys_cti_channel_out                             ,
	input  [63:0]  dbg_timestamp_dbg_timestamp_in                              ,
	output [63:0]  dbg_timestamp_dbg_timestamp_out                             ,
	input  [31:0]  dbg_data_dbg_data_in                                        ,
	output [31:0]  dbg_data_dbg_data_out                                       ,
	input  [7:0]   aon_ss_iniu_sys_side_node_id_porting_node_id                ,
	input  [31:0]  aon_ss_iniu_sys_side_axi_porting_s_araddr                   ,
	input  [1:0]   aon_ss_iniu_sys_side_axi_porting_s_arburst                  ,
	input  [3:0]   aon_ss_iniu_sys_side_axi_porting_s_arcache                  ,
	input  [7:0]   aon_ss_iniu_sys_side_axi_porting_s_arid                     ,
	input  [7:0]   aon_ss_iniu_sys_side_axi_porting_s_arlen                    ,
	input          aon_ss_iniu_sys_side_axi_porting_s_arlock                   ,
	input  [2:0]   aon_ss_iniu_sys_side_axi_porting_s_arprot                   ,
	input  [3:0]   aon_ss_iniu_sys_side_axi_porting_s_arqos                    ,
	output         aon_ss_iniu_sys_side_axi_porting_s_arready                  ,
	input  [2:0]   aon_ss_iniu_sys_side_axi_porting_s_arsize                   ,
	input  [7:0]   aon_ss_iniu_sys_side_axi_porting_s_aruser                   ,
	input          aon_ss_iniu_sys_side_axi_porting_s_arvalid                  ,
	input  [31:0]  aon_ss_iniu_sys_side_axi_porting_s_awaddr                   ,
	input  [1:0]   aon_ss_iniu_sys_side_axi_porting_s_awburst                  ,
	input  [3:0]   aon_ss_iniu_sys_side_axi_porting_s_awcache                  ,
	input  [7:0]   aon_ss_iniu_sys_side_axi_porting_s_awid                     ,
	input  [7:0]   aon_ss_iniu_sys_side_axi_porting_s_awlen                    ,
	input          aon_ss_iniu_sys_side_axi_porting_s_awlock                   ,
	input  [2:0]   aon_ss_iniu_sys_side_axi_porting_s_awprot                   ,
	input  [3:0]   aon_ss_iniu_sys_side_axi_porting_s_awqos                    ,
	output         aon_ss_iniu_sys_side_axi_porting_s_awready                  ,
	input  [2:0]   aon_ss_iniu_sys_side_axi_porting_s_awsize                   ,
	input  [7:0]   aon_ss_iniu_sys_side_axi_porting_s_awuser                   ,
	input          aon_ss_iniu_sys_side_axi_porting_s_awvalid                  ,
	output [7:0]   aon_ss_iniu_sys_side_axi_porting_s_bid                      ,
	input          aon_ss_iniu_sys_side_axi_porting_s_bready                   ,
	output [1:0]   aon_ss_iniu_sys_side_axi_porting_s_bresp                    ,
	output         aon_ss_iniu_sys_side_axi_porting_s_bvalid                   ,
	output [31:0]  aon_ss_iniu_sys_side_axi_porting_s_rdata                    ,
	output [7:0]   aon_ss_iniu_sys_side_axi_porting_s_rid                      ,
	output         aon_ss_iniu_sys_side_axi_porting_s_rlast                    ,
	input          aon_ss_iniu_sys_side_axi_porting_s_rready                   ,
	output [1:0]   aon_ss_iniu_sys_side_axi_porting_s_rresp                    ,
	output         aon_ss_iniu_sys_side_axi_porting_s_rvalid                   ,
	input  [31:0]  aon_ss_iniu_sys_side_axi_porting_s_wdata                    ,
	input          aon_ss_iniu_sys_side_axi_porting_s_wlast                    ,
	output         aon_ss_iniu_sys_side_axi_porting_s_wready                   ,
	input  [3:0]   aon_ss_iniu_sys_side_axi_porting_s_wstrb                    ,
	input          aon_ss_iniu_sys_side_axi_porting_s_wvalid                   ,
	output [120:0] aon_ss_iniu_sys_side_req_async_porting_req_pld_sync         ,
	input  [3:0]   aon_ss_iniu_sys_side_req_async_porting_req_rptr_async       ,
	input  [3:0]   aon_ss_iniu_sys_side_req_async_porting_req_rptr_sync        ,
	output [3:0]   aon_ss_iniu_sys_side_req_async_porting_req_wptr_async       ,
	input  [66:0]  aon_ss_iniu_sys_side_rsp_async_porting_rsp_pld_sync         ,
	output [3:0]   aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_async       ,
	output [3:0]   aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_sync        ,
	input  [3:0]   aon_ss_iniu_sys_side_rsp_async_porting_rsp_wptr_async       ,
	input  [7:0]   aon_ss_iniu_sys_side_cti_event_porting_cti_event_in         ,
	input  [7:0]   aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_ack     ,
	output [7:0]   aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_req     ,
	output [7:0]   aon_ss_iniu_sys_side_cti_event_porting_cti_event_out        ,
	output [7:0]   aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_ack    ,
	input  [7:0]   aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_req    ,
	input  [7:0]   aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in     ,
	input  [7:0]   aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_ack ,
	output [7:0]   aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_req ,
	output [7:0]   aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out    ,
	output [7:0]   aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_ack,
	input  [7:0]   aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_req,
	input  [63:0]  aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_in ,
	output [63:0]  aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_out,
	input  [31:0]  aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_in           ,
	output [31:0]  aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_out          );

	//Wire define for this module.

	//Wire define for sub module.

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	sts_iniu_sys iniu_sys_side (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.node_id(aon_ss_iniu_sys_side_node_id_porting_node_id),
		.s_awvalid(aon_ss_iniu_sys_side_axi_porting_s_awvalid),
		.s_awready(aon_ss_iniu_sys_side_axi_porting_s_awready),
		.s_awid(aon_ss_iniu_sys_side_axi_porting_s_awid),
		.s_awaddr(aon_ss_iniu_sys_side_axi_porting_s_awaddr),
		.s_awlen(aon_ss_iniu_sys_side_axi_porting_s_awlen),
		.s_awsize(aon_ss_iniu_sys_side_axi_porting_s_awsize),
		.s_awburst(aon_ss_iniu_sys_side_axi_porting_s_awburst),
		.s_awlock(aon_ss_iniu_sys_side_axi_porting_s_awlock),
		.s_awcache(aon_ss_iniu_sys_side_axi_porting_s_awcache),
		.s_awprot(aon_ss_iniu_sys_side_axi_porting_s_awprot),
		.s_awqos(aon_ss_iniu_sys_side_axi_porting_s_awqos),
		.s_awuser(aon_ss_iniu_sys_side_axi_porting_s_awuser),
		.s_wvalid(aon_ss_iniu_sys_side_axi_porting_s_wvalid),
		.s_wready(aon_ss_iniu_sys_side_axi_porting_s_wready),
		.s_wdata(aon_ss_iniu_sys_side_axi_porting_s_wdata),
		.s_wstrb(aon_ss_iniu_sys_side_axi_porting_s_wstrb),
		.s_wlast(aon_ss_iniu_sys_side_axi_porting_s_wlast),
		.s_bvalid(aon_ss_iniu_sys_side_axi_porting_s_bvalid),
		.s_bready(aon_ss_iniu_sys_side_axi_porting_s_bready),
		.s_bid(aon_ss_iniu_sys_side_axi_porting_s_bid),
		.s_bresp(aon_ss_iniu_sys_side_axi_porting_s_bresp),
		.s_arvalid(aon_ss_iniu_sys_side_axi_porting_s_arvalid),
		.s_arready(aon_ss_iniu_sys_side_axi_porting_s_arready),
		.s_arid(aon_ss_iniu_sys_side_axi_porting_s_arid),
		.s_araddr(aon_ss_iniu_sys_side_axi_porting_s_araddr),
		.s_arlen(aon_ss_iniu_sys_side_axi_porting_s_arlen),
		.s_arsize(aon_ss_iniu_sys_side_axi_porting_s_arsize),
		.s_arburst(aon_ss_iniu_sys_side_axi_porting_s_arburst),
		.s_arlock(aon_ss_iniu_sys_side_axi_porting_s_arlock),
		.s_arcache(aon_ss_iniu_sys_side_axi_porting_s_arcache),
		.s_arprot(aon_ss_iniu_sys_side_axi_porting_s_arprot),
		.s_arqos(aon_ss_iniu_sys_side_axi_porting_s_arqos),
		.s_aruser(aon_ss_iniu_sys_side_axi_porting_s_aruser),
		.s_rvalid(aon_ss_iniu_sys_side_axi_porting_s_rvalid),
		.s_rready(aon_ss_iniu_sys_side_axi_porting_s_rready),
		.s_rid(aon_ss_iniu_sys_side_axi_porting_s_rid),
		.s_rdata(aon_ss_iniu_sys_side_axi_porting_s_rdata),
		.s_rresp(aon_ss_iniu_sys_side_axi_porting_s_rresp),
		.s_rlast(aon_ss_iniu_sys_side_axi_porting_s_rlast),
		.req_wptr_async(aon_ss_iniu_sys_side_req_async_porting_req_wptr_async),
		.req_rptr_async(aon_ss_iniu_sys_side_req_async_porting_req_rptr_async),
		.req_rptr_sync(aon_ss_iniu_sys_side_req_async_porting_req_rptr_sync),
		.req_pld_sync(aon_ss_iniu_sys_side_req_async_porting_req_pld_sync),
		.rsp_wptr_async(aon_ss_iniu_sys_side_rsp_async_porting_rsp_wptr_async),
		.rsp_rptr_async(aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_async),
		.rsp_rptr_sync(aon_ss_iniu_sys_side_rsp_async_porting_rsp_rptr_sync),
		.rsp_pld_sync(aon_ss_iniu_sys_side_rsp_async_porting_rsp_pld_sync),
		.cti_event_in(aon_ss_iniu_sys_side_cti_event_porting_cti_event_in),
		.cti_event_in_req(aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_req),
		.cti_event_in_ack(aon_ss_iniu_sys_side_cti_event_porting_cti_event_in_ack),
		.cti_event_out(aon_ss_iniu_sys_side_cti_event_porting_cti_event_out),
		.cti_event_out_req(aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_req),
		.cti_event_out_ack(aon_ss_iniu_sys_side_cti_event_porting_cti_event_out_ack),
		.cti_channel_in(aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in),
		.cti_channel_in_req(aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_req),
		.cti_channel_in_ack(aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_in_ack),
		.cti_channel_out(aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out),
		.cti_channel_out_req(aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_req),
		.cti_channel_out_ack(aon_ss_iniu_sys_side_cti_channel_porting_cti_channel_out_ack),
		.dbg_timestamp_in(aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(aon_ss_iniu_sys_side_dbg_timestamp_porting_dbg_timestamp_out),
		.dbg_data_in(aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_in),
		.dbg_data_out(aon_ss_iniu_sys_side_dbg_data_porting_dbg_data_out));
	sts_iniu_top iniu_top_side (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.node_id(node_id_node_id),
		.sts_iniu_s_awvalid(axi_sts_iniu_s_awvalid),
		.sts_iniu_s_awready(axi_sts_iniu_s_awready),
		.sts_iniu_s_awid(axi_sts_iniu_s_awid),
		.sts_iniu_s_awaddr(axi_sts_iniu_s_awaddr),
		.sts_iniu_s_awlen(axi_sts_iniu_s_awlen),
		.sts_iniu_s_awsize(axi_sts_iniu_s_awsize),
		.sts_iniu_s_awburst(axi_sts_iniu_s_awburst),
		.sts_iniu_s_awlock(axi_sts_iniu_s_awlock),
		.sts_iniu_s_awcache(axi_sts_iniu_s_awcache),
		.sts_iniu_s_awprot(axi_sts_iniu_s_awprot),
		.sts_iniu_s_awqos(axi_sts_iniu_s_awqos),
		.sts_iniu_s_awuser(axi_sts_iniu_s_awuser),
		.sts_iniu_s_wvalid(axi_sts_iniu_s_wvalid),
		.sts_iniu_s_wready(axi_sts_iniu_s_wready),
		.sts_iniu_s_wdata(axi_sts_iniu_s_wdata),
		.sts_iniu_s_wstrb(axi_sts_iniu_s_wstrb),
		.sts_iniu_s_wlast(axi_sts_iniu_s_wlast),
		.sts_iniu_s_bvalid(axi_sts_iniu_s_bvalid),
		.sts_iniu_s_bready(axi_sts_iniu_s_bready),
		.sts_iniu_s_bid(axi_sts_iniu_s_bid),
		.sts_iniu_s_bresp(axi_sts_iniu_s_bresp),
		.sts_iniu_s_arvalid(axi_sts_iniu_s_arvalid),
		.sts_iniu_s_arready(axi_sts_iniu_s_arready),
		.sts_iniu_s_arid(axi_sts_iniu_s_arid),
		.sts_iniu_s_araddr(axi_sts_iniu_s_araddr),
		.sts_iniu_s_arlen(axi_sts_iniu_s_arlen),
		.sts_iniu_s_arsize(axi_sts_iniu_s_arsize),
		.sts_iniu_s_arburst(axi_sts_iniu_s_arburst),
		.sts_iniu_s_arlock(axi_sts_iniu_s_arlock),
		.sts_iniu_s_arcache(axi_sts_iniu_s_arcache),
		.sts_iniu_s_arprot(axi_sts_iniu_s_arprot),
		.sts_iniu_s_arqos(axi_sts_iniu_s_arqos),
		.sts_iniu_s_aruser(axi_sts_iniu_s_aruser),
		.sts_iniu_s_rvalid(axi_sts_iniu_s_rvalid),
		.sts_iniu_s_rready(axi_sts_iniu_s_rready),
		.sts_iniu_s_rid(axi_sts_iniu_s_rid),
		.sts_iniu_s_rdata(axi_sts_iniu_s_rdata),
		.sts_iniu_s_rresp(axi_sts_iniu_s_rresp),
		.sts_iniu_s_rlast(axi_sts_iniu_s_rlast),
		.out_req_vld(req_out_req_vld),
		.out_req_rdy(req_out_req_rdy),
		.out_req_pld(req_out_req_pld),
		.in_rsp_vld(rsp_in_rsp_vld),
		.in_rsp_rdy(rsp_in_rsp_rdy),
		.in_rsp_pld(rsp_in_rsp_pld),
		.sys_cti_event_in(cti_event_sys_cti_event_in),
		.sys_cti_event_out(cti_event_sys_cti_event_out),
		.noc_cti_event_out(cti_event_noc_cti_event_out),
		.noc_cti_event_in(cti_event_noc_cti_event_in),
		.sys_cti_channel_in(cti_channel_sys_cti_channel_in),
		.sys_cti_channel_out(cti_channel_sys_cti_channel_out),
		.noc_cti_channel_out(cti_channel_noc_cti_channel_out),
		.noc_cti_channel_in(cti_channel_noc_cti_channel_in),
		.dbg_timestamp_in(dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_out(dbg_timestamp_dbg_timestamp_out),
		.dbg_data_in(dbg_data_dbg_data_in),
		.dbg_data_out(dbg_data_dbg_data_out));

endmodule
//[UHDL]Content End [md5:da39a31644380dc3277104d91cbf861a]

