//[UHDL]Content Start [md5:4a22dfdd981560122e80b601d31f6a8f]
module aon_ss_iniu (
	input          clk_src                                ,
	input          rstn_src                               ,
	input          clk_dst                                ,
	input          rstn_dst                               ,
	output [120:0] top_req_req_s_pld                      ,
	input          top_req_req_s_rdy                      ,
	output         top_req_req_s_vld                      ,
	input  [66:0]  top_rsp_rsp_m_pld                      ,
	output         top_rsp_rsp_m_rdy                      ,
	input          top_rsp_rsp_m_vld                      ,
	input  [8:0]   node_id_node_id                        ,
	input          axi_awvalid_s_awvalid                  ,
	output         axi_awready_s_awready                  ,
	input  [7:0]   axi_awid_s_awid                        ,
	input  [31:0]  axi_awaddr_s_awaddr                    ,
	input  [7:0]   axi_awlen_s_awlen                      ,
	input  [2:0]   axi_awsize_s_awsize                    ,
	input  [1:0]   axi_awburst_s_awburst                  ,
	input          axi_awlock_s_awlock                    ,
	input  [3:0]   axi_awcache_s_awcache                  ,
	input  [2:0]   axi_awprot_s_awprot                    ,
	input  [3:0]   axi_awqos_s_awqos                      ,
	input  [7:0]   axi_awuser_s_awuser                    ,
	input          axi_wvalid_s_wvalid                    ,
	output         axi_wready_s_wready                    ,
	input  [31:0]  axi_wdata_s_wdata                      ,
	input  [3:0]   axi_wstrb_s_wstrb                      ,
	input          axi_wlast_s_wlast                      ,
	output         axi_bvalid_s_bvalid                    ,
	input          axi_bready_s_bready                    ,
	output [7:0]   axi_bid_s_bid                          ,
	output [1:0]   axi_bresp_s_bresp                      ,
	input          axi_arvalid_s_arvalid                  ,
	output         axi_arready_s_arready                  ,
	input  [7:0]   axi_arid_s_arid                        ,
	input  [31:0]  axi_araddr_s_araddr                    ,
	input  [7:0]   axi_arlen_s_arlen                      ,
	input  [2:0]   axi_arsize_s_arsize                    ,
	input  [1:0]   axi_arburst_s_arburst                  ,
	input          axi_arlock_s_arlock                    ,
	input  [3:0]   axi_arcache_s_arcache                  ,
	input  [2:0]   axi_arprot_s_arprot                    ,
	input  [3:0]   axi_arqos_s_arqos                      ,
	input  [7:0]   axi_aruser_s_aruser                    ,
	output         axi_rvalid_s_rvalid                    ,
	input          axi_rready_s_rready                    ,
	output [7:0]   axi_rid_s_rid                          ,
	output [31:0]  axi_rdata_s_rdata                      ,
	output [1:0]   axi_rresp_s_rresp                      ,
	output         axi_rlast_s_rlast                      ,
	input  [47:0]  noc_cti_channel_in_ctm_channel_in      ,
	output [47:0]  noc_cti_channel_out_ctm_channel_out    ,
	input  [63:0]  dbg_timestamp_dbg_timestamp_in         ,
	output [63:0]  dbg_timestamp_dbg_timestamp_out        ,
	input  [31:0]  dbg_data_dbg_data_in                   ,
	output [31:0]  dbg_data_dbg_data_out                  ,
	input  [63:0]  noc_dbg_timestamp_in_dbg_timestamp_in  ,
	output [63:0]  noc_dbg_timestamp_out_dbg_timestamp_out,
	input  [31:0]  noc_dbg_data_in_dbg_data_in            ,
	output [31:0]  noc_dbg_data_out_dbg_data_out          ,
	output         safety_safety_addr_map_rd_err          ,
	output         safety_safety_addr_map_wr_err          ,
	output         safety_safety_afifo_req_ecc_err        ,
	output         safety_safety_afifo_rsp_db_err         ,
	output         safety_safety_afifo_rsp_ecc_err        ,
	output         safety_safety_afifo_rsp_sb_err         ,
	output         safety_safety_ar_timeout_err           ,
	output         safety_safety_arb_lockstep_err         ,
	output         safety_safety_aw_timeout_err           ,
	output         safety_safety_w_timeout_err            );

	//Wire define for this module.

	//Wire define for sub module.
	wire [15:0]  noc_side_TO_sys_side_SIG_req_rptr_async;
	wire [15:0]  noc_side_TO_sys_side_SIG_req_rptr_sync ;
	wire [15:0]  noc_side_TO_sys_side_SIG_rsp_wptr_async;
	wire [75:0]  noc_side_TO_sys_side_SIG_rsp_pld_sync  ;
	wire [15:0]  sys_side_TO_noc_side_SIG_req_wptr_async;
	wire [130:0] sys_side_TO_noc_side_SIG_req_pld_sync  ;
	wire [15:0]  sys_side_TO_noc_side_SIG_rsp_rptr_async;
	wire [15:0]  sys_side_TO_noc_side_SIG_rsp_rptr_sync ;

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	aon_ss_iniu_sts_iniu_sys sys_side (
		.clk_src(clk_src),
		.rstn_src(rstn_src),
		.node_id(node_id_node_id),
		.s_awvalid(axi_awvalid_s_awvalid),
		.s_awready(axi_awready_s_awready),
		.s_awid(axi_awid_s_awid),
		.s_awaddr(axi_awaddr_s_awaddr),
		.s_awlen(axi_awlen_s_awlen),
		.s_awsize(axi_awsize_s_awsize),
		.s_awburst(axi_awburst_s_awburst),
		.s_awlock(axi_awlock_s_awlock),
		.s_awcache(axi_awcache_s_awcache),
		.s_awprot(axi_awprot_s_awprot),
		.s_awqos(axi_awqos_s_awqos),
		.s_awuser(axi_awuser_s_awuser),
		.s_wvalid(axi_wvalid_s_wvalid),
		.s_wready(axi_wready_s_wready),
		.s_wdata(axi_wdata_s_wdata),
		.s_wstrb(axi_wstrb_s_wstrb),
		.s_wlast(axi_wlast_s_wlast),
		.s_bvalid(axi_bvalid_s_bvalid),
		.s_bready(axi_bready_s_bready),
		.s_bid(axi_bid_s_bid),
		.s_bresp(axi_bresp_s_bresp),
		.s_arvalid(axi_arvalid_s_arvalid),
		.s_arready(axi_arready_s_arready),
		.s_arid(axi_arid_s_arid),
		.s_araddr(axi_araddr_s_araddr),
		.s_arlen(axi_arlen_s_arlen),
		.s_arsize(axi_arsize_s_arsize),
		.s_arburst(axi_arburst_s_arburst),
		.s_arlock(axi_arlock_s_arlock),
		.s_arcache(axi_arcache_s_arcache),
		.s_arprot(axi_arprot_s_arprot),
		.s_arqos(axi_arqos_s_arqos),
		.s_aruser(axi_aruser_s_aruser),
		.s_rvalid(axi_rvalid_s_rvalid),
		.s_rready(axi_rready_s_rready),
		.s_rid(axi_rid_s_rid),
		.s_rdata(axi_rdata_s_rdata),
		.s_rresp(axi_rresp_s_rresp),
		.s_rlast(axi_rlast_s_rlast),
		.req_wptr_async(sys_side_TO_noc_side_SIG_req_wptr_async),
		.req_rptr_async(noc_side_TO_sys_side_SIG_req_rptr_async),
		.req_rptr_sync(noc_side_TO_sys_side_SIG_req_rptr_sync),
		.req_pld_sync(sys_side_TO_noc_side_SIG_req_pld_sync),
		.rsp_wptr_async(noc_side_TO_sys_side_SIG_rsp_wptr_async),
		.rsp_rptr_async(sys_side_TO_noc_side_SIG_rsp_rptr_async),
		.rsp_rptr_sync(sys_side_TO_noc_side_SIG_rsp_rptr_sync),
		.rsp_pld_sync(noc_side_TO_sys_side_SIG_rsp_pld_sync),
		.sys_cti_trigin(),
		.sys_cti_trigin_ack(),
		.noc_cti_trigin(),
		.noc_cti_trigin_ack(),
		.noc_cti_trigout(),
		.noc_cti_trigout_ack(),
		.sys_cti_trigout(),
		.sys_cti_trigout_ack(),
		.sys_ctm_trigin(),
		.sys_ctm_trigin_ack(),
		.noc_ctm_trigin(),
		.noc_ctm_trigin_ack(),
		.noc_ctm_trigout(),
		.noc_ctm_trigout_ack(),
		.sys_ctm_trigout(),
		.sys_ctm_trigout_ack(),
		.dbg_timestamp_in(dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_out(dbg_timestamp_dbg_timestamp_out),
		.reserved_bits_in(),
		.reserved_bits_out(),
		.dbg_data_in(dbg_data_dbg_data_in),
		.dbg_data_out(dbg_data_dbg_data_out),
		.safety_arb_lockstep_err(safety_safety_arb_lockstep_err),
		.safety_addr_map_wr_err(safety_safety_addr_map_wr_err),
		.safety_addr_map_rd_err(safety_safety_addr_map_rd_err),
		.safety_afifo_rsp_ecc_err(safety_safety_afifo_rsp_ecc_err),
		.safety_afifo_req_ecc_err(safety_safety_afifo_req_ecc_err),
		.safety_ar_timeout_err(safety_safety_ar_timeout_err),
		.safety_w_timeout_err(safety_safety_w_timeout_err),
		.safety_aw_timeout_err(safety_safety_aw_timeout_err),
		.safety_afifo_rsp_sb_err(safety_safety_afifo_rsp_sb_err),
		.safety_afifo_rsp_db_err(safety_safety_afifo_rsp_db_err));
	aon_ss_iniu_sts_iniu_noc noc_side (
		.clk_dst(clk_dst),
		.rst_n_dst(rstn_dst),
		.req_wptr_async(sys_side_TO_noc_side_SIG_req_wptr_async),
		.req_rptr_async(noc_side_TO_sys_side_SIG_req_rptr_async),
		.req_rptr_sync(noc_side_TO_sys_side_SIG_req_rptr_sync),
		.req_pld_sync(sys_side_TO_noc_side_SIG_req_pld_sync),
		.rsp_wptr_async(noc_side_TO_sys_side_SIG_rsp_wptr_async),
		.rsp_rptr_async(sys_side_TO_noc_side_SIG_rsp_rptr_async),
		.rsp_rptr_sync(sys_side_TO_noc_side_SIG_rsp_rptr_sync),
		.rsp_pld_sync(noc_side_TO_sys_side_SIG_rsp_pld_sync),
		.req_s_vld(top_req_req_s_vld),
		.req_s_rdy(top_req_req_s_rdy),
		.req_s_pld(top_req_req_s_pld),
		.rsp_m_vld(top_rsp_rsp_m_vld),
		.rsp_m_rdy(top_rsp_rsp_m_rdy),
		.rsp_m_pld(top_rsp_rsp_m_pld),
		.dbg_data_in(noc_dbg_data_in_dbg_data_in),
		.dbg_data_out(noc_dbg_data_out_dbg_data_out),
		.sys_side_cti_trigin(),
		.sys_side_cti_trigin_ack(),
		.sys_side_cti_trigout(),
		.sys_side_cti_trigout_ack(),
		.ctm_channel_in(noc_cti_channel_in_ctm_channel_in),
		.ctm_channel_out(noc_cti_channel_out_ctm_channel_out),
		.sys_side_ctm_trigin(),
		.sys_side_ctm_trigin_ack(),
		.sys_side_ctm_trigout(),
		.sys_side_ctm_trigout_ack(),
		.cti_apb_psel(),
		.cti_apb_penable(),
		.cti_apb_paddr(),
		.cti_apb_pwrite(),
		.cti_apb_pwdata(),
		.cti_apb_prdata(),
		.cti_apb_pready(),
		.cti_apb_pslverr(),
		.dbg_timestamp_in(noc_dbg_timestamp_in_dbg_timestamp_in),
		.dbg_timestamp_out(noc_dbg_timestamp_out_dbg_timestamp_out),
		.reserved_bits_in(),
		.reserved_bits_out(),
		.req_afifo_sb_err(),
		.req_afifo_db_err());

endmodule
//[UHDL]Content End [md5:4a22dfdd981560122e80b601d31f6a8f]

