//[UHDL]Content Start [md5:5ae53219e8dfff6bc202dfbf9d5dc7a0]
module gpuss0_tniu (
	input          clk_src                                        ,
	input          rstn_src                                       ,
	input          clk_dst                                        ,
	input          rstn_dst                                       ,
	input          clk_dbg_timer                                  ,
	input          rstn_dbg_timer                                 ,
	input  [119:0] top_req_in_req_pld                             ,
	output         top_req_in_req_rdy                             ,
	input          top_req_in_req_vld                             ,
	output [65:0]  top_rsp_out_rsp_pld                            ,
	input          top_rsp_out_rsp_rdy                            ,
	output         top_rsp_out_rsp_vld                            ,
	output [31:0]  sys_apb_m_paddr                                ,
	output         sys_apb_m_penable                              ,
	output [2:0]   sys_apb_m_pprot                                ,
	input  [31:0]  sys_apb_m_prdata                               ,
	input          sys_apb_m_pready                               ,
	output         sys_apb_m_psel                                 ,
	input          sys_apb_m_pslverr                              ,
	output [3:0]   sys_apb_m_pstrb                                ,
	output [31:0]  sys_apb_m_pwdata                               ,
	output         sys_apb_m_pwrite                               ,
	input  [71:0]  noc_ctm_channel_in_ctm_channel_in              ,
	output [71:0]  noc_ctm_channel_out_ctm_channel_out            ,
	input  [31:0]  dbg_data_dbg_data_in                           ,
	output [31:0]  dbg_data_dbg_data_out                          ,
	input  [63:0]  dbg_timestamp_dbg_timestamp_in                 ,
	output [63:0]  dbg_timestamp_dbg_timestamp_out                ,
	input  [31:0]  noc_dbg_data_in_dbg_data_in                    ,
	output [31:0]  noc_dbg_data_out_dbg_data_out                  ,
	input  [63:0]  noc_dbg_timestamp_in_dbg_timestamp_in          ,
	output [63:0]  noc_dbg_timestamp_out_dbg_timestamp_out        ,
	output         safety_sts_tniu_req_afifo_db_err               ,
	output         safety_sts_tniu_req_afifo_sb_err               ,
	output [31:0]  apb_paddr                                      ,
	output         apb_penable                                    ,
	output [2:0]   apb_pprot                                      ,
	input  [31:0]  apb_prdata                                     ,
	input          apb_pready                                     ,
	output         apb_psel                                       ,
	input          apb_pslverr                                    ,
	output [3:0]   apb_pstrb                                      ,
	output [31:0]  apb_pwdata                                     ,
	output         apb_pwrite                                     ,
	output [31:0]  timing_bus1_timing_bus1                        ,
	output [31:0]  timing_bus2_timing_bus2                        ,
	output [31:0]  timing_bus3_timing_bus3                        ,
	output [31:0]  dbg_en_dbg_en                                  ,
	output         tniu_regbank_parity_err_tniu_regbank_parity_err,
	output         rsp_afifo_sb_err_rsp_afifo_sb_err              ,
	output         rsp_afifo_db_err_rsp_afifo_db_err              );

	//Wire define for this module.

	//Wire define for sub module.
	wire [3:0]   noc_side_TO_sys_side_SIG_req_wptr_async;
	wire [129:0] noc_side_TO_sys_side_SIG_req_pld_sync  ;
	wire [3:0]   noc_side_TO_sys_side_SIG_rsp_rptr_async;
	wire [3:0]   noc_side_TO_sys_side_SIG_rsp_rptr_sync ;
	wire [3:0]   sys_side_TO_noc_side_SIG_req_rptr_async;
	wire [3:0]   sys_side_TO_noc_side_SIG_req_rptr_sync ;
	wire [3:0]   sys_side_TO_noc_side_SIG_rsp_wptr_async;
	wire [75:0]  sys_side_TO_noc_side_SIG_rsp_pld_sync  ;

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	sts_tniu_sys sys_side (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.rstn_dbg_timer(rstn_dbg_timer),
		.req_wptr_async(noc_side_TO_sys_side_SIG_req_wptr_async),
		.req_rptr_async(sys_side_TO_noc_side_SIG_req_rptr_async),
		.req_rptr_sync(sys_side_TO_noc_side_SIG_req_rptr_sync),
		.req_pld_sync(noc_side_TO_sys_side_SIG_req_pld_sync),
		.rsp_wptr_async(sys_side_TO_noc_side_SIG_rsp_wptr_async),
		.rsp_rptr_async(noc_side_TO_sys_side_SIG_rsp_rptr_async),
		.rsp_rptr_sync(noc_side_TO_sys_side_SIG_rsp_rptr_sync),
		.rsp_pld_sync(sys_side_TO_noc_side_SIG_rsp_pld_sync),
		.m_psel(sys_apb_m_psel),
		.m_paddr(sys_apb_m_paddr),
		.m_pready(sys_apb_m_pready),
		.m_prdata(sys_apb_m_prdata),
		.m_pslverr(sys_apb_m_pslverr),
		.m_pprot(sys_apb_m_pprot),
		.m_penable(sys_apb_m_penable),
		.m_pwrite(sys_apb_m_pwrite),
		.m_pwdata(sys_apb_m_pwdata),
		.m_pstrb(sys_apb_m_pstrb),
		.v_tniu_sys_reg(),
		.sys_cti_trigin(),
		.sys_cti_trigin_ack(),
		.noc_cti_trigin(),
		.noc_cti_trigin_ack(),
		.noc_cti_trigout(),
		.noc_cti_trigout_ack(),
		.sys_cti_trigout(),
		.sys_cti_trigout_ack(),
		.sys_ctm_trigin(),
		.sys_ctm_trigin_ack(),
		.noc_ctm_trigin(),
		.noc_ctm_trigin_ack(),
		.noc_ctm_trigout(),
		.noc_ctm_trigout_ack(),
		.sys_ctm_trigout(),
		.sys_ctm_trigout_ack(),
		.dbg_data_in(dbg_data_dbg_data_in),
		.dbg_data_out(dbg_data_dbg_data_out),
		.dbg_timestamp_in(dbg_timestamp_dbg_timestamp_in),
		.dbg_timestamp_out(dbg_timestamp_dbg_timestamp_out),
		.tniu_sys_regbank_parity_err(),
		.sts_tniu_req_afifo_sb_err(safety_sts_tniu_req_afifo_sb_err),
		.sts_tniu_req_afifo_db_err(safety_sts_tniu_req_afifo_db_err));
	sts_tniu_noc noc_side (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.in_req_vld(top_req_in_req_vld),
		.in_req_rdy(top_req_in_req_rdy),
		.in_req_pld(top_req_in_req_pld),
		.out_rsp_vld(top_rsp_out_rsp_vld),
		.out_rsp_rdy(top_rsp_out_rsp_rdy),
		.out_rsp_pld(top_rsp_out_rsp_pld),
		.req_wptr_async(noc_side_TO_sys_side_SIG_req_wptr_async),
		.req_rptr_async(sys_side_TO_noc_side_SIG_req_rptr_async),
		.req_rptr_sync(sys_side_TO_noc_side_SIG_req_rptr_sync),
		.req_pld_sync(noc_side_TO_sys_side_SIG_req_pld_sync),
		.rsp_wptr_async(sys_side_TO_noc_side_SIG_rsp_wptr_async),
		.rsp_rptr_async(noc_side_TO_sys_side_SIG_rsp_rptr_async),
		.rsp_rptr_sync(noc_side_TO_sys_side_SIG_rsp_rptr_sync),
		.rsp_pld_sync(sys_side_TO_noc_side_SIG_rsp_pld_sync),
		.psel(apb_psel),
		.penable(apb_penable),
		.paddr(apb_paddr),
		.pwrite(apb_pwrite),
		.pwdata(apb_pwdata),
		.prdata(apb_prdata),
		.pready(apb_pready),
		.pstrb(apb_pstrb),
		.pprot(apb_pprot),
		.pslverr(apb_pslverr),
		.dbg_data_in(noc_dbg_data_in_dbg_data_in),
		.dbg_data_out(noc_dbg_data_out_dbg_data_out),
		.dbg_timestamp_in(noc_dbg_timestamp_in_dbg_timestamp_in),
		.dbg_timestamp_out(noc_dbg_timestamp_out_dbg_timestamp_out),
		.sys_side_cti_trigin(),
		.sys_side_cti_trigin_ack(),
		.sys_side_cti_trigout(),
		.sys_side_cti_trigout_ack(),
		.ctm_channel_in(noc_ctm_channel_in_ctm_channel_in),
		.ctm_channel_out(noc_ctm_channel_out_ctm_channel_out),
		.sys_side_ctm_trigin(),
		.sys_side_ctm_trigin_ack(),
		.sys_side_ctm_trigout(),
		.sys_side_ctm_trigout_ack(),
		.timing_bus1(timing_bus1_timing_bus1),
		.timing_bus2(timing_bus2_timing_bus2),
		.timing_bus3(timing_bus3_timing_bus3),
		.dbg_en(dbg_en_dbg_en),
		.tniu_regbank_parity_err(tniu_regbank_parity_err_tniu_regbank_parity_err),
		.rsp_afifo_sb_err(rsp_afifo_sb_err_rsp_afifo_sb_err),
		.rsp_afifo_db_err(rsp_afifo_db_err_rsp_afifo_db_err));

endmodule
//[UHDL]Content End [md5:5ae53219e8dfff6bc202dfbf9d5dc7a0]

