$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_sys_macros_dd2c524db5.sv
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_sts_tniu_define.sv
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_lwnoc_sts_pack.sv
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_RegSpaceBase_cfg_reg_bank_table_sys.v
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_sts_tniu_apb_dec.sv
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_sts_tniu_apb.sv
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_sts_tniu_sys.sv
$GPUSS1_TNIU_SYS_OUT_DIR/sts_noc_gpu_ss1_tniu_sts_tniu_undefine.sv
