$CAMERA_INIU_SYS_DIR/camera_dti_pr_iniu_define.sv
$CAMERA_INIU_SYS_DIR/camera_dti_iniu_pack.sv
$CAMERA_INIU_SYS_DIR/camera_dti_pr_rob_state_entry.sv
$CAMERA_INIU_SYS_DIR/camera_dti_pr.sv
$CAMERA_INIU_SYS_DIR/camera_dti_to_gnpd_conv.sv
$CAMERA_INIU_SYS_DIR/camera_dti_pr_iniu_async_sys_side.sv
