`define dti_sw_right4_DTI_INIU0_MAX 27
`define dti_sw_right4_DTI_INIU0_MIN 24
`define dti_sw_right4_DTI_INIU1_MAX 31
`define dti_sw_right4_DTI_INIU1_MIN 28
`define dti_sw_right4_DTI_INIU2_MAX 35
`define dti_sw_right4_DTI_INIU2_MIN 32
`define dti_sw_right4_DTI_INIU3_MAX 39
`define dti_sw_right4_DTI_INIU3_MIN 36
`define dti_sw_right4_DTI_TNIU_MAX 39
`define dti_sw_right4_DTI_TNIU_MIN 24
