$STS_LOGIC_TOPO_DIR/sts_demo_tniu0_sts_tniu_noc_dec2.sv
$STS_LOGIC_TOPO_DIR/sts_demo_tniu0_sts_tniu_noc.sv
$STS_LOGIC_TOPO_DIR/sts_demo_tniu0_sts_tniu_top.sv
$STS_LOGIC_TOPO_DIR/sts_demo_tniu0_sts_demo_tniu0_wrap.sv
