$STS_LOGIC_TOPO_DIR/sts_demo_tniu3_sts_tniu_noc_dec2.sv
$STS_LOGIC_TOPO_DIR/sts_demo_tniu3_sts_tniu_noc.sv
$STS_LOGIC_TOPO_DIR/sts_demo_tniu3_sts_tniu_top.sv
$STS_LOGIC_TOPO_DIR/sts_demo_tniu3_sts_demo_tniu3_wrap.sv
