$STS_LOGIC_TOPO_DIR/sts_demo_dec4_lwnoc_sts_pack.sv
$STS_LOGIC_TOPO_DIR/sts_demo_dec4_sts_iniu_addr_map.sv
$STS_LOGIC_TOPO_DIR/sts_demo_dec4_cti_handle.sv
$STS_LOGIC_TOPO_DIR/sts_demo_dec4_sts_noc_dec_node.sv
$STS_LOGIC_TOPO_DIR/sts_demo_dec4_sts_tniu_apb_dec.sv
$STS_LOGIC_TOPO_DIR/sts_demo_dec4_sts_demo_dec4_wrap.sv
