//[UHDL]Content Start [md5:ba5fc755d8a6e3ca9b7b52730557035a]
module sts_logic_topo_1i4t (
	input          clk_src                                          ,
	input          clk_dst                                          ,
	input          clk_dbg_timer                                    ,
	input          rstn_src                                         ,
	input          rstn_dst                                         ,
	input          rstn_dbg_timer                                   ,
	input  [7:0]   iniu0_node_id_porting_node_id                    ,
	input  [31:0]  iniu0_axi_porting_s_araddr                       ,
	input  [1:0]   iniu0_axi_porting_s_arburst                      ,
	input  [3:0]   iniu0_axi_porting_s_arcache                      ,
	input  [7:0]   iniu0_axi_porting_s_arid                         ,
	input  [7:0]   iniu0_axi_porting_s_arlen                        ,
	input          iniu0_axi_porting_s_arlock                       ,
	input  [2:0]   iniu0_axi_porting_s_arprot                       ,
	input  [3:0]   iniu0_axi_porting_s_arqos                        ,
	output         iniu0_axi_porting_s_arready                      ,
	input  [2:0]   iniu0_axi_porting_s_arsize                       ,
	input  [7:0]   iniu0_axi_porting_s_aruser                       ,
	input          iniu0_axi_porting_s_arvalid                      ,
	input  [31:0]  iniu0_axi_porting_s_awaddr                       ,
	input  [1:0]   iniu0_axi_porting_s_awburst                      ,
	input  [3:0]   iniu0_axi_porting_s_awcache                      ,
	input  [7:0]   iniu0_axi_porting_s_awid                         ,
	input  [7:0]   iniu0_axi_porting_s_awlen                        ,
	input          iniu0_axi_porting_s_awlock                       ,
	input  [2:0]   iniu0_axi_porting_s_awprot                       ,
	input  [3:0]   iniu0_axi_porting_s_awqos                        ,
	output         iniu0_axi_porting_s_awready                      ,
	input  [2:0]   iniu0_axi_porting_s_awsize                       ,
	input  [7:0]   iniu0_axi_porting_s_awuser                       ,
	input          iniu0_axi_porting_s_awvalid                      ,
	output [7:0]   iniu0_axi_porting_s_bid                          ,
	input          iniu0_axi_porting_s_bready                       ,
	output [1:0]   iniu0_axi_porting_s_bresp                        ,
	output         iniu0_axi_porting_s_bvalid                       ,
	output [31:0]  iniu0_axi_porting_s_rdata                        ,
	output [7:0]   iniu0_axi_porting_s_rid                          ,
	output         iniu0_axi_porting_s_rlast                        ,
	input          iniu0_axi_porting_s_rready                       ,
	output [1:0]   iniu0_axi_porting_s_rresp                        ,
	output         iniu0_axi_porting_s_rvalid                       ,
	input  [31:0]  iniu0_axi_porting_s_wdata                        ,
	input          iniu0_axi_porting_s_wlast                        ,
	output         iniu0_axi_porting_s_wready                       ,
	input  [3:0]   iniu0_axi_porting_s_wstrb                        ,
	input          iniu0_axi_porting_s_wvalid                       ,
	output [31:0]  tniu0_pmc_apb_porting_pmc_paddr                  ,
	output         tniu0_pmc_apb_porting_pmc_penable                ,
	output [2:0]   tniu0_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  tniu0_pmc_apb_porting_pmc_prdata                 ,
	input          tniu0_pmc_apb_porting_pmc_pready                 ,
	output         tniu0_pmc_apb_porting_pmc_psel                   ,
	input          tniu0_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   tniu0_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  tniu0_pmc_apb_porting_pmc_pwdata                 ,
	output         tniu0_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  tniu0_sys_apb_porting_m_paddr                    ,
	output         tniu0_sys_apb_porting_m_penable                  ,
	output [2:0]   tniu0_sys_apb_porting_m_pprot                    ,
	input  [319:0] tniu0_sys_apb_porting_m_prdata                   ,
	input  [9:0]   tniu0_sys_apb_porting_m_pready                   ,
	output [9:0]   tniu0_sys_apb_porting_m_psel                     ,
	input  [9:0]   tniu0_sys_apb_porting_m_pslverr                  ,
	output [3:0]   tniu0_sys_apb_porting_m_pstrb                    ,
	output [31:0]  tniu0_sys_apb_porting_m_pwdata                   ,
	output         tniu0_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  tniu0_dbg_data_porting_dbg_data_in               ,
	output [31:0]  tniu0_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  tniu0_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  tniu0_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   tniu0_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   tniu0_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   tniu0_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   tniu0_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   tniu0_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   tniu0_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   tniu0_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   tniu0_noc_cti_channel_porting_noc_cti_channel_out,
	output [31:0]  tniu1_pmc_apb_porting_pmc_paddr                  ,
	output         tniu1_pmc_apb_porting_pmc_penable                ,
	output [2:0]   tniu1_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  tniu1_pmc_apb_porting_pmc_prdata                 ,
	input          tniu1_pmc_apb_porting_pmc_pready                 ,
	output         tniu1_pmc_apb_porting_pmc_psel                   ,
	input          tniu1_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   tniu1_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  tniu1_pmc_apb_porting_pmc_pwdata                 ,
	output         tniu1_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  tniu1_sys_apb_porting_m_paddr                    ,
	output         tniu1_sys_apb_porting_m_penable                  ,
	output [2:0]   tniu1_sys_apb_porting_m_pprot                    ,
	input  [319:0] tniu1_sys_apb_porting_m_prdata                   ,
	input  [9:0]   tniu1_sys_apb_porting_m_pready                   ,
	output [9:0]   tniu1_sys_apb_porting_m_psel                     ,
	input  [9:0]   tniu1_sys_apb_porting_m_pslverr                  ,
	output [3:0]   tniu1_sys_apb_porting_m_pstrb                    ,
	output [31:0]  tniu1_sys_apb_porting_m_pwdata                   ,
	output         tniu1_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  tniu1_dbg_data_porting_dbg_data_in               ,
	output [31:0]  tniu1_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  tniu1_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  tniu1_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   tniu1_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   tniu1_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   tniu1_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   tniu1_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   tniu1_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   tniu1_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   tniu1_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   tniu1_noc_cti_channel_porting_noc_cti_channel_out,
	output [31:0]  tniu2_pmc_apb_porting_pmc_paddr                  ,
	output         tniu2_pmc_apb_porting_pmc_penable                ,
	output [2:0]   tniu2_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  tniu2_pmc_apb_porting_pmc_prdata                 ,
	input          tniu2_pmc_apb_porting_pmc_pready                 ,
	output         tniu2_pmc_apb_porting_pmc_psel                   ,
	input          tniu2_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   tniu2_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  tniu2_pmc_apb_porting_pmc_pwdata                 ,
	output         tniu2_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  tniu2_sys_apb_porting_m_paddr                    ,
	output         tniu2_sys_apb_porting_m_penable                  ,
	output [2:0]   tniu2_sys_apb_porting_m_pprot                    ,
	input  [319:0] tniu2_sys_apb_porting_m_prdata                   ,
	input  [9:0]   tniu2_sys_apb_porting_m_pready                   ,
	output [9:0]   tniu2_sys_apb_porting_m_psel                     ,
	input  [9:0]   tniu2_sys_apb_porting_m_pslverr                  ,
	output [3:0]   tniu2_sys_apb_porting_m_pstrb                    ,
	output [31:0]  tniu2_sys_apb_porting_m_pwdata                   ,
	output         tniu2_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  tniu2_dbg_data_porting_dbg_data_in               ,
	output [31:0]  tniu2_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  tniu2_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  tniu2_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   tniu2_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   tniu2_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   tniu2_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   tniu2_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   tniu2_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   tniu2_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   tniu2_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   tniu2_noc_cti_channel_porting_noc_cti_channel_out,
	output [31:0]  tniu3_pmc_apb_porting_pmc_paddr                  ,
	output         tniu3_pmc_apb_porting_pmc_penable                ,
	output [2:0]   tniu3_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  tniu3_pmc_apb_porting_pmc_prdata                 ,
	input          tniu3_pmc_apb_porting_pmc_pready                 ,
	output         tniu3_pmc_apb_porting_pmc_psel                   ,
	input          tniu3_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   tniu3_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  tniu3_pmc_apb_porting_pmc_pwdata                 ,
	output         tniu3_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  tniu3_sys_apb_porting_m_paddr                    ,
	output         tniu3_sys_apb_porting_m_penable                  ,
	output [2:0]   tniu3_sys_apb_porting_m_pprot                    ,
	input  [319:0] tniu3_sys_apb_porting_m_prdata                   ,
	input  [9:0]   tniu3_sys_apb_porting_m_pready                   ,
	output [9:0]   tniu3_sys_apb_porting_m_psel                     ,
	input  [9:0]   tniu3_sys_apb_porting_m_pslverr                  ,
	output [3:0]   tniu3_sys_apb_porting_m_pstrb                    ,
	output [31:0]  tniu3_sys_apb_porting_m_pwdata                   ,
	output         tniu3_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  tniu3_dbg_data_porting_dbg_data_in               ,
	output [31:0]  tniu3_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  tniu3_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  tniu3_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   tniu3_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   tniu3_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   tniu3_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   tniu3_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   tniu3_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   tniu3_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   tniu3_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   tniu3_noc_cti_channel_porting_noc_cti_channel_out);

	localparam integer unsigned STS_REQ_PLD_WIDTH = 119;
	localparam integer unsigned STS_RSP_PLD_WIDTH = 65;

	//Wire define for this module.

	//Wire define for sub module.
	wire  noc_dec_TO_iniu0_SIG_mst_req_rdy ;
	wire  noc_dec_TO_iniu0_SIG_mst_rsp_vld ;
	wire  [STS_RSP_PLD_WIDTH-1:0] noc_dec_TO_iniu0_SIG_mst_rsp_pld ;
	wire  iniu0_TO_noc_dec_SIG_out_req_vld ;
	wire  [STS_REQ_PLD_WIDTH-1:0] iniu0_TO_noc_dec_SIG_out_req_pld ;
	wire  iniu0_TO_noc_dec_SIG_in_rsp_rdy  ;
	wire  tniu0_TO_noc_dec_SIG_in_req_rdy  ;
	wire  tniu0_TO_noc_dec_SIG_out_rsp_vld ;
	wire  [STS_RSP_PLD_WIDTH-1:0] tniu0_TO_noc_dec_SIG_out_rsp_pld ;
	wire  tniu1_TO_noc_dec_SIG_in_req_rdy  ;
	wire  tniu1_TO_noc_dec_SIG_out_rsp_vld ;
	wire  [STS_RSP_PLD_WIDTH-1:0] tniu1_TO_noc_dec_SIG_out_rsp_pld ;
	wire  tniu2_TO_noc_dec_SIG_in_req_rdy  ;
	wire  tniu2_TO_noc_dec_SIG_out_rsp_vld ;
	wire  [STS_RSP_PLD_WIDTH-1:0] tniu2_TO_noc_dec_SIG_out_rsp_pld ;
	wire  tniu3_TO_noc_dec_SIG_in_req_rdy  ;
	wire  tniu3_TO_noc_dec_SIG_out_rsp_vld ;
	wire  [STS_RSP_PLD_WIDTH-1:0] tniu3_TO_noc_dec_SIG_out_rsp_pld ;
	wire  noc_dec_TO_tniu0_SIG_slv0_req_vld;
	wire  [STS_REQ_PLD_WIDTH-1:0] noc_dec_TO_tniu0_SIG_slv0_req_pld;
	wire  noc_dec_TO_tniu0_SIG_slv0_rsp_rdy;
	wire  noc_dec_TO_tniu1_SIG_slv1_req_vld;
	wire  [STS_REQ_PLD_WIDTH-1:0] noc_dec_TO_tniu1_SIG_slv1_req_pld;
	wire  noc_dec_TO_tniu1_SIG_slv1_rsp_rdy;
	wire  noc_dec_TO_tniu2_SIG_slv2_req_vld;
	wire  [STS_REQ_PLD_WIDTH-1:0] noc_dec_TO_tniu2_SIG_slv2_req_pld;
	wire  noc_dec_TO_tniu2_SIG_slv2_rsp_rdy;
	wire  noc_dec_TO_tniu3_SIG_slv3_req_vld;
	wire  [STS_REQ_PLD_WIDTH-1:0] noc_dec_TO_tniu3_SIG_slv3_req_pld;
	wire  noc_dec_TO_tniu3_SIG_slv3_rsp_rdy;

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	sts_demo_iniu_sts_demo_iniu_wrap iniu0 (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.node_id(iniu0_node_id_porting_node_id),
		.s_awvalid(iniu0_axi_porting_s_awvalid),
		.s_awready(iniu0_axi_porting_s_awready),
		.s_awid(iniu0_axi_porting_s_awid),
		.s_awaddr(iniu0_axi_porting_s_awaddr),
		.s_awlen(iniu0_axi_porting_s_awlen),
		.s_awsize(iniu0_axi_porting_s_awsize),
		.s_awburst(iniu0_axi_porting_s_awburst),
		.s_awlock(iniu0_axi_porting_s_awlock),
		.s_awcache(iniu0_axi_porting_s_awcache),
		.s_awprot(iniu0_axi_porting_s_awprot),
		.s_awqos(iniu0_axi_porting_s_awqos),
		.s_awuser(iniu0_axi_porting_s_awuser),
		.s_wvalid(iniu0_axi_porting_s_wvalid),
		.s_wready(iniu0_axi_porting_s_wready),
		.s_wdata(iniu0_axi_porting_s_wdata),
		.s_wstrb(iniu0_axi_porting_s_wstrb),
		.s_wlast(iniu0_axi_porting_s_wlast),
		.s_bvalid(iniu0_axi_porting_s_bvalid),
		.s_bready(iniu0_axi_porting_s_bready),
		.s_bid(iniu0_axi_porting_s_bid),
		.s_bresp(iniu0_axi_porting_s_bresp),
		.s_arvalid(iniu0_axi_porting_s_arvalid),
		.s_arready(iniu0_axi_porting_s_arready),
		.s_arid(iniu0_axi_porting_s_arid),
		.s_araddr(iniu0_axi_porting_s_araddr),
		.s_arlen(iniu0_axi_porting_s_arlen),
		.s_arsize(iniu0_axi_porting_s_arsize),
		.s_arburst(iniu0_axi_porting_s_arburst),
		.s_arlock(iniu0_axi_porting_s_arlock),
		.s_arcache(iniu0_axi_porting_s_arcache),
		.s_arprot(iniu0_axi_porting_s_arprot),
		.s_arqos(iniu0_axi_porting_s_arqos),
		.s_aruser(iniu0_axi_porting_s_aruser),
		.s_rvalid(iniu0_axi_porting_s_rvalid),
		.s_rready(iniu0_axi_porting_s_rready),
		.s_rid(iniu0_axi_porting_s_rid),
		.s_rdata(iniu0_axi_porting_s_rdata),
		.s_rresp(iniu0_axi_porting_s_rresp),
		.s_rlast(iniu0_axi_porting_s_rlast),
		.out_req_vld(iniu0_TO_noc_dec_SIG_out_req_vld),
		.out_req_rdy(noc_dec_TO_iniu0_SIG_mst_req_rdy),
		.out_req_pld(iniu0_TO_noc_dec_SIG_out_req_pld),
		.in_rsp_vld(noc_dec_TO_iniu0_SIG_mst_rsp_vld),
		.in_rsp_rdy(iniu0_TO_noc_dec_SIG_in_rsp_rdy),
		.in_rsp_pld(noc_dec_TO_iniu0_SIG_mst_rsp_pld));
	sts_demo_dec4_sts_demo_dec4_wrap noc_dec (
		.clk(clk_dst),
		.rst_n(rstn_dst),
		.mst_req_vld(iniu0_TO_noc_dec_SIG_out_req_vld),
		.mst_req_rdy(noc_dec_TO_iniu0_SIG_mst_req_rdy),
		.mst_req_pld(iniu0_TO_noc_dec_SIG_out_req_pld),
		.mst_rsp_vld(noc_dec_TO_iniu0_SIG_mst_rsp_vld),
		.mst_rsp_rdy(iniu0_TO_noc_dec_SIG_in_rsp_rdy),
		.mst_rsp_pld(noc_dec_TO_iniu0_SIG_mst_rsp_pld),
		.slv0_req_vld(noc_dec_TO_tniu0_SIG_slv0_req_vld),
		.slv0_req_rdy(tniu0_TO_noc_dec_SIG_in_req_rdy),
		.slv0_req_pld(noc_dec_TO_tniu0_SIG_slv0_req_pld),
		.slv0_rsp_vld(tniu0_TO_noc_dec_SIG_out_rsp_vld),
		.slv0_rsp_rdy(noc_dec_TO_tniu0_SIG_slv0_rsp_rdy),
		.slv0_rsp_pld(tniu0_TO_noc_dec_SIG_out_rsp_pld),
		.slv1_req_vld(noc_dec_TO_tniu1_SIG_slv1_req_vld),
		.slv1_req_rdy(tniu1_TO_noc_dec_SIG_in_req_rdy),
		.slv1_req_pld(noc_dec_TO_tniu1_SIG_slv1_req_pld),
		.slv1_rsp_vld(tniu1_TO_noc_dec_SIG_out_rsp_vld),
		.slv1_rsp_rdy(noc_dec_TO_tniu1_SIG_slv1_rsp_rdy),
		.slv1_rsp_pld(tniu1_TO_noc_dec_SIG_out_rsp_pld),
		.slv2_req_vld(noc_dec_TO_tniu2_SIG_slv2_req_vld),
		.slv2_req_rdy(tniu2_TO_noc_dec_SIG_in_req_rdy),
		.slv2_req_pld(noc_dec_TO_tniu2_SIG_slv2_req_pld),
		.slv2_rsp_vld(tniu2_TO_noc_dec_SIG_out_rsp_vld),
		.slv2_rsp_rdy(noc_dec_TO_tniu2_SIG_slv2_rsp_rdy),
		.slv2_rsp_pld(tniu2_TO_noc_dec_SIG_out_rsp_pld),
		.slv3_req_vld(noc_dec_TO_tniu3_SIG_slv3_req_vld),
		.slv3_req_rdy(tniu3_TO_noc_dec_SIG_in_req_rdy),
		.slv3_req_pld(noc_dec_TO_tniu3_SIG_slv3_req_pld),
		.slv3_rsp_vld(tniu3_TO_noc_dec_SIG_out_rsp_vld),
		.slv3_rsp_rdy(noc_dec_TO_tniu3_SIG_slv3_rsp_rdy),
		.slv3_rsp_pld(tniu3_TO_noc_dec_SIG_out_rsp_pld));
	sts_demo_tniu0_sts_demo_tniu0_wrap tniu0 (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.rstn_dbg_timer(rstn_dbg_timer),
		.in_req_vld(noc_dec_TO_tniu0_SIG_slv0_req_vld),
		.in_req_rdy(tniu0_TO_noc_dec_SIG_in_req_rdy),
		.in_req_pld(noc_dec_TO_tniu0_SIG_slv0_req_pld),
		.out_rsp_vld(tniu0_TO_noc_dec_SIG_out_rsp_vld),
		.out_rsp_rdy(noc_dec_TO_tniu0_SIG_slv0_rsp_rdy),
		.out_rsp_pld(tniu0_TO_noc_dec_SIG_out_rsp_pld),
		.pmc_psel(tniu0_pmc_apb_porting_pmc_psel),
		.pmc_penable(tniu0_pmc_apb_porting_pmc_penable),
		.pmc_paddr(tniu0_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(tniu0_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(tniu0_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(tniu0_pmc_apb_porting_pmc_prdata),
		.pmc_pready(tniu0_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(tniu0_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(tniu0_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(tniu0_pmc_apb_porting_pmc_pslverr),
		.m_psel(tniu0_sys_apb_porting_m_psel),
		.m_paddr(tniu0_sys_apb_porting_m_paddr),
		.m_pready(tniu0_sys_apb_porting_m_pready),
		.m_prdata(tniu0_sys_apb_porting_m_prdata),
		.m_pslverr(tniu0_sys_apb_porting_m_pslverr),
		.m_pprot(tniu0_sys_apb_porting_m_pprot),
		.m_penable(tniu0_sys_apb_porting_m_penable),
		.m_pwrite(tniu0_sys_apb_porting_m_pwrite),
		.m_pwdata(tniu0_sys_apb_porting_m_pwdata),
		.m_pstrb(tniu0_sys_apb_porting_m_pstrb),
		.dbg_data_in(tniu0_dbg_data_porting_dbg_data_in),
		.dbg_data_out(tniu0_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(tniu0_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(tniu0_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(tniu0_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(tniu0_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(tniu0_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(tniu0_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(tniu0_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(tniu0_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(tniu0_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(tniu0_noc_cti_channel_porting_noc_cti_channel_in));
	sts_demo_tniu1_sts_demo_tniu1_wrap tniu1 (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.rstn_dbg_timer(rstn_dbg_timer),
		.in_req_vld(noc_dec_TO_tniu1_SIG_slv1_req_vld),
		.in_req_rdy(tniu1_TO_noc_dec_SIG_in_req_rdy),
		.in_req_pld(noc_dec_TO_tniu1_SIG_slv1_req_pld),
		.out_rsp_vld(tniu1_TO_noc_dec_SIG_out_rsp_vld),
		.out_rsp_rdy(noc_dec_TO_tniu1_SIG_slv1_rsp_rdy),
		.out_rsp_pld(tniu1_TO_noc_dec_SIG_out_rsp_pld),
		.pmc_psel(tniu1_pmc_apb_porting_pmc_psel),
		.pmc_penable(tniu1_pmc_apb_porting_pmc_penable),
		.pmc_paddr(tniu1_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(tniu1_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(tniu1_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(tniu1_pmc_apb_porting_pmc_prdata),
		.pmc_pready(tniu1_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(tniu1_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(tniu1_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(tniu1_pmc_apb_porting_pmc_pslverr),
		.m_psel(tniu1_sys_apb_porting_m_psel),
		.m_paddr(tniu1_sys_apb_porting_m_paddr),
		.m_pready(tniu1_sys_apb_porting_m_pready),
		.m_prdata(tniu1_sys_apb_porting_m_prdata),
		.m_pslverr(tniu1_sys_apb_porting_m_pslverr),
		.m_pprot(tniu1_sys_apb_porting_m_pprot),
		.m_penable(tniu1_sys_apb_porting_m_penable),
		.m_pwrite(tniu1_sys_apb_porting_m_pwrite),
		.m_pwdata(tniu1_sys_apb_porting_m_pwdata),
		.m_pstrb(tniu1_sys_apb_porting_m_pstrb),
		.dbg_data_in(tniu1_dbg_data_porting_dbg_data_in),
		.dbg_data_out(tniu1_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(tniu1_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(tniu1_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(tniu1_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(tniu1_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(tniu1_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(tniu1_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(tniu1_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(tniu1_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(tniu1_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(tniu1_noc_cti_channel_porting_noc_cti_channel_in));
	sts_demo_tniu2_sts_demo_tniu2_wrap tniu2 (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.rstn_dbg_timer(rstn_dbg_timer),
		.in_req_vld(noc_dec_TO_tniu2_SIG_slv2_req_vld),
		.in_req_rdy(tniu2_TO_noc_dec_SIG_in_req_rdy),
		.in_req_pld(noc_dec_TO_tniu2_SIG_slv2_req_pld),
		.out_rsp_vld(tniu2_TO_noc_dec_SIG_out_rsp_vld),
		.out_rsp_rdy(noc_dec_TO_tniu2_SIG_slv2_rsp_rdy),
		.out_rsp_pld(tniu2_TO_noc_dec_SIG_out_rsp_pld),
		.pmc_psel(tniu2_pmc_apb_porting_pmc_psel),
		.pmc_penable(tniu2_pmc_apb_porting_pmc_penable),
		.pmc_paddr(tniu2_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(tniu2_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(tniu2_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(tniu2_pmc_apb_porting_pmc_prdata),
		.pmc_pready(tniu2_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(tniu2_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(tniu2_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(tniu2_pmc_apb_porting_pmc_pslverr),
		.m_psel(tniu2_sys_apb_porting_m_psel),
		.m_paddr(tniu2_sys_apb_porting_m_paddr),
		.m_pready(tniu2_sys_apb_porting_m_pready),
		.m_prdata(tniu2_sys_apb_porting_m_prdata),
		.m_pslverr(tniu2_sys_apb_porting_m_pslverr),
		.m_pprot(tniu2_sys_apb_porting_m_pprot),
		.m_penable(tniu2_sys_apb_porting_m_penable),
		.m_pwrite(tniu2_sys_apb_porting_m_pwrite),
		.m_pwdata(tniu2_sys_apb_porting_m_pwdata),
		.m_pstrb(tniu2_sys_apb_porting_m_pstrb),
		.dbg_data_in(tniu2_dbg_data_porting_dbg_data_in),
		.dbg_data_out(tniu2_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(tniu2_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(tniu2_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(tniu2_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(tniu2_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(tniu2_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(tniu2_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(tniu2_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(tniu2_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(tniu2_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(tniu2_noc_cti_channel_porting_noc_cti_channel_in));
	sts_demo_tniu3_sts_demo_tniu3_wrap tniu3 (
		.clk_src(clk_src),
		.clk_dst(clk_dst),
		.clk_dbg_timer(clk_dbg_timer),
		.rstn_src(rstn_src),
		.rstn_dst(rstn_dst),
		.rstn_dbg_timer(rstn_dbg_timer),
		.in_req_vld(noc_dec_TO_tniu3_SIG_slv3_req_vld),
		.in_req_rdy(tniu3_TO_noc_dec_SIG_in_req_rdy),
		.in_req_pld(noc_dec_TO_tniu3_SIG_slv3_req_pld),
		.out_rsp_vld(tniu3_TO_noc_dec_SIG_out_rsp_vld),
		.out_rsp_rdy(noc_dec_TO_tniu3_SIG_slv3_rsp_rdy),
		.out_rsp_pld(tniu3_TO_noc_dec_SIG_out_rsp_pld),
		.pmc_psel(tniu3_pmc_apb_porting_pmc_psel),
		.pmc_penable(tniu3_pmc_apb_porting_pmc_penable),
		.pmc_paddr(tniu3_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(tniu3_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(tniu3_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(tniu3_pmc_apb_porting_pmc_prdata),
		.pmc_pready(tniu3_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(tniu3_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(tniu3_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(tniu3_pmc_apb_porting_pmc_pslverr),
		.m_psel(tniu3_sys_apb_porting_m_psel),
		.m_paddr(tniu3_sys_apb_porting_m_paddr),
		.m_pready(tniu3_sys_apb_porting_m_pready),
		.m_prdata(tniu3_sys_apb_porting_m_prdata),
		.m_pslverr(tniu3_sys_apb_porting_m_pslverr),
		.m_pprot(tniu3_sys_apb_porting_m_pprot),
		.m_penable(tniu3_sys_apb_porting_m_penable),
		.m_pwrite(tniu3_sys_apb_porting_m_pwrite),
		.m_pwdata(tniu3_sys_apb_porting_m_pwdata),
		.m_pstrb(tniu3_sys_apb_porting_m_pstrb),
		.dbg_data_in(tniu3_dbg_data_porting_dbg_data_in),
		.dbg_data_out(tniu3_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(tniu3_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(tniu3_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(tniu3_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(tniu3_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(tniu3_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(tniu3_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(tniu3_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(tniu3_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(tniu3_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(tniu3_noc_cti_channel_porting_noc_cti_channel_in));

endmodule
//[UHDL]Content End [md5:ba5fc755d8a6e3ca9b7b52730557035a]

