//[UHDL]Content Start [md5:b5ef89919255f3e510d65950ca37964c]
module atb_dn_harden (
	output         async_bridge_mst_node_m_chan_porting_m_afready                       ,
	input          async_bridge_mst_node_m_chan_porting_m_afvalid                       ,
	output [2:0]   async_bridge_mst_node_m_chan_porting_m_atbytes                       ,
	output [63:0]  async_bridge_mst_node_m_chan_porting_m_atdata                        ,
	output [6:0]   async_bridge_mst_node_m_chan_porting_m_atid                          ,
	input          async_bridge_mst_node_m_chan_porting_m_atready                       ,
	output         async_bridge_mst_node_m_chan_porting_m_atvalid                       ,
	output         async_bridge_mst_node_m_chan_porting_m_atwakeup                      ,
	input          async_bridge_mst_node_m_chan_porting_m_syncreq                       ,
	input  [1:0]   right_funnel_node_atvalids_porting_atvalids                          ,
	input  [1:0]   right_funnel_node_afreadys_porting_afreadys                          ,
	input  [13:0]  right_funnel_node_atids_porting_atids                                ,
	input  [255:0] right_funnel_node_atdatas_porting_atdatas                            ,
	input  [7:0]   right_funnel_node_atbytess_porting_atbytess                          ,
	input          right_funnel_node_atreadym_porting_atreadym                          ,
	input          right_funnel_node_afvalidm_porting_afvalidm                          ,
	input          right_funnel_node_syncreqm_porting_syncreqm                          ,
	output         right_funnel_node_atvalidm_porting_atvalidm                          ,
	output         right_funnel_node_afreadym_porting_afreadym                          ,
	output [6:0]   right_funnel_node_atidm_porting_atidm                                ,
	output [127:0] right_funnel_node_atdatam_porting_atdatam                            ,
	output [3:0]   right_funnel_node_atbytesm_porting_atbytesm                          ,
	output [1:0]   right_funnel_node_atreadys_porting_atreadys                          ,
	output [1:0]   right_funnel_node_afvalids_porting_afvalids                          ,
	output [1:0]   right_funnel_node_syncreqs_porting_syncreqs                          ,
	input          right_funnel_node_pclkendbg_porting_pclkendbg                        ,
	input          right_funnel_node_pseldbg_porting_pseldbg                            ,
	input          right_funnel_node_penabledbg_porting_penabledbg                      ,
	input          right_funnel_node_pwritedbg_porting_pwritedbg                        ,
	input          right_funnel_node_paddrdbg31_porting_paddrdbg31                      ,
	input  [9:0]   right_funnel_node_paddrdbg_porting_paddrdbg                          ,
	input  [31:0]  right_funnel_node_pwdatadbg_porting_pwdatadbg                        ,
	output         right_funnel_node_preadydbg_porting_preadydbg                        ,
	output         right_funnel_node_pslverrdbg_porting_pslverrdbg                      ,
	output [31:0]  right_funnel_node_prdatadbg_porting_prdatadbg                        ,
	output         camera_ss_top_node_m_chan_porting_m_afready                          ,
	input          camera_ss_top_node_m_chan_porting_m_afvalid                          ,
	output [3:0]   camera_ss_top_node_m_chan_porting_m_atbytes                          ,
	output [127:0] camera_ss_top_node_m_chan_porting_m_atdata                           ,
	output [6:0]   camera_ss_top_node_m_chan_porting_m_atid                             ,
	input          camera_ss_top_node_m_chan_porting_m_atready                          ,
	output         camera_ss_top_node_m_chan_porting_m_atvalid                          ,
	output         camera_ss_top_node_m_chan_porting_m_atwakeup                         ,
	input          camera_ss_top_node_m_chan_porting_m_syncreq                          ,
	output         camera_ss_top_node_sync_ctrl_porting_flush_req_level                 ,
	output         camera_ss_top_node_sync_ctrl_porting_syncreq_level                   ,
	input  [12:0]  camera_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req              ,
	output [12:0]  camera_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req              ,
	input  [142:0] camera_ss_top_node_async_fifo_porting_pld_sync                       ,
	output [15:0]  camera_ss_top_node_async_fifo_porting_rptr_async                     ,
	output [15:0]  camera_ss_top_node_async_fifo_porting_rptr_sync                      ,
	input  [15:0]  camera_ss_top_node_async_fifo_porting_wptr_async                     ,
	input  [12:0]  camera_ss_top_node_lp_rx_porting_lw_rx_req                           ,
	output [12:0]  camera_ss_top_node_lp_tx_porting_lw_tx_req                           ,
	input  [9:0]   camera_ss_top_node_timeout_val_porting_timeout_val                   ,
	output         mipi_ss_top_node_m_chan_porting_m_afready                            ,
	input          mipi_ss_top_node_m_chan_porting_m_afvalid                            ,
	output [3:0]   mipi_ss_top_node_m_chan_porting_m_atbytes                            ,
	output [127:0] mipi_ss_top_node_m_chan_porting_m_atdata                             ,
	output [6:0]   mipi_ss_top_node_m_chan_porting_m_atid                               ,
	input          mipi_ss_top_node_m_chan_porting_m_atready                            ,
	output         mipi_ss_top_node_m_chan_porting_m_atvalid                            ,
	output         mipi_ss_top_node_m_chan_porting_m_atwakeup                           ,
	input          mipi_ss_top_node_m_chan_porting_m_syncreq                            ,
	output         mipi_ss_top_node_sync_ctrl_porting_flush_req_level                   ,
	output         mipi_ss_top_node_sync_ctrl_porting_syncreq_level                     ,
	input  [12:0]  mipi_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req                ,
	output [12:0]  mipi_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req                ,
	input  [142:0] mipi_ss_top_node_async_fifo_porting_pld_sync                         ,
	output [15:0]  mipi_ss_top_node_async_fifo_porting_rptr_async                       ,
	output [15:0]  mipi_ss_top_node_async_fifo_porting_rptr_sync                        ,
	input  [15:0]  mipi_ss_top_node_async_fifo_porting_wptr_async                       ,
	input  [12:0]  mipi_ss_top_node_lp_rx_porting_lw_rx_req                             ,
	output [12:0]  mipi_ss_top_node_lp_tx_porting_lw_tx_req                             ,
	input  [9:0]   mipi_ss_top_node_timeout_val_porting_timeout_val                     ,
	input          debug_tniu_ss_top_node_s_chan_porting_s_afready                      ,
	output         debug_tniu_ss_top_node_s_chan_porting_s_afvalid                      ,
	input  [3:0]   debug_tniu_ss_top_node_s_chan_porting_s_atbytes                      ,
	input  [127:0] debug_tniu_ss_top_node_s_chan_porting_s_atdata                       ,
	input  [6:0]   debug_tniu_ss_top_node_s_chan_porting_s_atid                         ,
	output         debug_tniu_ss_top_node_s_chan_porting_s_atready                      ,
	input          debug_tniu_ss_top_node_s_chan_porting_s_atvalid                      ,
	input          debug_tniu_ss_top_node_s_chan_porting_s_atwakeup                     ,
	output         debug_tniu_ss_top_node_s_chan_porting_s_syncreq                      ,
	input          debug_tniu_ss_top_node_flush_req_porting_flush_req                   ,
	output [142:0] debug_tniu_ss_top_node_async_fifo_porting_pld_sync                   ,
	input  [15:0]  debug_tniu_ss_top_node_async_fifo_porting_rptr_async                 ,
	input  [15:0]  debug_tniu_ss_top_node_async_fifo_porting_rptr_sync                  ,
	output [15:0]  debug_tniu_ss_top_node_async_fifo_porting_wptr_async                 ,
	input          debug_tniu_ss_top_node_syncreq_level_porting_syncreq_level           ,
	input  [12:0]  debug_tniu_ss_top_node_lp_lw_porting_lw_rx_req                       ,
	output [12:0]  debug_tniu_ss_top_node_lp_lw_porting_lw_tx_req                       ,
	input  [12:0]  debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_rx_req             ,
	output [12:0]  debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_tx_req             ,
	input  [9:0]   debug_tniu_ss_top_node_timeout_val_porting_timeout_val               ,
	input          async_bridge_mst_side_async_bridge_slv_side_clk_dst_porting_porting  ,
	input          async_bridge_mst_side_async_bridge_slv_side_rst_dst_n_porting_porting);

	//Wire define for this module.

	//Wire define for sub module.

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	atb_async_bridge_top async_bridge_mst_side (
		.clk_atb_s(),
		.rstn_atb_s(),
		.s_atvalid(),
		.s_atready(),
		.s_atbytes(),
		.s_atdata(),
		.s_atid(),
		.s_afvalid(),
		.s_afready(),
		.s_syncreq(),
		.s_atwakeup(),
		.slv_full_zero(),
		.clk_atb_m(async_bridge_mst_side_async_bridge_slv_side_clk_dst_porting_porting),
		.rstn_atb_m(async_bridge_mst_side_async_bridge_slv_side_rst_dst_n_porting_porting),
		.m_atvalid(async_bridge_mst_node_m_chan_porting_m_atvalid),
		.m_atready(async_bridge_mst_node_m_chan_porting_m_atready),
		.m_atbytes(async_bridge_mst_node_m_chan_porting_m_atbytes),
		.m_atdata(async_bridge_mst_node_m_chan_porting_m_atdata),
		.m_atid(async_bridge_mst_node_m_chan_porting_m_atid),
		.m_afvalid(async_bridge_mst_node_m_chan_porting_m_afvalid),
		.m_afready(async_bridge_mst_node_m_chan_porting_m_afready),
		.m_syncreq(async_bridge_mst_node_m_chan_porting_m_syncreq),
		.m_atwakeup(async_bridge_mst_node_m_chan_porting_m_atwakeup),
		.mst_full_zero(),
		.mst_read_idle());
	atb_funnel right_funnel (
		.clk(async_bridge_mst_side_async_bridge_slv_side_clk_dst_porting_porting),
		.resetn(async_bridge_mst_side_async_bridge_slv_side_rst_dst_n_porting_porting),
		.pclkendbg(right_funnel_node_pclkendbg_porting_pclkendbg),
		.pseldbg(right_funnel_node_pseldbg_porting_pseldbg),
		.penabledbg(right_funnel_node_penabledbg_porting_penabledbg),
		.pwritedbg(right_funnel_node_pwritedbg_porting_pwritedbg),
		.paddrdbg31(right_funnel_node_paddrdbg31_porting_paddrdbg31),
		.paddrdbg(right_funnel_node_paddrdbg_porting_paddrdbg),
		.pwdatadbg(right_funnel_node_pwdatadbg_porting_pwdatadbg),
		.atvalids(right_funnel_node_atvalids_porting_atvalids),
		.afreadys(right_funnel_node_afreadys_porting_afreadys),
		.atids(right_funnel_node_atids_porting_atids),
		.atdatas(right_funnel_node_atdatas_porting_atdatas),
		.atbytess(right_funnel_node_atbytess_porting_atbytess),
		.atreadym(right_funnel_node_atreadym_porting_atreadym),
		.afvalidm(right_funnel_node_afvalidm_porting_afvalidm),
		.syncreqm(right_funnel_node_syncreqm_porting_syncreqm),
		.preadydbg(right_funnel_node_preadydbg_porting_preadydbg),
		.pslverrdbg(right_funnel_node_pslverrdbg_porting_pslverrdbg),
		.prdatadbg(right_funnel_node_prdatadbg_porting_prdatadbg),
		.atvalidm(right_funnel_node_atvalidm_porting_atvalidm),
		.afreadym(right_funnel_node_afreadym_porting_afreadym),
		.atidm(right_funnel_node_atidm_porting_atidm),
		.atdatam(right_funnel_node_atdatam_porting_atdatam),
		.atbytesm(right_funnel_node_atbytesm_porting_atbytesm),
		.atreadys(right_funnel_node_atreadys_porting_atreadys),
		.afvalids(right_funnel_node_afvalids_porting_afvalids),
		.syncreqs(right_funnel_node_syncreqs_porting_syncreqs));
	atb_iniu_noc camera_ss_top_wrap (
		.clk_atb_m(async_bridge_mst_side_async_bridge_slv_side_clk_dst_porting_porting),
		.rstn_atb_m(async_bridge_mst_side_async_bridge_slv_side_rst_dst_n_porting_porting),
		.m_atvalid(camera_ss_top_node_m_chan_porting_m_atvalid),
		.m_atready(camera_ss_top_node_m_chan_porting_m_atready),
		.m_atbytes(camera_ss_top_node_m_chan_porting_m_atbytes),
		.m_atdata(camera_ss_top_node_m_chan_porting_m_atdata),
		.m_atid(camera_ss_top_node_m_chan_porting_m_atid),
		.m_afvalid(camera_ss_top_node_m_chan_porting_m_afvalid),
		.m_afready(camera_ss_top_node_m_chan_porting_m_afready),
		.m_syncreq(camera_ss_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(camera_ss_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(camera_ss_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(camera_ss_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(camera_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(camera_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(camera_ss_top_node_async_fifo_porting_wptr_async),
		.rptr_async(camera_ss_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(camera_ss_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(camera_ss_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(camera_ss_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(camera_ss_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(camera_ss_top_node_timeout_val_porting_timeout_val));
	atb_iniu_noc mipi_ss_top_wrap (
		.clk_atb_m(async_bridge_mst_side_async_bridge_slv_side_clk_dst_porting_porting),
		.rstn_atb_m(async_bridge_mst_side_async_bridge_slv_side_rst_dst_n_porting_porting),
		.m_atvalid(mipi_ss_top_node_m_chan_porting_m_atvalid),
		.m_atready(mipi_ss_top_node_m_chan_porting_m_atready),
		.m_atbytes(mipi_ss_top_node_m_chan_porting_m_atbytes),
		.m_atdata(mipi_ss_top_node_m_chan_porting_m_atdata),
		.m_atid(mipi_ss_top_node_m_chan_porting_m_atid),
		.m_afvalid(mipi_ss_top_node_m_chan_porting_m_afvalid),
		.m_afready(mipi_ss_top_node_m_chan_porting_m_afready),
		.m_syncreq(mipi_ss_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(mipi_ss_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(mipi_ss_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(mipi_ss_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(mipi_ss_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(mipi_ss_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(mipi_ss_top_node_async_fifo_porting_wptr_async),
		.rptr_async(mipi_ss_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(mipi_ss_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(mipi_ss_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(mipi_ss_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(mipi_ss_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(mipi_ss_top_node_timeout_val_porting_timeout_val));
	atb_tniu_noc debug_tniu_top_wrap (
		.clk_atb_s(async_bridge_mst_side_async_bridge_slv_side_clk_dst_porting_porting),
		.rstn_atb_s(async_bridge_mst_side_async_bridge_slv_side_rst_dst_n_porting_porting),
		.s_atvalid(debug_tniu_ss_top_node_s_chan_porting_s_atvalid),
		.s_atready(debug_tniu_ss_top_node_s_chan_porting_s_atready),
		.s_atbytes(debug_tniu_ss_top_node_s_chan_porting_s_atbytes),
		.s_atdata(debug_tniu_ss_top_node_s_chan_porting_s_atdata),
		.s_atid(debug_tniu_ss_top_node_s_chan_porting_s_atid),
		.s_afvalid(debug_tniu_ss_top_node_s_chan_porting_s_afvalid),
		.s_afready(debug_tniu_ss_top_node_s_chan_porting_s_afready),
		.s_syncreq(debug_tniu_ss_top_node_s_chan_porting_s_syncreq),
		.s_atwakeup(debug_tniu_ss_top_node_s_chan_porting_s_atwakeup),
		.flush_req(debug_tniu_ss_top_node_flush_req_porting_flush_req),
		.aifo_slv_full_zero(),
		.wptr_async(debug_tniu_ss_top_node_async_fifo_porting_wptr_async),
		.rptr_async(debug_tniu_ss_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(debug_tniu_ss_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(debug_tniu_ss_top_node_async_fifo_porting_pld_sync),
		.syncreq_level(debug_tniu_ss_top_node_syncreq_level_porting_syncreq_level),
		.lw_rx_req(debug_tniu_ss_top_node_lp_lw_porting_lw_rx_req),
		.lw_tx_req(debug_tniu_ss_top_node_lp_lw_porting_lw_tx_req),
		.afifo_slv_rx_req(debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_rx_req),
		.afifo_slv_tx_req(debug_tniu_ss_top_node_lp_afifo_porting_afifo_slv_tx_req),
		.timeout_val(debug_tniu_ss_top_node_timeout_val_porting_timeout_val));

endmodule
//[UHDL]Content End [md5:b5ef89919255f3e510d65950ca37964c]

