$CPUSS_TNIU_SYS_OUT_DIR/cpuss_tniu_sys_macros_bfa02fee06.sv
$CPUSS_TNIU_SYS_OUT_DIR/sts_tniu_define.sv
$CPUSS_TNIU_SYS_OUT_DIR/lwnoc_sts_pack.sv
$CPUSS_TNIU_SYS_OUT_DIR/RegSpaceBase_cfg_reg_bank_table_sys.v
$CPUSS_TNIU_SYS_OUT_DIR/sts_tniu_apb_dec.sv
$CPUSS_TNIU_SYS_OUT_DIR/sts_tniu_apb.sv
$CPUSS_TNIU_SYS_OUT_DIR/sts_tniu_sys.sv
$CPUSS_TNIU_SYS_OUT_DIR/sts_tniu_undefine.sv
