`define dti_iniu_top_dspss3_INIU_ROUTE_BASE 12
`define dti_iniu_top_dspss3_PAYLOAD_WIDTH 90
`define dti_iniu_top_dspss3_TBU_NUM 1
`define dti_iniu_top_dspss3_TID_WIDTH 6
`define dti_iniu_top_dspss3_TRANSACTION_MAX_NUM 8
