module `_PREFIX_(sts_demo_tniu1_wrap)
    import `_PREFIX_(lwnoc_sts_pack)::*;
(
    input   logic                    clk_src,
    input   logic                    clk_dst,
    input   logic                    clk_dbg_timer,
    input   logic                    rstn_src,
    input   logic                    rstn_dst,
    input   logic                    rstn_dbg_timer,
    input   logic                    in_req_vld,
    output  logic                    in_req_rdy,
    input   sts_req_typ              in_req_pld,
    output  logic                    out_rsp_vld,
    input   logic                    out_rsp_rdy,
    output  sts_rsp_typ              out_rsp_pld,
    output  logic                    pmc_psel,
    output  logic                    pmc_penable,
    output  logic [31:0]             pmc_paddr,
    output  logic                    pmc_pwrite,
    output  logic [31:0]             pmc_pwdata,
    input   logic [31:0]             pmc_prdata,
    input   logic                    pmc_pready,
    output  logic [3:0]              pmc_pstrb,
    output  logic [2:0]              pmc_pprot,
    input   logic                    pmc_pslverr,
    output  logic [9:0]              m_psel,
    output  logic [31:0]             m_paddr,
    input   logic [9:0]              m_pready,
    input   logic [10*32-1:0]        m_prdata,
    input   logic [9:0]              m_pslverr,
    output  logic [2:0]              m_pprot,
    output  logic                    m_penable,
    output  logic                    m_pwrite,
    output  logic [31:0]             m_pwdata,
    output  logic [3:0]              m_pstrb
);

    localparam logic [`STS_DEMO_SYS_APB_MASTER_NUM*TGT_ID_WIDTH-1:0] SYS_APB_ROUTE_BASE = `STS_DEMO_SYS_APB_ROUTE_BASE;
    localparam logic [`STS_DEMO_SYS_APB_MASTER_NUM*TGT_ID_WIDTH-1:0] SYS_APB_ROUTE_MASK = `STS_DEMO_SYS_APB_ROUTE_MASK;

    `_PREFIX_(sts_tniu_top) #(
        .APB_ADDR_WIDTH        (`STS_DEMO_APB_ADDR_WIDTH),
        .LOCAL_RSC_TGT_ID      (`STS_DEMO_LOCAL_RSC_TGT_ID),
        .LOCAL_REGBANK_TGT_ID  (`STS_DEMO_LOCAL_REGBANK_TGT_ID),
        .SYS_APB_MASTER_NUM    (`STS_DEMO_SYS_APB_MASTER_NUM),
        .SYS_APB_ROUTE_BASE    (SYS_APB_ROUTE_BASE),
        .SYS_APB_ROUTE_MASK    (SYS_APB_ROUTE_MASK)
    ) u_sts_tniu_top (
        .clk_src            (clk_dst),
        .clk_dst            (clk_src),
        .clk_dbg_timer      (clk_dbg_timer),
        .rstn_src           (rstn_dst),
        .rstn_dst           (rstn_src),
        .rstn_dbg_timer     (rstn_dbg_timer),
        .in_req_vld         (in_req_vld),
        .in_req_rdy         (in_req_rdy),
        .in_req_pld         (in_req_pld),
        .out_rsp_vld        (out_rsp_vld),
        .out_rsp_rdy        (out_rsp_rdy),
        .out_rsp_pld        (out_rsp_pld),
        .pmc_psel           (pmc_psel),
        .pmc_penable        (pmc_penable),
        .pmc_paddr          (pmc_paddr),
        .pmc_pwrite         (pmc_pwrite),
        .pmc_pwdata         (pmc_pwdata),
        .pmc_prdata         (pmc_prdata),
        .pmc_pready         (pmc_pready),
        .pmc_pstrb          (pmc_pstrb),
        .pmc_pprot          (pmc_pprot),
        .pmc_pslverr        (pmc_pslverr),
        .m_psel             (m_psel),
        .m_paddr            (m_paddr),
        .m_pready           (m_pready),
        .m_prdata           (m_prdata),
        .m_pslverr          (m_pslverr),
        .m_pprot            (m_pprot),
        .m_penable          (m_penable),
        .m_pwrite           (m_pwrite),
        .m_pwdata           (m_pwdata),
        .m_pstrb            (m_pstrb),
        .write_stall        (1'b0),
        .write_clear        (1'b0),
        .write_full_zero    (),
        .dbg_data_in        ('0),
        .dbg_data_out       (),
        .dbg_timestamp_in   ('0),
        .dbg_timestamp_out  (),
        .sys_cti_event_in   ('0),
        .sys_cti_event_out  (),
        .noc_cti_event_out  (),
        .noc_cti_event_in   ('0),
        .sys_cti_channel_in ('0),
        .sys_cti_channel_out(),
        .noc_cti_channel_out(),
        .noc_cti_channel_in ('0),
        .timing_bus1        (),
        .timing_bus2        (),
        .timing_bus3        (),
        .dbg_en             ()
    );

endmodule