//[UHDL]Content Start [md5:aaa57a8aa2414c86fabd57af5d07fa76]
module soc_sts_dn_harden (
	input          clk_harden_dn_func                                            ,
	input          rst_harden_dn_func_n                                          ,
	input  [118:0] camera_ss_tniu_top_req_porting_in_req_pld                     ,
	output         camera_ss_tniu_top_req_porting_in_req_rdy                     ,
	input          camera_ss_tniu_top_req_porting_in_req_vld                     ,
	output [64:0]  camera_ss_tniu_top_rsp_porting_out_rsp_pld                    ,
	input          camera_ss_tniu_top_rsp_porting_out_rsp_rdy                    ,
	output         camera_ss_tniu_top_rsp_porting_out_rsp_vld                    ,
	output [31:0]  camera_ss_tniu_top_pmc_apb_porting_pmc_paddr                  ,
	output         camera_ss_tniu_top_pmc_apb_porting_pmc_penable                ,
	output [2:0]   camera_ss_tniu_top_pmc_apb_porting_pmc_pprot                  ,
	input  [31:0]  camera_ss_tniu_top_pmc_apb_porting_pmc_prdata                 ,
	input          camera_ss_tniu_top_pmc_apb_porting_pmc_pready                 ,
	output         camera_ss_tniu_top_pmc_apb_porting_pmc_psel                   ,
	input          camera_ss_tniu_top_pmc_apb_porting_pmc_pslverr                ,
	output [3:0]   camera_ss_tniu_top_pmc_apb_porting_pmc_pstrb                  ,
	output [31:0]  camera_ss_tniu_top_pmc_apb_porting_pmc_pwdata                 ,
	output         camera_ss_tniu_top_pmc_apb_porting_pmc_pwrite                 ,
	output [31:0]  camera_ss_tniu_top_sys_apb_porting_m_paddr                    ,
	output         camera_ss_tniu_top_sys_apb_porting_m_penable                  ,
	output [2:0]   camera_ss_tniu_top_sys_apb_porting_m_pprot                    ,
	input  [63:0]  camera_ss_tniu_top_sys_apb_porting_m_prdata                   ,
	input  [1:0]   camera_ss_tniu_top_sys_apb_porting_m_pready                   ,
	output [1:0]   camera_ss_tniu_top_sys_apb_porting_m_psel                     ,
	input  [1:0]   camera_ss_tniu_top_sys_apb_porting_m_pslverr                  ,
	output [3:0]   camera_ss_tniu_top_sys_apb_porting_m_pstrb                    ,
	output [31:0]  camera_ss_tniu_top_sys_apb_porting_m_pwdata                   ,
	output         camera_ss_tniu_top_sys_apb_porting_m_pwrite                   ,
	input  [31:0]  camera_ss_tniu_top_dbg_data_porting_dbg_data_in               ,
	output [31:0]  camera_ss_tniu_top_dbg_data_porting_dbg_data_out              ,
	input  [63:0]  camera_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_in     ,
	output [63:0]  camera_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_out    ,
	input  [7:0]   camera_ss_tniu_top_sys_cti_event_porting_sys_cti_event_in     ,
	output [7:0]   camera_ss_tniu_top_sys_cti_event_porting_sys_cti_event_out    ,
	input  [7:0]   camera_ss_tniu_top_noc_cti_event_porting_noc_cti_event_in     ,
	output [7:0]   camera_ss_tniu_top_noc_cti_event_porting_noc_cti_event_out    ,
	input  [7:0]   camera_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_in ,
	output [7:0]   camera_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_out,
	input  [7:0]   camera_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_in ,
	output [7:0]   camera_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_out,
	input  [118:0] vpu_ss_tniu_top_req_porting_in_req_pld                        ,
	output         vpu_ss_tniu_top_req_porting_in_req_rdy                        ,
	input          vpu_ss_tniu_top_req_porting_in_req_vld                        ,
	output [64:0]  vpu_ss_tniu_top_rsp_porting_out_rsp_pld                       ,
	input          vpu_ss_tniu_top_rsp_porting_out_rsp_rdy                       ,
	output         vpu_ss_tniu_top_rsp_porting_out_rsp_vld                       ,
	output [31:0]  vpu_ss_tniu_top_pmc_apb_porting_pmc_paddr                     ,
	output         vpu_ss_tniu_top_pmc_apb_porting_pmc_penable                   ,
	output [2:0]   vpu_ss_tniu_top_pmc_apb_porting_pmc_pprot                     ,
	input  [31:0]  vpu_ss_tniu_top_pmc_apb_porting_pmc_prdata                    ,
	input          vpu_ss_tniu_top_pmc_apb_porting_pmc_pready                    ,
	output         vpu_ss_tniu_top_pmc_apb_porting_pmc_psel                      ,
	input          vpu_ss_tniu_top_pmc_apb_porting_pmc_pslverr                   ,
	output [3:0]   vpu_ss_tniu_top_pmc_apb_porting_pmc_pstrb                     ,
	output [31:0]  vpu_ss_tniu_top_pmc_apb_porting_pmc_pwdata                    ,
	output         vpu_ss_tniu_top_pmc_apb_porting_pmc_pwrite                    ,
	output [31:0]  vpu_ss_tniu_top_sys_apb_porting_m_paddr                       ,
	output         vpu_ss_tniu_top_sys_apb_porting_m_penable                     ,
	output [2:0]   vpu_ss_tniu_top_sys_apb_porting_m_pprot                       ,
	input  [63:0]  vpu_ss_tniu_top_sys_apb_porting_m_prdata                      ,
	input  [1:0]   vpu_ss_tniu_top_sys_apb_porting_m_pready                      ,
	output [1:0]   vpu_ss_tniu_top_sys_apb_porting_m_psel                        ,
	input  [1:0]   vpu_ss_tniu_top_sys_apb_porting_m_pslverr                     ,
	output [3:0]   vpu_ss_tniu_top_sys_apb_porting_m_pstrb                       ,
	output [31:0]  vpu_ss_tniu_top_sys_apb_porting_m_pwdata                      ,
	output         vpu_ss_tniu_top_sys_apb_porting_m_pwrite                      ,
	input  [31:0]  vpu_ss_tniu_top_dbg_data_porting_dbg_data_in                  ,
	output [31:0]  vpu_ss_tniu_top_dbg_data_porting_dbg_data_out                 ,
	input  [63:0]  vpu_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_in        ,
	output [63:0]  vpu_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_out       ,
	input  [7:0]   vpu_ss_tniu_top_sys_cti_event_porting_sys_cti_event_in        ,
	output [7:0]   vpu_ss_tniu_top_sys_cti_event_porting_sys_cti_event_out       ,
	input  [7:0]   vpu_ss_tniu_top_noc_cti_event_porting_noc_cti_event_in        ,
	output [7:0]   vpu_ss_tniu_top_noc_cti_event_porting_noc_cti_event_out       ,
	input  [7:0]   vpu_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_in    ,
	output [7:0]   vpu_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_out   ,
	input  [7:0]   vpu_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_in    ,
	output [7:0]   vpu_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_out   ,
	input  [7:0]   aon_ss_iniu_top_side_node_id_porting_node_id                  ,
	input  [31:0]  aon_ss_iniu_top_side_axi_porting_sts_iniu_s_araddr            ,
	input  [1:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arburst           ,
	input  [3:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arcache           ,
	input  [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arid              ,
	input  [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arlen             ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arlock            ,
	input  [2:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arprot            ,
	input  [3:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arqos             ,
	output         aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arready           ,
	input  [2:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arsize            ,
	input  [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_aruser            ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arvalid           ,
	input  [31:0]  aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awaddr            ,
	input  [1:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awburst           ,
	input  [3:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awcache           ,
	input  [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awid              ,
	input  [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awlen             ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awlock            ,
	input  [2:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awprot            ,
	input  [3:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awqos             ,
	output         aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awready           ,
	input  [2:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awsize            ,
	input  [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awuser            ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awvalid           ,
	output [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bid               ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bready            ,
	output [1:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bresp             ,
	output         aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bvalid            ,
	output [31:0]  aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rdata             ,
	output [7:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rid               ,
	output         aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rlast             ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rready            ,
	output [1:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rresp             ,
	output         aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rvalid            ,
	input  [31:0]  aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wdata             ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wlast             ,
	output         aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wready            ,
	input  [3:0]   aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wstrb             ,
	input          aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wvalid            ,
	output [118:0] aon_ss_iniu_top_side_req_porting_out_req_pld                  ,
	input          aon_ss_iniu_top_side_req_porting_out_req_rdy                  ,
	output         aon_ss_iniu_top_side_req_porting_out_req_vld                  ,
	input  [64:0]  aon_ss_iniu_top_side_rsp_porting_in_rsp_pld                   ,
	output         aon_ss_iniu_top_side_rsp_porting_in_rsp_rdy                   ,
	input          aon_ss_iniu_top_side_rsp_porting_in_rsp_vld                   ,
	input  [7:0]   aon_ss_iniu_top_side_cti_event_porting_noc_cti_event_in       ,
	output [7:0]   aon_ss_iniu_top_side_cti_event_porting_noc_cti_event_out      ,
	input  [7:0]   aon_ss_iniu_top_side_cti_event_porting_sys_cti_event_in       ,
	output [7:0]   aon_ss_iniu_top_side_cti_event_porting_sys_cti_event_out      ,
	input  [7:0]   aon_ss_iniu_top_side_cti_channel_porting_noc_cti_channel_in   ,
	output [7:0]   aon_ss_iniu_top_side_cti_channel_porting_noc_cti_channel_out  ,
	input  [7:0]   aon_ss_iniu_top_side_cti_channel_porting_sys_cti_channel_in   ,
	output [7:0]   aon_ss_iniu_top_side_cti_channel_porting_sys_cti_channel_out  ,
	input  [63:0]  aon_ss_iniu_top_side_dbg_timestamp_porting_dbg_timestamp_in   ,
	output [63:0]  aon_ss_iniu_top_side_dbg_timestamp_porting_dbg_timestamp_out  ,
	input  [31:0]  aon_ss_iniu_top_side_dbg_data_porting_dbg_data_in             ,
	output [31:0]  aon_ss_iniu_top_side_dbg_data_porting_dbg_data_out            ,
	input  [118:0] harden_dn_async_bridge_slv_s_chan_porting_in_req_pld          ,
	output         harden_dn_async_bridge_slv_s_chan_porting_in_req_rdy          ,
	input          harden_dn_async_bridge_slv_s_chan_porting_in_req_vld          ,
	output [119:0] harden_dn_async_bridge_slv_sync_porting_pld_sync              ,
	input  [15:0]  harden_dn_async_bridge_slv_sync_porting_rptr_async            ,
	input  [15:0]  harden_dn_async_bridge_slv_sync_porting_rptr_sync             ,
	output [15:0]  harden_dn_async_bridge_slv_sync_porting_wptr_async            ,
	input          aon_ss_iniu_top_clk_src_porting                               ,
	input          aon_ss_iniu_top_rst_sys_n_porting                             ,
	input          camera_ss_top_clk_dbg_timer_porting                           ,
	input          camera_ss_top_rst_dbg_timer_n_porting                         );

	//Wire define for this module.

	//Wire define for sub module.

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	sts_tniu_top camera_ss_top (
		.clk_src(aon_ss_iniu_top_clk_src_porting),
		.clk_dst(clk_harden_dn_func),
		.clk_dbg_timer(camera_ss_top_clk_dbg_timer_porting),
		.rstn_src(aon_ss_iniu_top_rst_sys_n_porting),
		.rstn_dst(rst_harden_dn_func_n),
		.rstn_dbg_timer(camera_ss_top_rst_dbg_timer_n_porting),
		.in_req_vld(camera_ss_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(camera_ss_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(camera_ss_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(camera_ss_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(camera_ss_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(camera_ss_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(camera_ss_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(camera_ss_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(camera_ss_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(camera_ss_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(camera_ss_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(camera_ss_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(camera_ss_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(camera_ss_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(camera_ss_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(camera_ss_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(camera_ss_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(camera_ss_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(camera_ss_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(camera_ss_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(camera_ss_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(camera_ss_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(camera_ss_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(camera_ss_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(camera_ss_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(camera_ss_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(camera_ss_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(camera_ss_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(camera_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(camera_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(camera_ss_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(camera_ss_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(camera_ss_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(camera_ss_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(camera_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(camera_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(camera_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(camera_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_tniu_top vpu_ss_top (
		.clk_src(aon_ss_iniu_top_clk_src_porting),
		.clk_dst(clk_harden_dn_func),
		.clk_dbg_timer(camera_ss_top_clk_dbg_timer_porting),
		.rstn_src(aon_ss_iniu_top_rst_sys_n_porting),
		.rstn_dst(rst_harden_dn_func_n),
		.rstn_dbg_timer(camera_ss_top_rst_dbg_timer_n_porting),
		.in_req_vld(vpu_ss_tniu_top_req_porting_in_req_vld),
		.in_req_rdy(vpu_ss_tniu_top_req_porting_in_req_rdy),
		.in_req_pld(vpu_ss_tniu_top_req_porting_in_req_pld),
		.out_rsp_vld(vpu_ss_tniu_top_rsp_porting_out_rsp_vld),
		.out_rsp_rdy(vpu_ss_tniu_top_rsp_porting_out_rsp_rdy),
		.out_rsp_pld(vpu_ss_tniu_top_rsp_porting_out_rsp_pld),
		.pmc_psel(vpu_ss_tniu_top_pmc_apb_porting_pmc_psel),
		.pmc_penable(vpu_ss_tniu_top_pmc_apb_porting_pmc_penable),
		.pmc_paddr(vpu_ss_tniu_top_pmc_apb_porting_pmc_paddr),
		.pmc_pwrite(vpu_ss_tniu_top_pmc_apb_porting_pmc_pwrite),
		.pmc_pwdata(vpu_ss_tniu_top_pmc_apb_porting_pmc_pwdata),
		.pmc_prdata(vpu_ss_tniu_top_pmc_apb_porting_pmc_prdata),
		.pmc_pready(vpu_ss_tniu_top_pmc_apb_porting_pmc_pready),
		.pmc_pstrb(vpu_ss_tniu_top_pmc_apb_porting_pmc_pstrb),
		.pmc_pprot(vpu_ss_tniu_top_pmc_apb_porting_pmc_pprot),
		.pmc_pslverr(vpu_ss_tniu_top_pmc_apb_porting_pmc_pslverr),
		.m_psel(vpu_ss_tniu_top_sys_apb_porting_m_psel),
		.m_paddr(vpu_ss_tniu_top_sys_apb_porting_m_paddr),
		.m_pready(vpu_ss_tniu_top_sys_apb_porting_m_pready),
		.m_prdata(vpu_ss_tniu_top_sys_apb_porting_m_prdata),
		.m_pslverr(vpu_ss_tniu_top_sys_apb_porting_m_pslverr),
		.m_pprot(vpu_ss_tniu_top_sys_apb_porting_m_pprot),
		.m_penable(vpu_ss_tniu_top_sys_apb_porting_m_penable),
		.m_pwrite(vpu_ss_tniu_top_sys_apb_porting_m_pwrite),
		.m_pwdata(vpu_ss_tniu_top_sys_apb_porting_m_pwdata),
		.m_pstrb(vpu_ss_tniu_top_sys_apb_porting_m_pstrb),
		.dbg_data_in(vpu_ss_tniu_top_dbg_data_porting_dbg_data_in),
		.dbg_data_out(vpu_ss_tniu_top_dbg_data_porting_dbg_data_out),
		.dbg_timestamp_in(vpu_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(vpu_ss_tniu_top_dbg_timestamp_porting_dbg_timestamp_out),
		.sys_cti_event_in(vpu_ss_tniu_top_sys_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(vpu_ss_tniu_top_sys_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(vpu_ss_tniu_top_noc_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(vpu_ss_tniu_top_noc_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(vpu_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(vpu_ss_tniu_top_sys_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(vpu_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(vpu_ss_tniu_top_noc_cti_channel_porting_noc_cti_channel_in),
		.timing_bus1(),
		.timing_bus2(),
		.timing_bus3(),
		.dbg_en());
	sts_iniu_top aon_ss_iniu_top (
		.clk_src(aon_ss_iniu_top_clk_src_porting),
		.clk_dst(clk_harden_dn_func),
		.rstn_src(aon_ss_iniu_top_rst_sys_n_porting),
		.rstn_dst(rst_harden_dn_func_n),
		.node_id(aon_ss_iniu_top_side_node_id_porting_node_id),
		.sts_iniu_s_awvalid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awvalid),
		.sts_iniu_s_awready(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awready),
		.sts_iniu_s_awid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awid),
		.sts_iniu_s_awaddr(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awaddr),
		.sts_iniu_s_awlen(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awlen),
		.sts_iniu_s_awsize(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awsize),
		.sts_iniu_s_awburst(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awburst),
		.sts_iniu_s_awlock(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awlock),
		.sts_iniu_s_awcache(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awcache),
		.sts_iniu_s_awprot(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awprot),
		.sts_iniu_s_awqos(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awqos),
		.sts_iniu_s_awuser(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_awuser),
		.sts_iniu_s_wvalid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wvalid),
		.sts_iniu_s_wready(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wready),
		.sts_iniu_s_wdata(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wdata),
		.sts_iniu_s_wstrb(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wstrb),
		.sts_iniu_s_wlast(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_wlast),
		.sts_iniu_s_bvalid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bvalid),
		.sts_iniu_s_bready(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bready),
		.sts_iniu_s_bid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bid),
		.sts_iniu_s_bresp(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_bresp),
		.sts_iniu_s_arvalid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arvalid),
		.sts_iniu_s_arready(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arready),
		.sts_iniu_s_arid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arid),
		.sts_iniu_s_araddr(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_araddr),
		.sts_iniu_s_arlen(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arlen),
		.sts_iniu_s_arsize(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arsize),
		.sts_iniu_s_arburst(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arburst),
		.sts_iniu_s_arlock(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arlock),
		.sts_iniu_s_arcache(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arcache),
		.sts_iniu_s_arprot(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arprot),
		.sts_iniu_s_arqos(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_arqos),
		.sts_iniu_s_aruser(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_aruser),
		.sts_iniu_s_rvalid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rvalid),
		.sts_iniu_s_rready(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rready),
		.sts_iniu_s_rid(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rid),
		.sts_iniu_s_rdata(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rdata),
		.sts_iniu_s_rresp(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rresp),
		.sts_iniu_s_rlast(aon_ss_iniu_top_side_axi_porting_sts_iniu_s_rlast),
		.out_req_vld(aon_ss_iniu_top_side_req_porting_out_req_vld),
		.out_req_rdy(aon_ss_iniu_top_side_req_porting_out_req_rdy),
		.out_req_pld(aon_ss_iniu_top_side_req_porting_out_req_pld),
		.in_rsp_vld(aon_ss_iniu_top_side_rsp_porting_in_rsp_vld),
		.in_rsp_rdy(aon_ss_iniu_top_side_rsp_porting_in_rsp_rdy),
		.in_rsp_pld(aon_ss_iniu_top_side_rsp_porting_in_rsp_pld),
		.sys_cti_event_in(aon_ss_iniu_top_side_cti_event_porting_sys_cti_event_in),
		.sys_cti_event_out(aon_ss_iniu_top_side_cti_event_porting_sys_cti_event_out),
		.noc_cti_event_out(aon_ss_iniu_top_side_cti_event_porting_noc_cti_event_out),
		.noc_cti_event_in(aon_ss_iniu_top_side_cti_event_porting_noc_cti_event_in),
		.sys_cti_channel_in(aon_ss_iniu_top_side_cti_channel_porting_sys_cti_channel_in),
		.sys_cti_channel_out(aon_ss_iniu_top_side_cti_channel_porting_sys_cti_channel_out),
		.noc_cti_channel_out(aon_ss_iniu_top_side_cti_channel_porting_noc_cti_channel_out),
		.noc_cti_channel_in(aon_ss_iniu_top_side_cti_channel_porting_noc_cti_channel_in),
		.dbg_timestamp_in(aon_ss_iniu_top_side_dbg_timestamp_porting_dbg_timestamp_in),
		.dbg_timestamp_out(aon_ss_iniu_top_side_dbg_timestamp_porting_dbg_timestamp_out),
		.dbg_data_in(aon_ss_iniu_top_side_dbg_data_porting_dbg_data_in),
		.dbg_data_out(aon_ss_iniu_top_side_dbg_data_porting_dbg_data_out));
	sts_async_bridge_slv async_bridge_slv (
		.clk(clk_harden_dn_func),
		.rst_n(rst_harden_dn_func_n),
		.stall(),
		.clear(),
		.full_zero(),
		.in_req_vld(harden_dn_async_bridge_slv_s_chan_porting_in_req_vld),
		.in_req_rdy(harden_dn_async_bridge_slv_s_chan_porting_in_req_rdy),
		.in_req_pld(harden_dn_async_bridge_slv_s_chan_porting_in_req_pld),
		.almost_full(),
		.wptr_async(harden_dn_async_bridge_slv_sync_porting_wptr_async),
		.rptr_async(harden_dn_async_bridge_slv_sync_porting_rptr_async),
		.rptr_sync(harden_dn_async_bridge_slv_sync_porting_rptr_sync),
		.pld_sync(harden_dn_async_bridge_slv_sync_porting_pld_sync));

endmodule
//[UHDL]Content End [md5:aaa57a8aa2414c86fabd57af5d07fa76]

