$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_dti_pr_iniu_define.sv
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_dti_iniu_pack.sv
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_dti_pr_rob_state_entry.sv
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_dti_pr.sv
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_dti_to_gnpd_conv.sv
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_dti_pr_iniu_async_sys_side.sv
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_iniu_sys_wrap.v
$SOC_DTI_DSP_SS2_INIU_SYS_DIR/dsp_ss2_iniu_node.v
