`define dti_iniu_top_dspss1_INIU_ROUTE_BASE 10
`define dti_iniu_top_dspss1_PAYLOAD_WIDTH 90
`define dti_iniu_top_dspss1_TBU_NUM 1
`define dti_iniu_top_dspss1_TID_WIDTH 6
`define dti_iniu_top_dspss1_TRANSACTION_MAX_NUM 8
