$DTI_INIU_TOP_USB_DP_SS_DIR/dti_iniu_top_side_usb_dp_ss_macros_062f893a33.sv
$DTI_INIU_TOP_USB_DP_SS_DIR/dti_iniu_top_usb_dp_ss_dti_pr_iniu_define.sv
$DTI_INIU_TOP_USB_DP_SS_DIR/dti_iniu_top_usb_dp_ss_dti_iniu_pack.sv
$DTI_INIU_TOP_USB_DP_SS_DIR/dti_iniu_top_usb_dp_ss_dti_pr_iniu_async_top_side.sv
$DTI_INIU_TOP_USB_DP_SS_DIR/dti_iniu_top_usb_dp_ss_dti_pr_iniu_undef.sv
