`ifdef dti_sw3_DTI_LINK_BUF_FORWARD_EN
    `undef DTI_LINK_BUF_FORWARD_EN
`endif

`ifdef dti_sw3_DTI_LINK_BUF_ALMOST_EMPTY_THRESHOLD
    `undef DTI_LINK_BUF_ALMOST_EMPTY_THRESHOLD
`endif

`ifdef dti_sw3_DTI_LINK_BUF_ALMOST_FULL_THRESHOLD
    `undef DTI_LINK_BUF_ALMOST_FULL_THRESHOLD
`endif

`ifdef dti_sw3_DTI_LINK_BUF_TID_WIDTH
    `undef DTI_LINK_BUF_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_LINK_BUF_PAYLOAD_WIDTH
    `undef DTI_LINK_BUF_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_LINK_BUF_FIFO_DEPTH
    `undef DTI_LINK_BUF_FIFO_DEPTH
`endif

`ifdef dti_sw3_DTI_LINK_PIPE_RS_TYPE
    `undef DTI_LINK_PIPE_RS_TYPE
`endif

`ifdef dti_sw3_DTI_LINK_PIPE_TID_WIDTH
    `undef DTI_LINK_PIPE_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_LINK_PIPE_PAYLOAD_WIDTH
    `undef DTI_LINK_PIPE_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_VT_TYPE
    `undef DTI_ASYNC_BRIDGE_MST_VT_TYPE
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_ERR_INT_CNT_WIDTH
    `undef DTI_ASYNC_BRIDGE_MST_ERR_INT_CNT_WIDTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_TID_WIDTH
    `undef DTI_ASYNC_BRIDGE_MST_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_PAYLOAD_WIDTH
    `undef DTI_ASYNC_BRIDGE_MST_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_ALMOST_EMPTY_THRESHOLD
    `undef DTI_ASYNC_BRIDGE_MST_ALMOST_EMPTY_THRESHOLD
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_THRESHOLD_EN
    `undef DTI_ASYNC_BRIDGE_MST_THRESHOLD_EN
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_FIFO_DEPTH
    `undef DTI_ASYNC_BRIDGE_MST_FIFO_DEPTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_MST_SYNC_STAGE
    `undef DTI_ASYNC_BRIDGE_MST_SYNC_STAGE
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_VT_TYPE
    `undef DTI_ASYNC_BRIDGE_SLV_VT_TYPE
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_TID_WIDTH
    `undef DTI_ASYNC_BRIDGE_SLV_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_PAYLOAD_WIDTH
    `undef DTI_ASYNC_BRIDGE_SLV_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_ALMOST_FULL_THRESHOLD
    `undef DTI_ASYNC_BRIDGE_SLV_ALMOST_FULL_THRESHOLD
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_THRESHOLD_EN
    `undef DTI_ASYNC_BRIDGE_SLV_THRESHOLD_EN
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_FIFO_DEPTH
    `undef DTI_ASYNC_BRIDGE_SLV_FIFO_DEPTH
`endif

`ifdef dti_sw3_DTI_ASYNC_BRIDGE_SLV_SYNC_STAGE
    `undef DTI_ASYNC_BRIDGE_SLV_SYNC_STAGE
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_10TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_10TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_10TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_10TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_10TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_10TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_10TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_10TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_10TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_10TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_10TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_10TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_9TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_9TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_9TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_9TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_9TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_9TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_9TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_9TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_9TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_9TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_9TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_9TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_8TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_8TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_8TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_8TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_8TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_8TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_8TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_8TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_8TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_8TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_8TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_8TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_7TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_7TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_7TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_7TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_7TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_7TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_7TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_7TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_7TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_7TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_7TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_7TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_6TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_6TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_6TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_6TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_6TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_6TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_6TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_6TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_6TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_6TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_6TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_6TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_5TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_5TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_5TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_5TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_5TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_5TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_5TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_5TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_5TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_5TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_5TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_5TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_4TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_4TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_4TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_4TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_4TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_4TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_4TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_4TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_4TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_4TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_4TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_4TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_3TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_3TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_3TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_3TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_3TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_3TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_3TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_3TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_3TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_3TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_3TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_3TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_2TO1_WRAP_INIU_DECMAX
    `undef DTI_NOC_SWITCH_2TO1_WRAP_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_2TO1_WRAP_INIU_DECMIN
    `undef DTI_NOC_SWITCH_2TO1_WRAP_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_2TO1_WRAP_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_2TO1_WRAP_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_2TO1_WRAP_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_2TO1_WRAP_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_2TO1_WRAP_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_2TO1_WRAP_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_2TO1_WRAP_TID_WIDTH
    `undef DTI_NOC_SWITCH_2TO1_WRAP_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_INIU_DECMAX
    `undef DTI_NOC_SWITCH_INIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_INIU_DECMIN
    `undef DTI_NOC_SWITCH_INIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_TNIU_DECMAX
    `undef DTI_NOC_SWITCH_TNIU_DECMAX
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_TNIU_DECMIN
    `undef DTI_NOC_SWITCH_TNIU_DECMIN
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_PAYLOAD_WIDTH
    `undef DTI_NOC_SWITCH_PAYLOAD_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_TID_WIDTH
    `undef DTI_NOC_SWITCH_TID_WIDTH
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_NUM_TNIU
    `undef DTI_NOC_SWITCH_NUM_TNIU
`endif

`ifdef dti_sw3_DTI_NOC_SWITCH_NUM_INIU
    `undef DTI_NOC_SWITCH_NUM_INIU
`endif
