$NPUSS2_TNIU_SYS_OUT_DIR/npuss2_tniu_sys_macros_5005657d53.sv
$NPUSS2_TNIU_SYS_OUT_DIR/sts_tniu_define.sv
$NPUSS2_TNIU_SYS_OUT_DIR/lwnoc_sts_pack.sv
$NPUSS2_TNIU_SYS_OUT_DIR/RegSpaceBase_cfg_reg_bank_table_sys.v
$NPUSS2_TNIU_SYS_OUT_DIR/sts_tniu_apb_dec.sv
$NPUSS2_TNIU_SYS_OUT_DIR/sts_tniu_apb.sv
$NPUSS2_TNIU_SYS_OUT_DIR/sts_tniu_sys.sv
$NPUSS2_TNIU_SYS_OUT_DIR/sts_tniu_undefine.sv
