`ifdef INTR_NETWORK_MEM_DATA_WIDTH
    `undef INTR_NETWORK_MEM_DATA_WIDTH
`endif

`ifdef INTR_NETWORK_MEM_ADDR_WIDTH
    `undef INTR_NETWORK_MEM_ADDR_WIDTH
`endif

`ifdef INTR_NETWORK_SYNC_WIDTH
    `undef INTR_NETWORK_SYNC_WIDTH
`endif

`ifdef INTR_NETWORK_SYNC_INIT_VALUE
    `undef INTR_NETWORK_SYNC_INIT_VALUE
`endif

`ifdef INTR_NETWORK_ROB_ENTRY_NUM
    `undef INTR_NETWORK_ROB_ENTRY_NUM
`endif

`ifdef INTR_NETWORK_FLOW_CTRL_ADDR_WIDTH
    `undef INTR_NETWORK_FLOW_CTRL_ADDR_WIDTH
`endif

`ifdef INTR_NETWORK_FLOW_CTRL_NODE_NUM
    `undef INTR_NETWORK_FLOW_CTRL_NODE_NUM
`endif

`ifdef INTR_NETWORK_FLOW_CTRL_THRESHOLD
    `undef INTR_NETWORK_FLOW_CTRL_THRESHOLD
`endif

`ifdef INTR_NETWORK_VCBUF_AFULL_LEVEL
    `undef INTR_NETWORK_VCBUF_AFULL_LEVEL
`endif

`ifdef INTR_NETWORK_SFIFO_AFULL_LEVEL
    `undef INTR_NETWORK_SFIFO_AFULL_LEVEL
`endif

`ifdef INTR_NETWORK_SFIFO_FIFO_WIDTH
    `undef INTR_NETWORK_SFIFO_FIFO_WIDTH
`endif

`ifdef INTR_NETWORK_SFIFO_BUF_DEP
    `undef INTR_NETWORK_SFIFO_BUF_DEP
`endif

`ifdef INTR_NETWORK_STATION_PLD_WIDTH
    `undef INTR_NETWORK_STATION_PLD_WIDTH
`endif

`ifdef INTR_NETWORK_STATION_VC_AFULL_LEVEL
    `undef INTR_NETWORK_STATION_VC_AFULL_LEVEL
`endif

`ifdef INTR_NETWORK_STATION_VC_BUF_DEPTH
    `undef INTR_NETWORK_STATION_VC_BUF_DEPTH
`endif

`ifdef INTR_NETWORK_SINK_EN
    `undef INTR_NETWORK_SINK_EN
`endif

`ifdef INTR_NETWORK_DUMMY_EN
    `undef INTR_NETWORK_DUMMY_EN
`endif

`ifdef INTR_NETWORK_ENDPOINT_HAS_TNIU
    `undef INTR_NETWORK_ENDPOINT_HAS_TNIU
`endif

`ifdef INTR_NETWORK_ENDPOINT_HAS_INIU
    `undef INTR_NETWORK_ENDPOINT_HAS_INIU
`endif

`ifdef INTR_NETWORK_ENDPOINT_SINGLE_THR_WIDTH
    `undef INTR_NETWORK_ENDPOINT_SINGLE_THR_WIDTH
`endif

`ifdef INTR_NETWORK_ENDPOINT_QOS_WIDTH
    `undef INTR_NETWORK_ENDPOINT_QOS_WIDTH
`endif

`ifdef INTR_NETWORK_ENDPOINT_ID_WIDTH
    `undef INTR_NETWORK_ENDPOINT_ID_WIDTH
`endif

`ifdef INTR_NETWORK_ENDPOINT_PLD_WIDTH
    `undef INTR_NETWORK_ENDPOINT_PLD_WIDTH
`endif

`ifdef INTR_NETWORK_ENDPOINT_NODE_NUM
    `undef INTR_NETWORK_ENDPOINT_NODE_NUM
`endif

`ifdef INTR_NETWORK_ENDPOINT_RING_ID
    `undef INTR_NETWORK_ENDPOINT_RING_ID
`endif

`ifdef INTR_NETWORK_RING_ERR_INT_CNT_WIDTH
    `undef INTR_NETWORK_RING_ERR_INT_CNT_WIDTH
`endif

`ifdef INTR_NETWORK_RING_AFIFO_DEP
    `undef INTR_NETWORK_RING_AFIFO_DEP
`endif

`ifdef INTR_NETWORK_RING_SYNC_LEVEL
    `undef INTR_NETWORK_RING_SYNC_LEVEL
`endif

`ifdef INTR_NETWORK_RING_NODE_NUM
    `undef INTR_NETWORK_RING_NODE_NUM
`endif

`ifdef INTR_NETWORK_RING_SINGLE_THR_WIDTH
    `undef INTR_NETWORK_RING_SINGLE_THR_WIDTH
`endif

`ifdef INTR_NETWORK_RING_THRESHOLD_EN
    `undef INTR_NETWORK_RING_THRESHOLD_EN
`endif

`ifdef INTR_NETWORK_RING_BUF_DEP
    `undef INTR_NETWORK_RING_BUF_DEP
`endif

`ifdef INTR_NETWORK_RING_QOS_WIDTH
    `undef INTR_NETWORK_RING_QOS_WIDTH
`endif

`ifdef INTR_NETWORK_RING_ID_WIDTH
    `undef INTR_NETWORK_RING_ID_WIDTH
`endif

`ifdef INTR_NETWORK_RING_PLD_WIDTH
    `undef INTR_NETWORK_RING_PLD_WIDTH
`endif
