`ifndef _PREFIX_
    `define _PREFIX_(x)  Base_``x
`endif

`ifndef INTR_NETWORK_RING_PLD_WIDTH
    `define INTR_NETWORK_RING_PLD_WIDTH 512
`endif

`ifndef INTR_NETWORK_RING_ID_WIDTH
    `define INTR_NETWORK_RING_ID_WIDTH 4
`endif

`ifndef INTR_NETWORK_RING_QOS_WIDTH
    `define INTR_NETWORK_RING_QOS_WIDTH 4
`endif

`ifndef INTR_NETWORK_RING_BUF_DEP
    `define INTR_NETWORK_RING_BUF_DEP 2
`endif

`ifndef INTR_NETWORK_RING_THRESHOLD_EN
    `define INTR_NETWORK_RING_THRESHOLD_EN 1'b1
`endif

`ifndef INTR_NETWORK_RING_SINGLE_THR_WIDTH
    `define INTR_NETWORK_RING_SINGLE_THR_WIDTH 1
`endif

`ifndef INTR_NETWORK_RING_NODE_NUM
    `define INTR_NETWORK_RING_NODE_NUM 16
`endif

`ifndef INTR_NETWORK_RING_SYNC_LEVEL
    `define INTR_NETWORK_RING_SYNC_LEVEL 3
`endif

`ifndef INTR_NETWORK_RING_AFIFO_DEP
    `define INTR_NETWORK_RING_AFIFO_DEP 8
`endif

`ifndef INTR_NETWORK_RING_ERR_INT_CNT_WIDTH
    `define INTR_NETWORK_RING_ERR_INT_CNT_WIDTH 16
`endif

`ifndef INTR_NETWORK_ENDPOINT_RING_ID
    `define INTR_NETWORK_ENDPOINT_RING_ID 0
`endif

`ifndef INTR_NETWORK_ENDPOINT_NODE_NUM
    `define INTR_NETWORK_ENDPOINT_NODE_NUM 4
`endif

`ifndef INTR_NETWORK_ENDPOINT_PLD_WIDTH
    `define INTR_NETWORK_ENDPOINT_PLD_WIDTH 40
`endif

`ifndef INTR_NETWORK_ENDPOINT_ID_WIDTH
    `define INTR_NETWORK_ENDPOINT_ID_WIDTH 8
`endif

`ifndef INTR_NETWORK_ENDPOINT_QOS_WIDTH
    `define INTR_NETWORK_ENDPOINT_QOS_WIDTH 4
`endif

`ifndef INTR_NETWORK_ENDPOINT_SINGLE_THR_WIDTH
    `define INTR_NETWORK_ENDPOINT_SINGLE_THR_WIDTH 1
`endif

`ifndef INTR_NETWORK_ENDPOINT_HAS_INIU
    `define INTR_NETWORK_ENDPOINT_HAS_INIU 1'b1
`endif

`ifndef INTR_NETWORK_ENDPOINT_HAS_TNIU
    `define INTR_NETWORK_ENDPOINT_HAS_TNIU 1'b1
`endif

`ifndef INTR_NETWORK_DUMMY_EN
    `define INTR_NETWORK_DUMMY_EN 1'b1
`endif

`ifndef INTR_NETWORK_SINK_EN
    `define INTR_NETWORK_SINK_EN 1'b1
`endif

`ifndef INTR_NETWORK_STATION_VC_BUF_DEPTH
    `define INTR_NETWORK_STATION_VC_BUF_DEPTH 32
`endif

`ifndef INTR_NETWORK_STATION_VC_AFULL_LEVEL
    `define INTR_NETWORK_STATION_VC_AFULL_LEVEL 4
`endif

`ifndef INTR_NETWORK_STATION_PLD_WIDTH
    `define INTR_NETWORK_STATION_PLD_WIDTH 128
`endif

`ifndef INTR_NETWORK_SFIFO_BUF_DEP
    `define INTR_NETWORK_SFIFO_BUF_DEP 2
`endif

`ifndef INTR_NETWORK_SFIFO_FIFO_WIDTH
    `define INTR_NETWORK_SFIFO_FIFO_WIDTH 512
`endif

`ifndef INTR_NETWORK_SFIFO_AFULL_LEVEL
    `define INTR_NETWORK_SFIFO_AFULL_LEVEL 1
`endif

`ifndef INTR_NETWORK_VCBUF_AFULL_LEVEL
    `define INTR_NETWORK_VCBUF_AFULL_LEVEL 1
`endif

`ifndef INTR_NETWORK_FLOW_CTRL_THRESHOLD
    `define INTR_NETWORK_FLOW_CTRL_THRESHOLD 16
`endif

`ifndef INTR_NETWORK_FLOW_CTRL_NODE_NUM
    `define INTR_NETWORK_FLOW_CTRL_NODE_NUM 16
`endif

`ifndef INTR_NETWORK_FLOW_CTRL_ADDR_WIDTH
    `define INTR_NETWORK_FLOW_CTRL_ADDR_WIDTH 8
`endif

`ifndef INTR_NETWORK_ROB_ENTRY_NUM
    `define INTR_NETWORK_ROB_ENTRY_NUM 32
`endif

`ifndef INTR_NETWORK_SYNC_INIT_VALUE
    `define INTR_NETWORK_SYNC_INIT_VALUE 0
`endif

`ifndef INTR_NETWORK_SYNC_WIDTH
    `define INTR_NETWORK_SYNC_WIDTH 4
`endif

`ifndef INTR_NETWORK_MEM_ADDR_WIDTH
    `define INTR_NETWORK_MEM_ADDR_WIDTH 7
`endif

`ifndef INTR_NETWORK_MEM_DATA_WIDTH
    `define INTR_NETWORK_MEM_DATA_WIDTH (`INTR_NETWORK_ENDPOINT_PLD_WIDTH + (`INTR_NETWORK_ENDPOINT_ID_WIDTH * 2) + `INTR_NETWORK_ENDPOINT_QOS_WIDTH + 2)
`endif
