module sts_soc_harden_up_wrap(
    input logic clk_harden_up_func,
    input logic rst_harden_up_func_n,
    input logic clk_dbg_timer,
    input logic rst_dbg_timer_n,
    input logic vpu_ss_tniu_sys_clk_dst,
    input logic vpu_ss_tniu_sys_rstn_dst,
    output  logic [1:0]       vpu_ss_tniu_sys_m_psel,
    output  logic [31:0]           vpu_ss_tniu_sys_m_paddr,
    input   logic [1:0]       vpu_ss_tniu_sys_m_pready,
    input   logic [63:0]    vpu_ss_tniu_sys_m_prdata,
    input   logic [1:0]       vpu_ss_tniu_sys_m_pslverr,
    output  logic [2:0]                          vpu_ss_tniu_sys_m_pprot,
    output  logic                                vpu_ss_tniu_sys_m_penable,
    output  logic                                vpu_ss_tniu_sys_m_pwrite,
    output  logic [31:0]                         vpu_ss_tniu_sys_m_pwdata,
    output  logic [3:0]                          vpu_ss_tniu_sys_m_pstrb,
    input   logic [7:0]     vpu_ss_tniu_sys_cti_event_in,
    output  logic [7:0]     vpu_ss_tniu_sys_cti_event_in_req,
    input   logic [7:0]     vpu_ss_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     vpu_ss_tniu_sys_cti_event_out,
    input   logic [7:0]     vpu_ss_tniu_sys_cti_event_out_req,
    output  logic [7:0]     vpu_ss_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     vpu_ss_tniu_sys_cti_channel_in,
    output  logic [7:0]     vpu_ss_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     vpu_ss_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     vpu_ss_tniu_sys_cti_channel_out,
    input   logic [7:0]     vpu_ss_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     vpu_ss_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       vpu_ss_tniu_sys_dbg_data_in,
    output  logic [31:0]       vpu_ss_tniu_sys_dbg_data_out,
    input   logic [63:0]  vpu_ss_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  vpu_ss_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    vpu_ss_tniu_sys_req_wptr_async,
    output  logic [3:0]    vpu_ss_tniu_sys_req_rptr_async,
    output  logic [3:0]    vpu_ss_tniu_sys_req_rptr_sync,
    input   logic [120:0]       vpu_ss_tniu_sys_req_pld_sync,
    output  logic [3:0]    vpu_ss_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    vpu_ss_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    vpu_ss_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       vpu_ss_tniu_sys_rsp_pld_sync,
    input logic camera_ss_tniu_sys_clk_dst,
    input logic camera_ss_tniu_sys_rstn_dst,
    output  logic [1:0]       camera_ss_tniu_sys_m_psel,
    output  logic [31:0]           camera_ss_tniu_sys_m_paddr,
    input   logic [1:0]       camera_ss_tniu_sys_m_pready,
    input   logic [63:0]    camera_ss_tniu_sys_m_prdata,
    input   logic [1:0]       camera_ss_tniu_sys_m_pslverr,
    output  logic [2:0]                          camera_ss_tniu_sys_m_pprot,
    output  logic                                camera_ss_tniu_sys_m_penable,
    output  logic                                camera_ss_tniu_sys_m_pwrite,
    output  logic [31:0]                         camera_ss_tniu_sys_m_pwdata,
    output  logic [3:0]                          camera_ss_tniu_sys_m_pstrb,
    input   logic [7:0]     camera_ss_tniu_sys_cti_event_in,
    output  logic [7:0]     camera_ss_tniu_sys_cti_event_in_req,
    input   logic [7:0]     camera_ss_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     camera_ss_tniu_sys_cti_event_out,
    input   logic [7:0]     camera_ss_tniu_sys_cti_event_out_req,
    output  logic [7:0]     camera_ss_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     camera_ss_tniu_sys_cti_channel_in,
    output  logic [7:0]     camera_ss_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     camera_ss_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     camera_ss_tniu_sys_cti_channel_out,
    input   logic [7:0]     camera_ss_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     camera_ss_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       camera_ss_tniu_sys_dbg_data_in,
    output  logic [31:0]       camera_ss_tniu_sys_dbg_data_out,
    input   logic [63:0]  camera_ss_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  camera_ss_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    camera_ss_tniu_sys_req_wptr_async,
    output  logic [3:0]    camera_ss_tniu_sys_req_rptr_async,
    output  logic [3:0]    camera_ss_tniu_sys_req_rptr_sync,
    input   logic [120:0]       camera_ss_tniu_sys_req_pld_sync,
    output  logic [3:0]    camera_ss_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    camera_ss_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    camera_ss_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       camera_ss_tniu_sys_rsp_pld_sync,
    input logic dspss0_tniu_sys_clk_dst,
    input logic dspss0_tniu_sys_rstn_dst,
    output  logic [1:0]       dspss0_tniu_sys_m_psel,
    output  logic [31:0]           dspss0_tniu_sys_m_paddr,
    input   logic [1:0]       dspss0_tniu_sys_m_pready,
    input   logic [63:0]    dspss0_tniu_sys_m_prdata,
    input   logic [1:0]       dspss0_tniu_sys_m_pslverr,
    output  logic [2:0]                          dspss0_tniu_sys_m_pprot,
    output  logic                                dspss0_tniu_sys_m_penable,
    output  logic                                dspss0_tniu_sys_m_pwrite,
    output  logic [31:0]                         dspss0_tniu_sys_m_pwdata,
    output  logic [3:0]                          dspss0_tniu_sys_m_pstrb,
    input   logic [7:0]     dspss0_tniu_sys_cti_event_in,
    output  logic [7:0]     dspss0_tniu_sys_cti_event_in_req,
    input   logic [7:0]     dspss0_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     dspss0_tniu_sys_cti_event_out,
    input   logic [7:0]     dspss0_tniu_sys_cti_event_out_req,
    output  logic [7:0]     dspss0_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     dspss0_tniu_sys_cti_channel_in,
    output  logic [7:0]     dspss0_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     dspss0_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     dspss0_tniu_sys_cti_channel_out,
    input   logic [7:0]     dspss0_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     dspss0_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       dspss0_tniu_sys_dbg_data_in,
    output  logic [31:0]       dspss0_tniu_sys_dbg_data_out,
    input   logic [63:0]  dspss0_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  dspss0_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    dspss0_tniu_sys_req_wptr_async,
    output  logic [3:0]    dspss0_tniu_sys_req_rptr_async,
    output  logic [3:0]    dspss0_tniu_sys_req_rptr_sync,
    input   logic [120:0]       dspss0_tniu_sys_req_pld_sync,
    output  logic [3:0]    dspss0_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    dspss0_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    dspss0_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       dspss0_tniu_sys_rsp_pld_sync,
    input logic dspss1_tniu_sys_clk_dst,
    input logic dspss1_tniu_sys_rstn_dst,
    output  logic [1:0]       dspss1_tniu_sys_m_psel,
    output  logic [31:0]           dspss1_tniu_sys_m_paddr,
    input   logic [1:0]       dspss1_tniu_sys_m_pready,
    input   logic [63:0]    dspss1_tniu_sys_m_prdata,
    input   logic [1:0]       dspss1_tniu_sys_m_pslverr,
    output  logic [2:0]                          dspss1_tniu_sys_m_pprot,
    output  logic                                dspss1_tniu_sys_m_penable,
    output  logic                                dspss1_tniu_sys_m_pwrite,
    output  logic [31:0]                         dspss1_tniu_sys_m_pwdata,
    output  logic [3:0]                          dspss1_tniu_sys_m_pstrb,
    input   logic [7:0]     dspss1_tniu_sys_cti_event_in,
    output  logic [7:0]     dspss1_tniu_sys_cti_event_in_req,
    input   logic [7:0]     dspss1_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     dspss1_tniu_sys_cti_event_out,
    input   logic [7:0]     dspss1_tniu_sys_cti_event_out_req,
    output  logic [7:0]     dspss1_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     dspss1_tniu_sys_cti_channel_in,
    output  logic [7:0]     dspss1_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     dspss1_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     dspss1_tniu_sys_cti_channel_out,
    input   logic [7:0]     dspss1_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     dspss1_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       dspss1_tniu_sys_dbg_data_in,
    output  logic [31:0]       dspss1_tniu_sys_dbg_data_out,
    input   logic [63:0]  dspss1_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  dspss1_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    dspss1_tniu_sys_req_wptr_async,
    output  logic [3:0]    dspss1_tniu_sys_req_rptr_async,
    output  logic [3:0]    dspss1_tniu_sys_req_rptr_sync,
    input   logic [120:0]       dspss1_tniu_sys_req_pld_sync,
    output  logic [3:0]    dspss1_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    dspss1_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    dspss1_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       dspss1_tniu_sys_rsp_pld_sync,
    input logic dspss2_tniu_sys_clk_dst,
    input logic dspss2_tniu_sys_rstn_dst,
    output  logic [1:0]       dspss2_tniu_sys_m_psel,
    output  logic [31:0]           dspss2_tniu_sys_m_paddr,
    input   logic [1:0]       dspss2_tniu_sys_m_pready,
    input   logic [63:0]    dspss2_tniu_sys_m_prdata,
    input   logic [1:0]       dspss2_tniu_sys_m_pslverr,
    output  logic [2:0]                          dspss2_tniu_sys_m_pprot,
    output  logic                                dspss2_tniu_sys_m_penable,
    output  logic                                dspss2_tniu_sys_m_pwrite,
    output  logic [31:0]                         dspss2_tniu_sys_m_pwdata,
    output  logic [3:0]                          dspss2_tniu_sys_m_pstrb,
    input   logic [7:0]     dspss2_tniu_sys_cti_event_in,
    output  logic [7:0]     dspss2_tniu_sys_cti_event_in_req,
    input   logic [7:0]     dspss2_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     dspss2_tniu_sys_cti_event_out,
    input   logic [7:0]     dspss2_tniu_sys_cti_event_out_req,
    output  logic [7:0]     dspss2_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     dspss2_tniu_sys_cti_channel_in,
    output  logic [7:0]     dspss2_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     dspss2_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     dspss2_tniu_sys_cti_channel_out,
    input   logic [7:0]     dspss2_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     dspss2_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       dspss2_tniu_sys_dbg_data_in,
    output  logic [31:0]       dspss2_tniu_sys_dbg_data_out,
    input   logic [63:0]  dspss2_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  dspss2_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    dspss2_tniu_sys_req_wptr_async,
    output  logic [3:0]    dspss2_tniu_sys_req_rptr_async,
    output  logic [3:0]    dspss2_tniu_sys_req_rptr_sync,
    input   logic [120:0]       dspss2_tniu_sys_req_pld_sync,
    output  logic [3:0]    dspss2_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    dspss2_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    dspss2_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       dspss2_tniu_sys_rsp_pld_sync,
    input logic dspss3_tniu_sys_clk_dst,
    input logic dspss3_tniu_sys_rstn_dst,
    output  logic [1:0]       dspss3_tniu_sys_m_psel,
    output  logic [31:0]           dspss3_tniu_sys_m_paddr,
    input   logic [1:0]       dspss3_tniu_sys_m_pready,
    input   logic [63:0]    dspss3_tniu_sys_m_prdata,
    input   logic [1:0]       dspss3_tniu_sys_m_pslverr,
    output  logic [2:0]                          dspss3_tniu_sys_m_pprot,
    output  logic                                dspss3_tniu_sys_m_penable,
    output  logic                                dspss3_tniu_sys_m_pwrite,
    output  logic [31:0]                         dspss3_tniu_sys_m_pwdata,
    output  logic [3:0]                          dspss3_tniu_sys_m_pstrb,
    input   logic [7:0]     dspss3_tniu_sys_cti_event_in,
    output  logic [7:0]     dspss3_tniu_sys_cti_event_in_req,
    input   logic [7:0]     dspss3_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     dspss3_tniu_sys_cti_event_out,
    input   logic [7:0]     dspss3_tniu_sys_cti_event_out_req,
    output  logic [7:0]     dspss3_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     dspss3_tniu_sys_cti_channel_in,
    output  logic [7:0]     dspss3_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     dspss3_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     dspss3_tniu_sys_cti_channel_out,
    input   logic [7:0]     dspss3_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     dspss3_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       dspss3_tniu_sys_dbg_data_in,
    output  logic [31:0]       dspss3_tniu_sys_dbg_data_out,
    input   logic [63:0]  dspss3_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  dspss3_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    dspss3_tniu_sys_req_wptr_async,
    output  logic [3:0]    dspss3_tniu_sys_req_rptr_async,
    output  logic [3:0]    dspss3_tniu_sys_req_rptr_sync,
    input   logic [120:0]       dspss3_tniu_sys_req_pld_sync,
    output  logic [3:0]    dspss3_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    dspss3_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    dspss3_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       dspss3_tniu_sys_rsp_pld_sync,
    input logic dspss4_tniu_sys_clk_dst,
    input logic dspss4_tniu_sys_rstn_dst,
    output  logic [1:0]       dspss4_tniu_sys_m_psel,
    output  logic [31:0]           dspss4_tniu_sys_m_paddr,
    input   logic [1:0]       dspss4_tniu_sys_m_pready,
    input   logic [63:0]    dspss4_tniu_sys_m_prdata,
    input   logic [1:0]       dspss4_tniu_sys_m_pslverr,
    output  logic [2:0]                          dspss4_tniu_sys_m_pprot,
    output  logic                                dspss4_tniu_sys_m_penable,
    output  logic                                dspss4_tniu_sys_m_pwrite,
    output  logic [31:0]                         dspss4_tniu_sys_m_pwdata,
    output  logic [3:0]                          dspss4_tniu_sys_m_pstrb,
    input   logic [7:0]     dspss4_tniu_sys_cti_event_in,
    output  logic [7:0]     dspss4_tniu_sys_cti_event_in_req,
    input   logic [7:0]     dspss4_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     dspss4_tniu_sys_cti_event_out,
    input   logic [7:0]     dspss4_tniu_sys_cti_event_out_req,
    output  logic [7:0]     dspss4_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     dspss4_tniu_sys_cti_channel_in,
    output  logic [7:0]     dspss4_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     dspss4_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     dspss4_tniu_sys_cti_channel_out,
    input   logic [7:0]     dspss4_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     dspss4_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       dspss4_tniu_sys_dbg_data_in,
    output  logic [31:0]       dspss4_tniu_sys_dbg_data_out,
    input   logic [63:0]  dspss4_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  dspss4_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    dspss4_tniu_sys_req_wptr_async,
    output  logic [3:0]    dspss4_tniu_sys_req_rptr_async,
    output  logic [3:0]    dspss4_tniu_sys_req_rptr_sync,
    input   logic [120:0]       dspss4_tniu_sys_req_pld_sync,
    output  logic [3:0]    dspss4_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    dspss4_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    dspss4_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       dspss4_tniu_sys_rsp_pld_sync,
    input logic dspss5_tniu_sys_clk_dst,
    input logic dspss5_tniu_sys_rstn_dst,
    output  logic [1:0]       dspss5_tniu_sys_m_psel,
    output  logic [31:0]           dspss5_tniu_sys_m_paddr,
    input   logic [1:0]       dspss5_tniu_sys_m_pready,
    input   logic [63:0]    dspss5_tniu_sys_m_prdata,
    input   logic [1:0]       dspss5_tniu_sys_m_pslverr,
    output  logic [2:0]                          dspss5_tniu_sys_m_pprot,
    output  logic                                dspss5_tniu_sys_m_penable,
    output  logic                                dspss5_tniu_sys_m_pwrite,
    output  logic [31:0]                         dspss5_tniu_sys_m_pwdata,
    output  logic [3:0]                          dspss5_tniu_sys_m_pstrb,
    input   logic [7:0]     dspss5_tniu_sys_cti_event_in,
    output  logic [7:0]     dspss5_tniu_sys_cti_event_in_req,
    input   logic [7:0]     dspss5_tniu_sys_cti_event_in_ack,
    output  logic [7:0]     dspss5_tniu_sys_cti_event_out,
    input   logic [7:0]     dspss5_tniu_sys_cti_event_out_req,
    output  logic [7:0]     dspss5_tniu_sys_cti_event_out_ack,
    input   logic [7:0]     dspss5_tniu_sys_cti_channel_in,
    output  logic [7:0]     dspss5_tniu_sys_cti_channel_in_req,
    input   logic [7:0]     dspss5_tniu_sys_cti_channel_in_ack,
    output  logic [7:0]     dspss5_tniu_sys_cti_channel_out,
    input   logic [7:0]     dspss5_tniu_sys_cti_channel_out_req,
    output  logic [7:0]     dspss5_tniu_sys_cti_channel_out_ack,
    input   logic [31:0]       dspss5_tniu_sys_dbg_data_in,
    output  logic [31:0]       dspss5_tniu_sys_dbg_data_out,
    input   logic [63:0]  dspss5_tniu_sys_dbg_timestamp_in,
    output  logic [63:0]  dspss5_tniu_sys_dbg_timestamp_out,
    input   logic [3:0]    dspss5_tniu_sys_req_wptr_async,
    output  logic [3:0]    dspss5_tniu_sys_req_rptr_async,
    output  logic [3:0]    dspss5_tniu_sys_req_rptr_sync,
    input   logic [120:0]       dspss5_tniu_sys_req_pld_sync,
    output  logic [3:0]    dspss5_tniu_sys_rsp_wptr_async,
    input   logic [3:0]    dspss5_tniu_sys_rsp_rptr_async,
    input   logic [3:0]    dspss5_tniu_sys_rsp_rptr_sync,
    output  logic [66:0]       dspss5_tniu_sys_rsp_pld_sync
);

sts_demo_tniu0_sts_tniu_sys u_vpu_ss_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (vpu_ss_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (vpu_ss_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (vpu_ss_tniu_sys_m_psel),
    .m_paddr          (vpu_ss_tniu_sys_m_paddr),
    .m_pready         (vpu_ss_tniu_sys_m_pready),
    .m_prdata         (vpu_ss_tniu_sys_m_prdata),
    .m_pslverr        (vpu_ss_tniu_sys_m_pslverr),
    .m_pprot          (vpu_ss_tniu_sys_m_pprot),
    .m_penable        (vpu_ss_tniu_sys_m_penable),
    .m_pwrite         (vpu_ss_tniu_sys_m_pwrite),
    .m_pwdata         (vpu_ss_tniu_sys_m_pwdata),
    .m_pstrb          (vpu_ss_tniu_sys_m_pstrb),
    .cti_event_in     (vpu_ss_tniu_sys_cti_event_in),
    .cti_event_in_req (vpu_ss_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (vpu_ss_tniu_sys_cti_event_in_ack),
    .cti_event_out    (vpu_ss_tniu_sys_cti_event_out),
    .cti_event_out_req (vpu_ss_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (vpu_ss_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (vpu_ss_tniu_sys_cti_channel_in),
    .cti_channel_in_req (vpu_ss_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (vpu_ss_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (vpu_ss_tniu_sys_cti_channel_out),
    .cti_channel_out_req (vpu_ss_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (vpu_ss_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (vpu_ss_tniu_sys_dbg_data_in),
    .dbg_data_out     (vpu_ss_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (vpu_ss_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (vpu_ss_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (vpu_ss_tniu_sys_req_pld_sync),
    .req_wptr_async   (vpu_ss_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (vpu_ss_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (vpu_ss_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (vpu_ss_tniu_sys_req_rptr_async),
    .req_rptr_sync    (vpu_ss_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (vpu_ss_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (vpu_ss_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu1_sts_tniu_sys u_camera_ss_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (camera_ss_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (camera_ss_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (camera_ss_tniu_sys_m_psel),
    .m_paddr          (camera_ss_tniu_sys_m_paddr),
    .m_pready         (camera_ss_tniu_sys_m_pready),
    .m_prdata         (camera_ss_tniu_sys_m_prdata),
    .m_pslverr        (camera_ss_tniu_sys_m_pslverr),
    .m_pprot          (camera_ss_tniu_sys_m_pprot),
    .m_penable        (camera_ss_tniu_sys_m_penable),
    .m_pwrite         (camera_ss_tniu_sys_m_pwrite),
    .m_pwdata         (camera_ss_tniu_sys_m_pwdata),
    .m_pstrb          (camera_ss_tniu_sys_m_pstrb),
    .cti_event_in     (camera_ss_tniu_sys_cti_event_in),
    .cti_event_in_req (camera_ss_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (camera_ss_tniu_sys_cti_event_in_ack),
    .cti_event_out    (camera_ss_tniu_sys_cti_event_out),
    .cti_event_out_req (camera_ss_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (camera_ss_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (camera_ss_tniu_sys_cti_channel_in),
    .cti_channel_in_req (camera_ss_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (camera_ss_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (camera_ss_tniu_sys_cti_channel_out),
    .cti_channel_out_req (camera_ss_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (camera_ss_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (camera_ss_tniu_sys_dbg_data_in),
    .dbg_data_out     (camera_ss_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (camera_ss_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (camera_ss_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (camera_ss_tniu_sys_req_pld_sync),
    .req_wptr_async   (camera_ss_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (camera_ss_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (camera_ss_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (camera_ss_tniu_sys_req_rptr_async),
    .req_rptr_sync    (camera_ss_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (camera_ss_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (camera_ss_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu2_sts_tniu_sys u_dspss0_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (dspss0_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (dspss0_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (dspss0_tniu_sys_m_psel),
    .m_paddr          (dspss0_tniu_sys_m_paddr),
    .m_pready         (dspss0_tniu_sys_m_pready),
    .m_prdata         (dspss0_tniu_sys_m_prdata),
    .m_pslverr        (dspss0_tniu_sys_m_pslverr),
    .m_pprot          (dspss0_tniu_sys_m_pprot),
    .m_penable        (dspss0_tniu_sys_m_penable),
    .m_pwrite         (dspss0_tniu_sys_m_pwrite),
    .m_pwdata         (dspss0_tniu_sys_m_pwdata),
    .m_pstrb          (dspss0_tniu_sys_m_pstrb),
    .cti_event_in     (dspss0_tniu_sys_cti_event_in),
    .cti_event_in_req (dspss0_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (dspss0_tniu_sys_cti_event_in_ack),
    .cti_event_out    (dspss0_tniu_sys_cti_event_out),
    .cti_event_out_req (dspss0_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (dspss0_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (dspss0_tniu_sys_cti_channel_in),
    .cti_channel_in_req (dspss0_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (dspss0_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (dspss0_tniu_sys_cti_channel_out),
    .cti_channel_out_req (dspss0_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (dspss0_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (dspss0_tniu_sys_dbg_data_in),
    .dbg_data_out     (dspss0_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (dspss0_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (dspss0_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (dspss0_tniu_sys_req_pld_sync),
    .req_wptr_async   (dspss0_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (dspss0_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (dspss0_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (dspss0_tniu_sys_req_rptr_async),
    .req_rptr_sync    (dspss0_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (dspss0_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (dspss0_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu3_sts_tniu_sys u_dspss1_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (dspss1_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (dspss1_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (dspss1_tniu_sys_m_psel),
    .m_paddr          (dspss1_tniu_sys_m_paddr),
    .m_pready         (dspss1_tniu_sys_m_pready),
    .m_prdata         (dspss1_tniu_sys_m_prdata),
    .m_pslverr        (dspss1_tniu_sys_m_pslverr),
    .m_pprot          (dspss1_tniu_sys_m_pprot),
    .m_penable        (dspss1_tniu_sys_m_penable),
    .m_pwrite         (dspss1_tniu_sys_m_pwrite),
    .m_pwdata         (dspss1_tniu_sys_m_pwdata),
    .m_pstrb          (dspss1_tniu_sys_m_pstrb),
    .cti_event_in     (dspss1_tniu_sys_cti_event_in),
    .cti_event_in_req (dspss1_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (dspss1_tniu_sys_cti_event_in_ack),
    .cti_event_out    (dspss1_tniu_sys_cti_event_out),
    .cti_event_out_req (dspss1_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (dspss1_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (dspss1_tniu_sys_cti_channel_in),
    .cti_channel_in_req (dspss1_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (dspss1_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (dspss1_tniu_sys_cti_channel_out),
    .cti_channel_out_req (dspss1_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (dspss1_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (dspss1_tniu_sys_dbg_data_in),
    .dbg_data_out     (dspss1_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (dspss1_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (dspss1_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (dspss1_tniu_sys_req_pld_sync),
    .req_wptr_async   (dspss1_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (dspss1_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (dspss1_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (dspss1_tniu_sys_req_rptr_async),
    .req_rptr_sync    (dspss1_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (dspss1_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (dspss1_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu0_sts_tniu_sys u_dspss2_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (dspss2_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (dspss2_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (dspss2_tniu_sys_m_psel),
    .m_paddr          (dspss2_tniu_sys_m_paddr),
    .m_pready         (dspss2_tniu_sys_m_pready),
    .m_prdata         (dspss2_tniu_sys_m_prdata),
    .m_pslverr        (dspss2_tniu_sys_m_pslverr),
    .m_pprot          (dspss2_tniu_sys_m_pprot),
    .m_penable        (dspss2_tniu_sys_m_penable),
    .m_pwrite         (dspss2_tniu_sys_m_pwrite),
    .m_pwdata         (dspss2_tniu_sys_m_pwdata),
    .m_pstrb          (dspss2_tniu_sys_m_pstrb),
    .cti_event_in     (dspss2_tniu_sys_cti_event_in),
    .cti_event_in_req (dspss2_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (dspss2_tniu_sys_cti_event_in_ack),
    .cti_event_out    (dspss2_tniu_sys_cti_event_out),
    .cti_event_out_req (dspss2_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (dspss2_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (dspss2_tniu_sys_cti_channel_in),
    .cti_channel_in_req (dspss2_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (dspss2_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (dspss2_tniu_sys_cti_channel_out),
    .cti_channel_out_req (dspss2_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (dspss2_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (dspss2_tniu_sys_dbg_data_in),
    .dbg_data_out     (dspss2_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (dspss2_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (dspss2_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (dspss2_tniu_sys_req_pld_sync),
    .req_wptr_async   (dspss2_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (dspss2_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (dspss2_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (dspss2_tniu_sys_req_rptr_async),
    .req_rptr_sync    (dspss2_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (dspss2_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (dspss2_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu1_sts_tniu_sys u_dspss3_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (dspss3_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (dspss3_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (dspss3_tniu_sys_m_psel),
    .m_paddr          (dspss3_tniu_sys_m_paddr),
    .m_pready         (dspss3_tniu_sys_m_pready),
    .m_prdata         (dspss3_tniu_sys_m_prdata),
    .m_pslverr        (dspss3_tniu_sys_m_pslverr),
    .m_pprot          (dspss3_tniu_sys_m_pprot),
    .m_penable        (dspss3_tniu_sys_m_penable),
    .m_pwrite         (dspss3_tniu_sys_m_pwrite),
    .m_pwdata         (dspss3_tniu_sys_m_pwdata),
    .m_pstrb          (dspss3_tniu_sys_m_pstrb),
    .cti_event_in     (dspss3_tniu_sys_cti_event_in),
    .cti_event_in_req (dspss3_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (dspss3_tniu_sys_cti_event_in_ack),
    .cti_event_out    (dspss3_tniu_sys_cti_event_out),
    .cti_event_out_req (dspss3_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (dspss3_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (dspss3_tniu_sys_cti_channel_in),
    .cti_channel_in_req (dspss3_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (dspss3_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (dspss3_tniu_sys_cti_channel_out),
    .cti_channel_out_req (dspss3_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (dspss3_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (dspss3_tniu_sys_dbg_data_in),
    .dbg_data_out     (dspss3_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (dspss3_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (dspss3_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (dspss3_tniu_sys_req_pld_sync),
    .req_wptr_async   (dspss3_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (dspss3_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (dspss3_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (dspss3_tniu_sys_req_rptr_async),
    .req_rptr_sync    (dspss3_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (dspss3_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (dspss3_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu2_sts_tniu_sys u_dspss4_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (dspss4_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (dspss4_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (dspss4_tniu_sys_m_psel),
    .m_paddr          (dspss4_tniu_sys_m_paddr),
    .m_pready         (dspss4_tniu_sys_m_pready),
    .m_prdata         (dspss4_tniu_sys_m_prdata),
    .m_pslverr        (dspss4_tniu_sys_m_pslverr),
    .m_pprot          (dspss4_tniu_sys_m_pprot),
    .m_penable        (dspss4_tniu_sys_m_penable),
    .m_pwrite         (dspss4_tniu_sys_m_pwrite),
    .m_pwdata         (dspss4_tniu_sys_m_pwdata),
    .m_pstrb          (dspss4_tniu_sys_m_pstrb),
    .cti_event_in     (dspss4_tniu_sys_cti_event_in),
    .cti_event_in_req (dspss4_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (dspss4_tniu_sys_cti_event_in_ack),
    .cti_event_out    (dspss4_tniu_sys_cti_event_out),
    .cti_event_out_req (dspss4_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (dspss4_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (dspss4_tniu_sys_cti_channel_in),
    .cti_channel_in_req (dspss4_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (dspss4_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (dspss4_tniu_sys_cti_channel_out),
    .cti_channel_out_req (dspss4_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (dspss4_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (dspss4_tniu_sys_dbg_data_in),
    .dbg_data_out     (dspss4_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (dspss4_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (dspss4_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (dspss4_tniu_sys_req_pld_sync),
    .req_wptr_async   (dspss4_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (dspss4_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (dspss4_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (dspss4_tniu_sys_req_rptr_async),
    .req_rptr_sync    (dspss4_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (dspss4_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (dspss4_tniu_sys_rsp_wptr_async)
 );

sts_demo_tniu3_sts_tniu_sys u_dspss5_tniu_sys (
    .clk_src       (clk_harden_up_func),
    .clk_dst       (dspss5_tniu_sys_clk_dst),
    .clk_dbg_timer (clk_dbg_timer),
    .rstn_src      (rst_harden_up_func_n),
    .rstn_dst      (dspss5_tniu_sys_rstn_dst),
    .rstn_dbg_timer(rst_dbg_timer_n),
    .m_psel           (dspss5_tniu_sys_m_psel),
    .m_paddr          (dspss5_tniu_sys_m_paddr),
    .m_pready         (dspss5_tniu_sys_m_pready),
    .m_prdata         (dspss5_tniu_sys_m_prdata),
    .m_pslverr        (dspss5_tniu_sys_m_pslverr),
    .m_pprot          (dspss5_tniu_sys_m_pprot),
    .m_penable        (dspss5_tniu_sys_m_penable),
    .m_pwrite         (dspss5_tniu_sys_m_pwrite),
    .m_pwdata         (dspss5_tniu_sys_m_pwdata),
    .m_pstrb          (dspss5_tniu_sys_m_pstrb),
    .cti_event_in     (dspss5_tniu_sys_cti_event_in),
    .cti_event_in_req (dspss5_tniu_sys_cti_event_in_req),
    .cti_event_in_ack (dspss5_tniu_sys_cti_event_in_ack),
    .cti_event_out    (dspss5_tniu_sys_cti_event_out),
    .cti_event_out_req (dspss5_tniu_sys_cti_event_out_req),
    .cti_event_out_ack (dspss5_tniu_sys_cti_event_out_ack),
    .cti_channel_in   (dspss5_tniu_sys_cti_channel_in),
    .cti_channel_in_req (dspss5_tniu_sys_cti_channel_in_req),
    .cti_channel_in_ack (dspss5_tniu_sys_cti_channel_in_ack),
    .cti_channel_out  (dspss5_tniu_sys_cti_channel_out),
    .cti_channel_out_req (dspss5_tniu_sys_cti_channel_out_req),
    .cti_channel_out_ack (dspss5_tniu_sys_cti_channel_out_ack),
    .dbg_data_in      (dspss5_tniu_sys_dbg_data_in),
    .dbg_data_out     (dspss5_tniu_sys_dbg_data_out),
    .dbg_timestamp_in (dspss5_tniu_sys_dbg_timestamp_in),
    .dbg_timestamp_out (dspss5_tniu_sys_dbg_timestamp_out),
    .req_pld_sync     (dspss5_tniu_sys_req_pld_sync),
    .req_wptr_async   (dspss5_tniu_sys_req_wptr_async),
    .rsp_rptr_async   (dspss5_tniu_sys_rsp_rptr_async),
    .rsp_rptr_sync    (dspss5_tniu_sys_rsp_rptr_sync),
    .req_rptr_async   (dspss5_tniu_sys_req_rptr_async),
    .req_rptr_sync    (dspss5_tniu_sys_req_rptr_sync),
    .rsp_pld_sync     (dspss5_tniu_sys_rsp_pld_sync),
    .rsp_wptr_async   (dspss5_tniu_sys_rsp_wptr_async)
 );

endmodule
