package ddr3_iniu_interrupt_iniu_pkg;

    //===========================================================================
    // user defined parameters
    //===========================================================================
    localparam integer unsigned OVERFLOW_TGT_ID         = 0;
    localparam integer unsigned OVERFLOW_TGT_INTR_ID    = 0;

    //===========================================================================
    // event recorder parameters
    //===========================================================================
    localparam integer unsigned INTERRUPT_MAX_NUM       = 4096;
    localparam integer unsigned INTERRUPT_MAXNUM_WIDTH  = $clog2(INTERRUPT_MAX_NUM);

    localparam integer unsigned NIU_ID_WIDTH        = 8;
    localparam integer unsigned INTR_ID_WIDTH       = 12;
    localparam integer unsigned INTR_LUT_BASE_ADDR       = 32'h4000;
    localparam integer unsigned INTR_PULSE_MODE_BASE_ADDR = 32'h8000;

    localparam integer unsigned EVENT_COUNT_MAX     = 16;
    localparam integer unsigned EVENT_COUNT_WIDTH   = $clog2(EVENT_COUNT_MAX + 1);

    localparam integer unsigned ARB_LEVEL_0         = 16;       //16
    localparam integer unsigned ARB_LEVEL_1         = 512;      //32
    localparam integer unsigned ARB_LEVEL_2         = 4096;     //8

    localparam integer unsigned IDLE_DELAY_MAX      = 8;

    localparam integer unsigned EVENT_REQ     = 0;
    localparam integer unsigned APB_REQ       = 1;
    typedef struct packed{
        logic                               toggle_flag;
        logic                               overflow;
        logic [INTERRUPT_MAXNUM_WIDTH-1:0]  intr_addr;

    } recorder_pkg;

    typedef struct packed{
        logic                                   srcid;
        logic [INTERRUPT_MAXNUM_WIDTH-1:0]      addr;
        logic                                   toggle_flag;
        logic                                   overflow;
    } event_apb_arb_pkg;

    typedef struct packed{
        logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        // logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
    } lut_pkg;

    typedef struct packed{
        logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        // logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
        logic [$clog2($bits(lut_pkg))-1:0] ecc; // used to indicate the interrupt address
    } ecc_pkg;



endpackage
