//[UHDL]Content Start [md5:befd97d92d2442e9608138dfd6c88388]
module atb_up_harden (
	output         dsp_ss0_top_node_m_chan_porting_m_afready            ,
	input          dsp_ss0_top_node_m_chan_porting_m_afvalid            ,
	output [3:0]   dsp_ss0_top_node_m_chan_porting_m_atbytes            ,
	output [127:0] dsp_ss0_top_node_m_chan_porting_m_atdata             ,
	output [6:0]   dsp_ss0_top_node_m_chan_porting_m_atid               ,
	input          dsp_ss0_top_node_m_chan_porting_m_atready            ,
	output         dsp_ss0_top_node_m_chan_porting_m_atvalid            ,
	output         dsp_ss0_top_node_m_chan_porting_m_atwakeup           ,
	input          dsp_ss0_top_node_m_chan_porting_m_syncreq            ,
	output         dsp_ss0_top_node_sync_ctrl_porting_flush_req_level   ,
	output         dsp_ss0_top_node_sync_ctrl_porting_syncreq_level     ,
	input  [12:0]  dsp_ss0_top_node_lp_afifo_rx_porting_afifo_mst_rx_req,
	output [12:0]  dsp_ss0_top_node_lp_afifo_tx_porting_afifo_mst_tx_req,
	input  [142:0] dsp_ss0_top_node_async_fifo_porting_pld_sync         ,
	output [15:0]  dsp_ss0_top_node_async_fifo_porting_rptr_async       ,
	output [15:0]  dsp_ss0_top_node_async_fifo_porting_rptr_sync        ,
	input  [15:0]  dsp_ss0_top_node_async_fifo_porting_wptr_async       ,
	input  [12:0]  dsp_ss0_top_node_lp_rx_porting_lw_rx_req             ,
	output [12:0]  dsp_ss0_top_node_lp_tx_porting_lw_tx_req             ,
	input  [9:0]   dsp_ss0_top_node_timeout_val_porting_timeout_val     ,
	output         dsp_ss1_top_node_m_chan_porting_m_afready            ,
	input          dsp_ss1_top_node_m_chan_porting_m_afvalid            ,
	output [3:0]   dsp_ss1_top_node_m_chan_porting_m_atbytes            ,
	output [127:0] dsp_ss1_top_node_m_chan_porting_m_atdata             ,
	output [6:0]   dsp_ss1_top_node_m_chan_porting_m_atid               ,
	input          dsp_ss1_top_node_m_chan_porting_m_atready            ,
	output         dsp_ss1_top_node_m_chan_porting_m_atvalid            ,
	output         dsp_ss1_top_node_m_chan_porting_m_atwakeup           ,
	input          dsp_ss1_top_node_m_chan_porting_m_syncreq            ,
	output         dsp_ss1_top_node_sync_ctrl_porting_flush_req_level   ,
	output         dsp_ss1_top_node_sync_ctrl_porting_syncreq_level     ,
	input  [12:0]  dsp_ss1_top_node_lp_afifo_rx_porting_afifo_mst_rx_req,
	output [12:0]  dsp_ss1_top_node_lp_afifo_tx_porting_afifo_mst_tx_req,
	input  [142:0] dsp_ss1_top_node_async_fifo_porting_pld_sync         ,
	output [15:0]  dsp_ss1_top_node_async_fifo_porting_rptr_async       ,
	output [15:0]  dsp_ss1_top_node_async_fifo_porting_rptr_sync        ,
	input  [15:0]  dsp_ss1_top_node_async_fifo_porting_wptr_async       ,
	input  [12:0]  dsp_ss1_top_node_lp_rx_porting_lw_rx_req             ,
	output [12:0]  dsp_ss1_top_node_lp_tx_porting_lw_tx_req             ,
	input  [9:0]   dsp_ss1_top_node_timeout_val_porting_timeout_val     ,
	output         dsp_ss2_top_node_m_chan_porting_m_afready            ,
	input          dsp_ss2_top_node_m_chan_porting_m_afvalid            ,
	output [3:0]   dsp_ss2_top_node_m_chan_porting_m_atbytes            ,
	output [127:0] dsp_ss2_top_node_m_chan_porting_m_atdata             ,
	output [6:0]   dsp_ss2_top_node_m_chan_porting_m_atid               ,
	input          dsp_ss2_top_node_m_chan_porting_m_atready            ,
	output         dsp_ss2_top_node_m_chan_porting_m_atvalid            ,
	output         dsp_ss2_top_node_m_chan_porting_m_atwakeup           ,
	input          dsp_ss2_top_node_m_chan_porting_m_syncreq            ,
	output         dsp_ss2_top_node_sync_ctrl_porting_flush_req_level   ,
	output         dsp_ss2_top_node_sync_ctrl_porting_syncreq_level     ,
	input  [12:0]  dsp_ss2_top_node_lp_afifo_rx_porting_afifo_mst_rx_req,
	output [12:0]  dsp_ss2_top_node_lp_afifo_tx_porting_afifo_mst_tx_req,
	input  [142:0] dsp_ss2_top_node_async_fifo_porting_pld_sync         ,
	output [15:0]  dsp_ss2_top_node_async_fifo_porting_rptr_async       ,
	output [15:0]  dsp_ss2_top_node_async_fifo_porting_rptr_sync        ,
	input  [15:0]  dsp_ss2_top_node_async_fifo_porting_wptr_async       ,
	input  [12:0]  dsp_ss2_top_node_lp_rx_porting_lw_rx_req             ,
	output [12:0]  dsp_ss2_top_node_lp_tx_porting_lw_tx_req             ,
	input  [9:0]   dsp_ss2_top_node_timeout_val_porting_timeout_val     ,
	output         dsp_ss3_top_node_m_chan_porting_m_afready            ,
	input          dsp_ss3_top_node_m_chan_porting_m_afvalid            ,
	output [3:0]   dsp_ss3_top_node_m_chan_porting_m_atbytes            ,
	output [127:0] dsp_ss3_top_node_m_chan_porting_m_atdata             ,
	output [6:0]   dsp_ss3_top_node_m_chan_porting_m_atid               ,
	input          dsp_ss3_top_node_m_chan_porting_m_atready            ,
	output         dsp_ss3_top_node_m_chan_porting_m_atvalid            ,
	output         dsp_ss3_top_node_m_chan_porting_m_atwakeup           ,
	input          dsp_ss3_top_node_m_chan_porting_m_syncreq            ,
	output         dsp_ss3_top_node_sync_ctrl_porting_flush_req_level   ,
	output         dsp_ss3_top_node_sync_ctrl_porting_syncreq_level     ,
	input  [12:0]  dsp_ss3_top_node_lp_afifo_rx_porting_afifo_mst_rx_req,
	output [12:0]  dsp_ss3_top_node_lp_afifo_tx_porting_afifo_mst_tx_req,
	input  [142:0] dsp_ss3_top_node_async_fifo_porting_pld_sync         ,
	output [15:0]  dsp_ss3_top_node_async_fifo_porting_rptr_async       ,
	output [15:0]  dsp_ss3_top_node_async_fifo_porting_rptr_sync        ,
	input  [15:0]  dsp_ss3_top_node_async_fifo_porting_wptr_async       ,
	input  [12:0]  dsp_ss3_top_node_lp_rx_porting_lw_rx_req             ,
	output [12:0]  dsp_ss3_top_node_lp_tx_porting_lw_tx_req             ,
	input  [9:0]   dsp_ss3_top_node_timeout_val_porting_timeout_val     ,
	output         dsp_ss4_top_node_m_chan_porting_m_afready            ,
	input          dsp_ss4_top_node_m_chan_porting_m_afvalid            ,
	output [3:0]   dsp_ss4_top_node_m_chan_porting_m_atbytes            ,
	output [127:0] dsp_ss4_top_node_m_chan_porting_m_atdata             ,
	output [6:0]   dsp_ss4_top_node_m_chan_porting_m_atid               ,
	input          dsp_ss4_top_node_m_chan_porting_m_atready            ,
	output         dsp_ss4_top_node_m_chan_porting_m_atvalid            ,
	output         dsp_ss4_top_node_m_chan_porting_m_atwakeup           ,
	input          dsp_ss4_top_node_m_chan_porting_m_syncreq            ,
	output         dsp_ss4_top_node_sync_ctrl_porting_flush_req_level   ,
	output         dsp_ss4_top_node_sync_ctrl_porting_syncreq_level     ,
	input  [12:0]  dsp_ss4_top_node_lp_afifo_rx_porting_afifo_mst_rx_req,
	output [12:0]  dsp_ss4_top_node_lp_afifo_tx_porting_afifo_mst_tx_req,
	input  [142:0] dsp_ss4_top_node_async_fifo_porting_pld_sync         ,
	output [15:0]  dsp_ss4_top_node_async_fifo_porting_rptr_async       ,
	output [15:0]  dsp_ss4_top_node_async_fifo_porting_rptr_sync        ,
	input  [15:0]  dsp_ss4_top_node_async_fifo_porting_wptr_async       ,
	input  [12:0]  dsp_ss4_top_node_lp_rx_porting_lw_rx_req             ,
	output [12:0]  dsp_ss4_top_node_lp_tx_porting_lw_tx_req             ,
	input  [9:0]   dsp_ss4_top_node_timeout_val_porting_timeout_val     ,
	output         dsp_ss5_top_node_m_chan_porting_m_afready            ,
	input          dsp_ss5_top_node_m_chan_porting_m_afvalid            ,
	output [3:0]   dsp_ss5_top_node_m_chan_porting_m_atbytes            ,
	output [127:0] dsp_ss5_top_node_m_chan_porting_m_atdata             ,
	output [6:0]   dsp_ss5_top_node_m_chan_porting_m_atid               ,
	input          dsp_ss5_top_node_m_chan_porting_m_atready            ,
	output         dsp_ss5_top_node_m_chan_porting_m_atvalid            ,
	output         dsp_ss5_top_node_m_chan_porting_m_atwakeup           ,
	input          dsp_ss5_top_node_m_chan_porting_m_syncreq            ,
	output         dsp_ss5_top_node_sync_ctrl_porting_flush_req_level   ,
	output         dsp_ss5_top_node_sync_ctrl_porting_syncreq_level     ,
	input  [12:0]  dsp_ss5_top_node_lp_afifo_rx_porting_afifo_mst_rx_req,
	output [12:0]  dsp_ss5_top_node_lp_afifo_tx_porting_afifo_mst_tx_req,
	input  [142:0] dsp_ss5_top_node_async_fifo_porting_pld_sync         ,
	output [15:0]  dsp_ss5_top_node_async_fifo_porting_rptr_async       ,
	output [15:0]  dsp_ss5_top_node_async_fifo_porting_rptr_sync        ,
	input  [15:0]  dsp_ss5_top_node_async_fifo_porting_wptr_async       ,
	input  [12:0]  dsp_ss5_top_node_lp_rx_porting_lw_rx_req             ,
	output [12:0]  dsp_ss5_top_node_lp_tx_porting_lw_tx_req             ,
	input  [9:0]   dsp_ss5_top_node_timeout_val_porting_timeout_val     ,
	input  [1:0]   left_funnel_node_atvalids_porting_atvalids           ,
	input  [1:0]   left_funnel_node_afreadys_porting_afreadys           ,
	input  [13:0]  left_funnel_node_atids_porting_atids                 ,
	input  [255:0] left_funnel_node_atdatas_porting_atdatas             ,
	input  [7:0]   left_funnel_node_atbytess_porting_atbytess           ,
	input          left_funnel_node_atreadym_porting_atreadym           ,
	input          left_funnel_node_afvalidm_porting_afvalidm           ,
	input          left_funnel_node_syncreqm_porting_syncreqm           ,
	output         left_funnel_node_atvalidm_porting_atvalidm           ,
	output         left_funnel_node_afreadym_porting_afreadym           ,
	output [6:0]   left_funnel_node_atidm_porting_atidm                 ,
	output [127:0] left_funnel_node_atdatam_porting_atdatam             ,
	output [3:0]   left_funnel_node_atbytesm_porting_atbytesm           ,
	output [1:0]   left_funnel_node_atreadys_porting_atreadys           ,
	output [1:0]   left_funnel_node_afvalids_porting_afvalids           ,
	output [1:0]   left_funnel_node_syncreqs_porting_syncreqs           ,
	input          left_funnel_node_pclkendbg_porting_pclkendbg         ,
	input          left_funnel_node_pseldbg_porting_pseldbg             ,
	input          left_funnel_node_penabledbg_porting_penabledbg       ,
	input          left_funnel_node_pwritedbg_porting_pwritedbg         ,
	input          left_funnel_node_paddrdbg31_porting_paddrdbg31       ,
	input  [9:0]   left_funnel_node_paddrdbg_porting_paddrdbg           ,
	input  [31:0]  left_funnel_node_pwdatadbg_porting_pwdatadbg         ,
	output         left_funnel_node_preadydbg_porting_preadydbg         ,
	output         left_funnel_node_pslverrdbg_porting_pslverrdbg       ,
	output [31:0]  left_funnel_node_prdatadbg_porting_prdatadbg         ,
	input          async_bridge_slv_node_s_chan_porting_s_afready       ,
	output         async_bridge_slv_node_s_chan_porting_s_afvalid       ,
	input  [2:0]   async_bridge_slv_node_s_chan_porting_s_atbytes       ,
	input  [63:0]  async_bridge_slv_node_s_chan_porting_s_atdata        ,
	input  [6:0]   async_bridge_slv_node_s_chan_porting_s_atid          ,
	output         async_bridge_slv_node_s_chan_porting_s_atready       ,
	input          async_bridge_slv_node_s_chan_porting_s_atvalid       ,
	input          async_bridge_slv_node_s_chan_porting_s_atwakeup      ,
	output         async_bridge_slv_node_s_chan_porting_s_syncreq       ,
	input          async_bridge_slv_side_clk_dst_porting                ,
	input          async_bridge_slv_side_rst_dst_n_porting              );

	//Wire define for this module.

	//Wire define for sub module.

	//Wire define for Inout.

	//Wire sub module connect to this module and inter module connect.

	//Wire this module connect to sub module.

	//module inst.
	atb_iniu_noc dsp_ss0_top_wrap (
		.clk_atb_m(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_m(async_bridge_slv_side_rst_dst_n_porting),
		.m_atvalid(dsp_ss0_top_node_m_chan_porting_m_atvalid),
		.m_atready(dsp_ss0_top_node_m_chan_porting_m_atready),
		.m_atbytes(dsp_ss0_top_node_m_chan_porting_m_atbytes),
		.m_atdata(dsp_ss0_top_node_m_chan_porting_m_atdata),
		.m_atid(dsp_ss0_top_node_m_chan_porting_m_atid),
		.m_afvalid(dsp_ss0_top_node_m_chan_porting_m_afvalid),
		.m_afready(dsp_ss0_top_node_m_chan_porting_m_afready),
		.m_syncreq(dsp_ss0_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(dsp_ss0_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(dsp_ss0_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(dsp_ss0_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(dsp_ss0_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(dsp_ss0_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(dsp_ss0_top_node_async_fifo_porting_wptr_async),
		.rptr_async(dsp_ss0_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(dsp_ss0_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(dsp_ss0_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(dsp_ss0_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(dsp_ss0_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(dsp_ss0_top_node_timeout_val_porting_timeout_val));
	atb_iniu_noc dsp_ss1_top_wrap (
		.clk_atb_m(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_m(async_bridge_slv_side_rst_dst_n_porting),
		.m_atvalid(dsp_ss1_top_node_m_chan_porting_m_atvalid),
		.m_atready(dsp_ss1_top_node_m_chan_porting_m_atready),
		.m_atbytes(dsp_ss1_top_node_m_chan_porting_m_atbytes),
		.m_atdata(dsp_ss1_top_node_m_chan_porting_m_atdata),
		.m_atid(dsp_ss1_top_node_m_chan_porting_m_atid),
		.m_afvalid(dsp_ss1_top_node_m_chan_porting_m_afvalid),
		.m_afready(dsp_ss1_top_node_m_chan_porting_m_afready),
		.m_syncreq(dsp_ss1_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(dsp_ss1_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(dsp_ss1_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(dsp_ss1_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(dsp_ss1_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(dsp_ss1_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(dsp_ss1_top_node_async_fifo_porting_wptr_async),
		.rptr_async(dsp_ss1_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(dsp_ss1_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(dsp_ss1_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(dsp_ss1_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(dsp_ss1_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(dsp_ss1_top_node_timeout_val_porting_timeout_val));
	atb_iniu_noc dsp_ss2_top_wrap (
		.clk_atb_m(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_m(async_bridge_slv_side_rst_dst_n_porting),
		.m_atvalid(dsp_ss2_top_node_m_chan_porting_m_atvalid),
		.m_atready(dsp_ss2_top_node_m_chan_porting_m_atready),
		.m_atbytes(dsp_ss2_top_node_m_chan_porting_m_atbytes),
		.m_atdata(dsp_ss2_top_node_m_chan_porting_m_atdata),
		.m_atid(dsp_ss2_top_node_m_chan_porting_m_atid),
		.m_afvalid(dsp_ss2_top_node_m_chan_porting_m_afvalid),
		.m_afready(dsp_ss2_top_node_m_chan_porting_m_afready),
		.m_syncreq(dsp_ss2_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(dsp_ss2_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(dsp_ss2_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(dsp_ss2_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(dsp_ss2_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(dsp_ss2_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(dsp_ss2_top_node_async_fifo_porting_wptr_async),
		.rptr_async(dsp_ss2_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(dsp_ss2_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(dsp_ss2_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(dsp_ss2_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(dsp_ss2_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(dsp_ss2_top_node_timeout_val_porting_timeout_val));
	atb_iniu_noc dsp_ss3_top_wrap (
		.clk_atb_m(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_m(async_bridge_slv_side_rst_dst_n_porting),
		.m_atvalid(dsp_ss3_top_node_m_chan_porting_m_atvalid),
		.m_atready(dsp_ss3_top_node_m_chan_porting_m_atready),
		.m_atbytes(dsp_ss3_top_node_m_chan_porting_m_atbytes),
		.m_atdata(dsp_ss3_top_node_m_chan_porting_m_atdata),
		.m_atid(dsp_ss3_top_node_m_chan_porting_m_atid),
		.m_afvalid(dsp_ss3_top_node_m_chan_porting_m_afvalid),
		.m_afready(dsp_ss3_top_node_m_chan_porting_m_afready),
		.m_syncreq(dsp_ss3_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(dsp_ss3_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(dsp_ss3_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(dsp_ss3_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(dsp_ss3_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(dsp_ss3_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(dsp_ss3_top_node_async_fifo_porting_wptr_async),
		.rptr_async(dsp_ss3_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(dsp_ss3_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(dsp_ss3_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(dsp_ss3_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(dsp_ss3_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(dsp_ss3_top_node_timeout_val_porting_timeout_val));
	atb_iniu_noc dsp_ss4_top_wrap (
		.clk_atb_m(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_m(async_bridge_slv_side_rst_dst_n_porting),
		.m_atvalid(dsp_ss4_top_node_m_chan_porting_m_atvalid),
		.m_atready(dsp_ss4_top_node_m_chan_porting_m_atready),
		.m_atbytes(dsp_ss4_top_node_m_chan_porting_m_atbytes),
		.m_atdata(dsp_ss4_top_node_m_chan_porting_m_atdata),
		.m_atid(dsp_ss4_top_node_m_chan_porting_m_atid),
		.m_afvalid(dsp_ss4_top_node_m_chan_porting_m_afvalid),
		.m_afready(dsp_ss4_top_node_m_chan_porting_m_afready),
		.m_syncreq(dsp_ss4_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(dsp_ss4_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(dsp_ss4_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(dsp_ss4_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(dsp_ss4_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(dsp_ss4_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(dsp_ss4_top_node_async_fifo_porting_wptr_async),
		.rptr_async(dsp_ss4_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(dsp_ss4_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(dsp_ss4_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(dsp_ss4_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(dsp_ss4_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(dsp_ss4_top_node_timeout_val_porting_timeout_val));
	atb_iniu_noc dsp_ss5_top_wrap (
		.clk_atb_m(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_m(async_bridge_slv_side_rst_dst_n_porting),
		.m_atvalid(dsp_ss5_top_node_m_chan_porting_m_atvalid),
		.m_atready(dsp_ss5_top_node_m_chan_porting_m_atready),
		.m_atbytes(dsp_ss5_top_node_m_chan_porting_m_atbytes),
		.m_atdata(dsp_ss5_top_node_m_chan_porting_m_atdata),
		.m_atid(dsp_ss5_top_node_m_chan_porting_m_atid),
		.m_afvalid(dsp_ss5_top_node_m_chan_porting_m_afvalid),
		.m_afready(dsp_ss5_top_node_m_chan_porting_m_afready),
		.m_syncreq(dsp_ss5_top_node_m_chan_porting_m_syncreq),
		.m_atwakeup(dsp_ss5_top_node_m_chan_porting_m_atwakeup),
		.syncreq_level(dsp_ss5_top_node_sync_ctrl_porting_syncreq_level),
		.flush_req_level(dsp_ss5_top_node_sync_ctrl_porting_flush_req_level),
		.afifo_mst_rx_req(dsp_ss5_top_node_lp_afifo_rx_porting_afifo_mst_rx_req),
		.afifo_mst_tx_req(dsp_ss5_top_node_lp_afifo_tx_porting_afifo_mst_tx_req),
		.wptr_async(dsp_ss5_top_node_async_fifo_porting_wptr_async),
		.rptr_async(dsp_ss5_top_node_async_fifo_porting_rptr_async),
		.rptr_sync(dsp_ss5_top_node_async_fifo_porting_rptr_sync),
		.pld_sync(dsp_ss5_top_node_async_fifo_porting_pld_sync),
		.lw_rx_req(dsp_ss5_top_node_lp_rx_porting_lw_rx_req),
		.lw_tx_req(dsp_ss5_top_node_lp_tx_porting_lw_tx_req),
		.timeout_val(dsp_ss5_top_node_timeout_val_porting_timeout_val));
	atb_funnel dsp_funnel_6ch (
		.clk(async_bridge_slv_side_clk_dst_porting),
		.resetn(async_bridge_slv_side_rst_dst_n_porting),
		.pclkendbg(left_funnel_node_pclkendbg_porting_pclkendbg),
		.pseldbg(left_funnel_node_pseldbg_porting_pseldbg),
		.penabledbg(left_funnel_node_penabledbg_porting_penabledbg),
		.pwritedbg(left_funnel_node_pwritedbg_porting_pwritedbg),
		.paddrdbg31(left_funnel_node_paddrdbg31_porting_paddrdbg31),
		.paddrdbg(left_funnel_node_paddrdbg_porting_paddrdbg),
		.pwdatadbg(left_funnel_node_pwdatadbg_porting_pwdatadbg),
		.atvalids(left_funnel_node_atvalids_porting_atvalids),
		.afreadys(left_funnel_node_afreadys_porting_afreadys),
		.atids(left_funnel_node_atids_porting_atids),
		.atdatas(left_funnel_node_atdatas_porting_atdatas),
		.atbytess(left_funnel_node_atbytess_porting_atbytess),
		.atreadym(left_funnel_node_atreadym_porting_atreadym),
		.afvalidm(left_funnel_node_afvalidm_porting_afvalidm),
		.syncreqm(left_funnel_node_syncreqm_porting_syncreqm),
		.preadydbg(left_funnel_node_preadydbg_porting_preadydbg),
		.pslverrdbg(left_funnel_node_pslverrdbg_porting_pslverrdbg),
		.prdatadbg(left_funnel_node_prdatadbg_porting_prdatadbg),
		.atvalidm(left_funnel_node_atvalidm_porting_atvalidm),
		.afreadym(left_funnel_node_afreadym_porting_afreadym),
		.atidm(left_funnel_node_atidm_porting_atidm),
		.atdatam(left_funnel_node_atdatam_porting_atdatam),
		.atbytesm(left_funnel_node_atbytesm_porting_atbytesm),
		.atreadys(left_funnel_node_atreadys_porting_atreadys),
		.afvalids(left_funnel_node_afvalids_porting_afvalids),
		.syncreqs(left_funnel_node_syncreqs_porting_syncreqs));
	atb_async_bridge_top async_bridge_slv_side (
		.clk_atb_s(async_bridge_slv_side_clk_dst_porting),
		.rstn_atb_s(async_bridge_slv_side_rst_dst_n_porting),
		.s_atvalid(async_bridge_slv_node_s_chan_porting_s_atvalid),
		.s_atready(async_bridge_slv_node_s_chan_porting_s_atready),
		.s_atbytes(async_bridge_slv_node_s_chan_porting_s_atbytes),
		.s_atdata(async_bridge_slv_node_s_chan_porting_s_atdata),
		.s_atid(async_bridge_slv_node_s_chan_porting_s_atid),
		.s_afvalid(async_bridge_slv_node_s_chan_porting_s_afvalid),
		.s_afready(async_bridge_slv_node_s_chan_porting_s_afready),
		.s_syncreq(async_bridge_slv_node_s_chan_porting_s_syncreq),
		.s_atwakeup(async_bridge_slv_node_s_chan_porting_s_atwakeup),
		.slv_full_zero(),
		.clk_atb_m(),
		.rstn_atb_m(),
		.m_atvalid(),
		.m_atready(),
		.m_atbytes(),
		.m_atdata(),
		.m_atid(),
		.m_afvalid(),
		.m_afready(),
		.m_syncreq(),
		.m_atwakeup(),
		.mst_full_zero(),
		.mst_read_idle());

endmodule
//[UHDL]Content End [md5:befd97d92d2442e9608138dfd6c88388]

