module atb_soc_harden_dn_wrap (
  input logic clk_core,
  input logic clk_async,
  input logic rst_n,
  input logic dsp_ss0_valid,
  input logic [127:0] dsp_ss0_data,
  input logic dsp_ss1_valid,
  input logic [127:0] dsp_ss1_data,
  input logic dsp_ss2_valid,
  input logic [127:0] dsp_ss2_data,
  input logic dsp_ss3_valid,
  input logic [127:0] dsp_ss3_data,
  input logic dsp_ss4_valid,
  input logic [127:0] dsp_ss4_data,
  input logic dsp_ss5_valid,
  input logic [127:0] dsp_ss5_data,
  input logic camera_ss_valid,
  input logic [127:0] camera_ss_data,
  input logic mipi_ss_valid,
  input logic [127:0] mipi_ss_data,
  output logic debug_tniu_ss_valid,
  output logic [127:0] debug_tniu_ss_data
);
  atb_soc_topo u_atb_soc_topo (
    .clk_core(clk_core),
    .clk_async(clk_async),
    .rst_n(rst_n),
    .dsp_ss0_valid(dsp_ss0_valid),
    .dsp_ss0_data(dsp_ss0_data),
    .dsp_ss1_valid(dsp_ss1_valid),
    .dsp_ss1_data(dsp_ss1_data),
    .dsp_ss2_valid(dsp_ss2_valid),
    .dsp_ss2_data(dsp_ss2_data),
    .dsp_ss3_valid(dsp_ss3_valid),
    .dsp_ss3_data(dsp_ss3_data),
    .dsp_ss4_valid(dsp_ss4_valid),
    .dsp_ss4_data(dsp_ss4_data),
    .dsp_ss5_valid(dsp_ss5_valid),
    .dsp_ss5_data(dsp_ss5_data),
    .camera_ss_valid(camera_ss_valid),
    .camera_ss_data(camera_ss_data),
    .mipi_ss_valid(mipi_ss_valid),
    .mipi_ss_data(mipi_ss_data),
    .debug_tniu_ss_valid(debug_tniu_ss_valid),
    .debug_tniu_ss_data(debug_tniu_ss_data)
  );
endmodule
