module sts_demo_iniu_sts_demo_iniu_wrap
    import sts_demo_iniu_lwnoc_sts_pack::*;
(
    input   logic                       clk_src,
    input   logic                       clk_dst,
    input   logic                       rstn_src,
    input   logic                       rstn_dst,
    input   logic [SRC_ID_WIDTH-1:0]    node_id,

    input   logic                       s_awvalid,
    output  logic                       s_awready,
    input   logic [AXI_AWID_WIDTH-1:0]  s_awid,
    input   logic [AXI_ADDR_WIDTH-1:0]  s_awaddr,
    input   logic [AXI_AWLEN_WIDTH-1:0] s_awlen,
    input   logic [2:0]                 s_awsize,
    input   logic [1:0]                 s_awburst,
    input   logic                       s_awlock,
    input   logic [3:0]                 s_awcache,
    input   logic [2:0]                 s_awprot,
    input   logic [3:0]                 s_awqos,
    input   logic [AXI_USER_WIDTH-1:0]  s_awuser,

    input   logic                       s_wvalid,
    output  logic                       s_wready,
    input   logic [AXI_DATA_WIDTH-1:0]  s_wdata,
    input   logic [AXI_STRB_WIDTH-1:0]  s_wstrb,
    input   logic                       s_wlast,

    output  logic                       s_bvalid,
    input   logic                       s_bready,
    output  logic [AXI_BID_WIDTH-1:0]   s_bid,
    output  logic [1:0]                 s_bresp,

    input   logic                       s_arvalid,
    output  logic                       s_arready,
    input   logic [AXI_ARID_WIDTH-1:0]  s_arid,
    input   logic [AXI_ADDR_WIDTH-1:0]  s_araddr,
    input   logic [AXI_ARLEN_WIDTH-1:0] s_arlen,
    input   logic [2:0]                 s_arsize,
    input   logic [1:0]                 s_arburst,
    input   logic                       s_arlock,
    input   logic [3:0]                 s_arcache,
    input   logic [2:0]                 s_arprot,
    input   logic [3:0]                 s_arqos,
    input   logic [AXI_USER_WIDTH-1:0]  s_aruser,

    output  logic                       s_rvalid,
    input   logic                       s_rready,
    output  logic [AXI_RID_WIDTH-1:0]   s_rid,
    output  logic [AXI_DATA_WIDTH-1:0]  s_rdata,
    output  logic [1:0]                 s_rresp,
    output  logic                       s_rlast,

    output  logic                       out_req_vld,
    input   logic                       out_req_rdy,
    output  sts_req_typ                 out_req_pld,
    input   logic                       in_rsp_vld,
    output  logic                       in_rsp_rdy,
    input   sts_rsp_typ                 in_rsp_pld
);

    localparam int unsigned ENTRY_NUM = `sts_demo_iniu_STS_DEMO_ADDR_MAP_ENTRY_NUM;
    localparam logic [ENTRY_NUM*AXI_ADDR_WIDTH-1:0] ADDR_MAP_BASE_TABLE = `sts_demo_iniu_STS_DEMO_ADDR_MAP_BASE_TABLE;
    localparam logic [ENTRY_NUM*AXI_ADDR_WIDTH-1:0] ADDR_MAP_MASK_TABLE = `sts_demo_iniu_STS_DEMO_ADDR_MAP_MASK_TABLE;
    localparam logic [ENTRY_NUM*TGT_ID_WIDTH-1:0] ADDR_MAP_TGT_ID_TABLE = `sts_demo_iniu_STS_DEMO_ADDR_MAP_TGT_ID_TABLE;

    sts_demo_iniu_sts_iniu_top #(
        .NODE_NUM                (`sts_demo_iniu_STS_DEMO_NODE_NUM),
        .ADDR_MAP_ENTRY_NUM      (ENTRY_NUM),
        .ADDR_MAP_BASE_TABLE     (ADDR_MAP_BASE_TABLE),
        .ADDR_MAP_MASK_TABLE     (ADDR_MAP_MASK_TABLE),
        .ADDR_MAP_TGT_ID_TABLE   (ADDR_MAP_TGT_ID_TABLE),
        .ADDR_MAP_DEFAULT_TGT_ID (`sts_demo_iniu_STS_DEMO_ADDR_MAP_DEFAULT_TGT_ID)
    ) u_sts_iniu_top (
        .clk_src             (clk_src),
        .clk_dst             (clk_dst),
        .rstn_src            (rstn_src),
        .rstn_dst            (rstn_dst),
        .node_id             (node_id),
        .flow_ctrl_busy      ('0),
        .flow_ctrl_update    (),
        .sts_iniu_s_awvalid  (s_awvalid),
        .sts_iniu_s_awready  (s_awready),
        .sts_iniu_s_awid     (s_awid),
        .sts_iniu_s_awaddr   (s_awaddr),
        .sts_iniu_s_awlen    (s_awlen),
        .sts_iniu_s_awsize   (s_awsize),
        .sts_iniu_s_awburst  (s_awburst),
        .sts_iniu_s_awlock   (s_awlock),
        .sts_iniu_s_awcache  (s_awcache),
        .sts_iniu_s_awprot   (s_awprot),
        .sts_iniu_s_awqos    (s_awqos),
        .sts_iniu_s_awuser   (s_awuser),
        .sts_iniu_s_wvalid   (s_wvalid),
        .sts_iniu_s_wready   (s_wready),
        .sts_iniu_s_wdata    (s_wdata),
        .sts_iniu_s_wstrb    (s_wstrb),
        .sts_iniu_s_wlast    (s_wlast),
        .sts_iniu_s_bvalid   (s_bvalid),
        .sts_iniu_s_bready   (s_bready),
        .sts_iniu_s_bid      (s_bid),
        .sts_iniu_s_bresp    (s_bresp),
        .sts_iniu_s_arvalid  (s_arvalid),
        .sts_iniu_s_arready  (s_arready),
        .sts_iniu_s_arid     (s_arid),
        .sts_iniu_s_araddr   (s_araddr),
        .sts_iniu_s_arlen    (s_arlen),
        .sts_iniu_s_arsize   (s_arsize),
        .sts_iniu_s_arburst  (s_arburst),
        .sts_iniu_s_arlock   (s_arlock),
        .sts_iniu_s_arcache  (s_arcache),
        .sts_iniu_s_arprot   (s_arprot),
        .sts_iniu_s_arqos    (s_arqos),
        .sts_iniu_s_aruser   (s_aruser),
        .sts_iniu_s_rvalid   (s_rvalid),
        .sts_iniu_s_rready   (s_rready),
        .sts_iniu_s_rid      (s_rid),
        .sts_iniu_s_rdata    (s_rdata),
        .sts_iniu_s_rresp    (s_rresp),
        .sts_iniu_s_rlast    (s_rlast),
        .out_req_vld         (out_req_vld),
        .out_req_rdy         (out_req_rdy),
        .out_req_pld         (out_req_pld),
        .in_rsp_vld          (in_rsp_vld),
        .in_rsp_rdy          (in_rsp_rdy),
        .in_rsp_pld          (in_rsp_pld),
        .sys_cti_event_in    ('0),
        .sys_cti_event_out   (),
        .noc_cti_event_out   (),
        .noc_cti_event_in    ('0),
        .sys_cti_channel_in  ('0),
        .sys_cti_channel_out (),
        .noc_cti_channel_out (),
        .noc_cti_channel_in  ('0),
        .dbg_timestamp_in    ('0),
        .dbg_timestamp_out   (),
        .dbg_data_in         ('0),
        .dbg_data_out        ()
    );

endmodule
