module atb_soc_harden_dn_wrap (
  input logic clk_core,
  input logic clk_async,
  input logic rst_n,
  input logic dsp_ss0_atvalid,
  output logic dsp_ss0_atready,
  input logic [3:0] dsp_ss0_atbytes,
  input logic [127:0] dsp_ss0_atdata,
  input logic [6:0] dsp_ss0_atid,
  output logic dsp_ss0_afvalid,
  input logic dsp_ss0_afready,
  output logic dsp_ss0_syncreq,
  input logic dsp_ss0_atwakeup,
  input logic dsp_ss0_preq,
  input logic [1:0] dsp_ss0_pstate,
  output logic [1:0] dsp_ss0_pactive,
  output logic dsp_ss0_paccept,
  output logic dsp_ss0_pdeny,
  input logic dsp_ss1_atvalid,
  output logic dsp_ss1_atready,
  input logic [3:0] dsp_ss1_atbytes,
  input logic [127:0] dsp_ss1_atdata,
  input logic [6:0] dsp_ss1_atid,
  output logic dsp_ss1_afvalid,
  input logic dsp_ss1_afready,
  output logic dsp_ss1_syncreq,
  input logic dsp_ss1_atwakeup,
  input logic dsp_ss1_preq,
  input logic [1:0] dsp_ss1_pstate,
  output logic [1:0] dsp_ss1_pactive,
  output logic dsp_ss1_paccept,
  output logic dsp_ss1_pdeny,
  input logic dsp_ss2_atvalid,
  output logic dsp_ss2_atready,
  input logic [3:0] dsp_ss2_atbytes,
  input logic [127:0] dsp_ss2_atdata,
  input logic [6:0] dsp_ss2_atid,
  output logic dsp_ss2_afvalid,
  input logic dsp_ss2_afready,
  output logic dsp_ss2_syncreq,
  input logic dsp_ss2_atwakeup,
  input logic dsp_ss2_preq,
  input logic [1:0] dsp_ss2_pstate,
  output logic [1:0] dsp_ss2_pactive,
  output logic dsp_ss2_paccept,
  output logic dsp_ss2_pdeny,
  input logic dsp_ss3_atvalid,
  output logic dsp_ss3_atready,
  input logic [3:0] dsp_ss3_atbytes,
  input logic [127:0] dsp_ss3_atdata,
  input logic [6:0] dsp_ss3_atid,
  output logic dsp_ss3_afvalid,
  input logic dsp_ss3_afready,
  output logic dsp_ss3_syncreq,
  input logic dsp_ss3_atwakeup,
  input logic dsp_ss3_preq,
  input logic [1:0] dsp_ss3_pstate,
  output logic [1:0] dsp_ss3_pactive,
  output logic dsp_ss3_paccept,
  output logic dsp_ss3_pdeny,
  input logic dsp_ss4_atvalid,
  output logic dsp_ss4_atready,
  input logic [3:0] dsp_ss4_atbytes,
  input logic [127:0] dsp_ss4_atdata,
  input logic [6:0] dsp_ss4_atid,
  output logic dsp_ss4_afvalid,
  input logic dsp_ss4_afready,
  output logic dsp_ss4_syncreq,
  input logic dsp_ss4_atwakeup,
  input logic dsp_ss4_preq,
  input logic [1:0] dsp_ss4_pstate,
  output logic [1:0] dsp_ss4_pactive,
  output logic dsp_ss4_paccept,
  output logic dsp_ss4_pdeny,
  input logic dsp_ss5_atvalid,
  output logic dsp_ss5_atready,
  input logic [3:0] dsp_ss5_atbytes,
  input logic [127:0] dsp_ss5_atdata,
  input logic [6:0] dsp_ss5_atid,
  output logic dsp_ss5_afvalid,
  input logic dsp_ss5_afready,
  output logic dsp_ss5_syncreq,
  input logic dsp_ss5_atwakeup,
  input logic dsp_ss5_preq,
  input logic [1:0] dsp_ss5_pstate,
  output logic [1:0] dsp_ss5_pactive,
  output logic dsp_ss5_paccept,
  output logic dsp_ss5_pdeny,
  input logic camera_ss_atvalid,
  output logic camera_ss_atready,
  input logic [3:0] camera_ss_atbytes,
  input logic [127:0] camera_ss_atdata,
  input logic [6:0] camera_ss_atid,
  output logic camera_ss_afvalid,
  input logic camera_ss_afready,
  output logic camera_ss_syncreq,
  input logic camera_ss_atwakeup,
  input logic camera_ss_preq,
  input logic [1:0] camera_ss_pstate,
  output logic [1:0] camera_ss_pactive,
  output logic camera_ss_paccept,
  output logic camera_ss_pdeny,
  input logic mipi_ss_atvalid,
  output logic mipi_ss_atready,
  input logic [3:0] mipi_ss_atbytes,
  input logic [127:0] mipi_ss_atdata,
  input logic [6:0] mipi_ss_atid,
  output logic mipi_ss_afvalid,
  input logic mipi_ss_afready,
  output logic mipi_ss_syncreq,
  input logic mipi_ss_atwakeup,
  input logic mipi_ss_preq,
  input logic [1:0] mipi_ss_pstate,
  output logic [1:0] mipi_ss_pactive,
  output logic mipi_ss_paccept,
  output logic mipi_ss_pdeny,
  output logic debug_tniu_ss_atvalid,
  input logic debug_tniu_ss_atready,
  output logic [3:0] debug_tniu_ss_atbytes,
  output logic [127:0] debug_tniu_ss_atdata,
  output logic [6:0] debug_tniu_ss_atid,
  input logic debug_tniu_ss_afvalid,
  output logic debug_tniu_ss_afready,
  input logic debug_tniu_ss_syncreq,
  output logic debug_tniu_ss_atwakeup,
  input logic debug_tniu_ss_preq,
  input logic [1:0] debug_tniu_ss_pstate,
  output logic [1:0] debug_tniu_ss_pactive,
  output logic debug_tniu_ss_paccept,
  output logic debug_tniu_ss_pdeny
);
  atb_soc_topo u_atb_soc_topo (
    .clk_core(clk_core),
    .clk_async(clk_async),
    .rst_n(rst_n),
    .dsp_ss0_atvalid(dsp_ss0_atvalid),
    .dsp_ss0_atready(dsp_ss0_atready),
    .dsp_ss0_atbytes(dsp_ss0_atbytes),
    .dsp_ss0_atdata(dsp_ss0_atdata),
    .dsp_ss0_atid(dsp_ss0_atid),
    .dsp_ss0_afvalid(dsp_ss0_afvalid),
    .dsp_ss0_afready(dsp_ss0_afready),
    .dsp_ss0_syncreq(dsp_ss0_syncreq),
    .dsp_ss0_atwakeup(dsp_ss0_atwakeup),
    .dsp_ss0_preq(dsp_ss0_preq),
    .dsp_ss0_pstate(dsp_ss0_pstate),
    .dsp_ss0_pactive(dsp_ss0_pactive),
    .dsp_ss0_paccept(dsp_ss0_paccept),
    .dsp_ss0_pdeny(dsp_ss0_pdeny),
    .dsp_ss1_atvalid(dsp_ss1_atvalid),
    .dsp_ss1_atready(dsp_ss1_atready),
    .dsp_ss1_atbytes(dsp_ss1_atbytes),
    .dsp_ss1_atdata(dsp_ss1_atdata),
    .dsp_ss1_atid(dsp_ss1_atid),
    .dsp_ss1_afvalid(dsp_ss1_afvalid),
    .dsp_ss1_afready(dsp_ss1_afready),
    .dsp_ss1_syncreq(dsp_ss1_syncreq),
    .dsp_ss1_atwakeup(dsp_ss1_atwakeup),
    .dsp_ss1_preq(dsp_ss1_preq),
    .dsp_ss1_pstate(dsp_ss1_pstate),
    .dsp_ss1_pactive(dsp_ss1_pactive),
    .dsp_ss1_paccept(dsp_ss1_paccept),
    .dsp_ss1_pdeny(dsp_ss1_pdeny),
    .dsp_ss2_atvalid(dsp_ss2_atvalid),
    .dsp_ss2_atready(dsp_ss2_atready),
    .dsp_ss2_atbytes(dsp_ss2_atbytes),
    .dsp_ss2_atdata(dsp_ss2_atdata),
    .dsp_ss2_atid(dsp_ss2_atid),
    .dsp_ss2_afvalid(dsp_ss2_afvalid),
    .dsp_ss2_afready(dsp_ss2_afready),
    .dsp_ss2_syncreq(dsp_ss2_syncreq),
    .dsp_ss2_atwakeup(dsp_ss2_atwakeup),
    .dsp_ss2_preq(dsp_ss2_preq),
    .dsp_ss2_pstate(dsp_ss2_pstate),
    .dsp_ss2_pactive(dsp_ss2_pactive),
    .dsp_ss2_paccept(dsp_ss2_paccept),
    .dsp_ss2_pdeny(dsp_ss2_pdeny),
    .dsp_ss3_atvalid(dsp_ss3_atvalid),
    .dsp_ss3_atready(dsp_ss3_atready),
    .dsp_ss3_atbytes(dsp_ss3_atbytes),
    .dsp_ss3_atdata(dsp_ss3_atdata),
    .dsp_ss3_atid(dsp_ss3_atid),
    .dsp_ss3_afvalid(dsp_ss3_afvalid),
    .dsp_ss3_afready(dsp_ss3_afready),
    .dsp_ss3_syncreq(dsp_ss3_syncreq),
    .dsp_ss3_atwakeup(dsp_ss3_atwakeup),
    .dsp_ss3_preq(dsp_ss3_preq),
    .dsp_ss3_pstate(dsp_ss3_pstate),
    .dsp_ss3_pactive(dsp_ss3_pactive),
    .dsp_ss3_paccept(dsp_ss3_paccept),
    .dsp_ss3_pdeny(dsp_ss3_pdeny),
    .dsp_ss4_atvalid(dsp_ss4_atvalid),
    .dsp_ss4_atready(dsp_ss4_atready),
    .dsp_ss4_atbytes(dsp_ss4_atbytes),
    .dsp_ss4_atdata(dsp_ss4_atdata),
    .dsp_ss4_atid(dsp_ss4_atid),
    .dsp_ss4_afvalid(dsp_ss4_afvalid),
    .dsp_ss4_afready(dsp_ss4_afready),
    .dsp_ss4_syncreq(dsp_ss4_syncreq),
    .dsp_ss4_atwakeup(dsp_ss4_atwakeup),
    .dsp_ss4_preq(dsp_ss4_preq),
    .dsp_ss4_pstate(dsp_ss4_pstate),
    .dsp_ss4_pactive(dsp_ss4_pactive),
    .dsp_ss4_paccept(dsp_ss4_paccept),
    .dsp_ss4_pdeny(dsp_ss4_pdeny),
    .dsp_ss5_atvalid(dsp_ss5_atvalid),
    .dsp_ss5_atready(dsp_ss5_atready),
    .dsp_ss5_atbytes(dsp_ss5_atbytes),
    .dsp_ss5_atdata(dsp_ss5_atdata),
    .dsp_ss5_atid(dsp_ss5_atid),
    .dsp_ss5_afvalid(dsp_ss5_afvalid),
    .dsp_ss5_afready(dsp_ss5_afready),
    .dsp_ss5_syncreq(dsp_ss5_syncreq),
    .dsp_ss5_atwakeup(dsp_ss5_atwakeup),
    .dsp_ss5_preq(dsp_ss5_preq),
    .dsp_ss5_pstate(dsp_ss5_pstate),
    .dsp_ss5_pactive(dsp_ss5_pactive),
    .dsp_ss5_paccept(dsp_ss5_paccept),
    .dsp_ss5_pdeny(dsp_ss5_pdeny),
    .camera_ss_atvalid(camera_ss_atvalid),
    .camera_ss_atready(camera_ss_atready),
    .camera_ss_atbytes(camera_ss_atbytes),
    .camera_ss_atdata(camera_ss_atdata),
    .camera_ss_atid(camera_ss_atid),
    .camera_ss_afvalid(camera_ss_afvalid),
    .camera_ss_afready(camera_ss_afready),
    .camera_ss_syncreq(camera_ss_syncreq),
    .camera_ss_atwakeup(camera_ss_atwakeup),
    .camera_ss_preq(camera_ss_preq),
    .camera_ss_pstate(camera_ss_pstate),
    .camera_ss_pactive(camera_ss_pactive),
    .camera_ss_paccept(camera_ss_paccept),
    .camera_ss_pdeny(camera_ss_pdeny),
    .mipi_ss_atvalid(mipi_ss_atvalid),
    .mipi_ss_atready(mipi_ss_atready),
    .mipi_ss_atbytes(mipi_ss_atbytes),
    .mipi_ss_atdata(mipi_ss_atdata),
    .mipi_ss_atid(mipi_ss_atid),
    .mipi_ss_afvalid(mipi_ss_afvalid),
    .mipi_ss_afready(mipi_ss_afready),
    .mipi_ss_syncreq(mipi_ss_syncreq),
    .mipi_ss_atwakeup(mipi_ss_atwakeup),
    .mipi_ss_preq(mipi_ss_preq),
    .mipi_ss_pstate(mipi_ss_pstate),
    .mipi_ss_pactive(mipi_ss_pactive),
    .mipi_ss_paccept(mipi_ss_paccept),
    .mipi_ss_pdeny(mipi_ss_pdeny),
    .debug_tniu_ss_atvalid(debug_tniu_ss_atvalid),
    .debug_tniu_ss_atready(debug_tniu_ss_atready),
    .debug_tniu_ss_atbytes(debug_tniu_ss_atbytes),
    .debug_tniu_ss_atdata(debug_tniu_ss_atdata),
    .debug_tniu_ss_atid(debug_tniu_ss_atid),
    .debug_tniu_ss_afvalid(debug_tniu_ss_afvalid),
    .debug_tniu_ss_afready(debug_tniu_ss_afready),
    .debug_tniu_ss_syncreq(debug_tniu_ss_syncreq),
    .debug_tniu_ss_atwakeup(debug_tniu_ss_atwakeup),
    .debug_tniu_ss_preq(debug_tniu_ss_preq),
    .debug_tniu_ss_pstate(debug_tniu_ss_pstate),
    .debug_tniu_ss_pactive(debug_tniu_ss_pactive),
    .debug_tniu_ss_paccept(debug_tniu_ss_paccept),
    .debug_tniu_ss_pdeny(debug_tniu_ss_pdeny)
  );
endmodule
