package ucie_ss_iniu_interrupt_iniu_pkg;

    //===========================================================================
    // user defined parameters — driven by INTR_INIU_* macros from interrupt_iniu_define.sv
    //===========================================================================
    localparam integer unsigned OVERFLOW_TGT_ID         = `ucie_ss_iniu_INTR_INIU_OVERFLOW_TGT_ID;
    localparam integer unsigned OVERFLOW_TGT_INTR_ID    = `ucie_ss_iniu_INTR_INIU_OVERFLOW_TGT_INTR_ID;

    //===========================================================================
    // event recorder parameters
    //===========================================================================
    localparam integer unsigned INTERRUPT_MAX_NUM       = `ucie_ss_iniu_INTR_INIU_INTERRUPT_MAX_NUM;
    localparam integer unsigned INTERRUPT_MAXNUM_WIDTH  = $clog2(INTERRUPT_MAX_NUM);

    localparam integer unsigned NIU_ID_WIDTH             = `ucie_ss_iniu_INTR_INIU_NIU_ID_WIDTH;
    localparam integer unsigned INTR_ID_WIDTH            = `ucie_ss_iniu_INTR_INIU_INTR_ID_WIDTH;
    localparam integer unsigned INTR_LUT_BASE_ADDR       = `ucie_ss_iniu_INTR_INIU_LUT_BASE_ADDR;
    localparam integer unsigned INTR_PULSE_MODE_BASE_ADDR = `ucie_ss_iniu_INTR_INIU_PULSE_MODE_BASE_ADDR;

    localparam integer unsigned EVENT_COUNT_MAX     = `ucie_ss_iniu_INTR_INIU_EVENT_COUNT_MAX;
    localparam integer unsigned EVENT_COUNT_WIDTH   = $clog2(EVENT_COUNT_MAX + 1);

    localparam integer unsigned ARB_LEVEL_0         = `ucie_ss_iniu_INTR_INIU_ARB_LEVEL_0;    //16
    localparam integer unsigned ARB_LEVEL_1         = `ucie_ss_iniu_INTR_INIU_ARB_LEVEL_1;    //512
    localparam integer unsigned ARB_LEVEL_2         = `ucie_ss_iniu_INTR_INIU_ARB_LEVEL_2;    //4096

    localparam integer unsigned IDLE_DELAY_MAX      = `ucie_ss_iniu_INTR_INIU_IDLE_DELAY_MAX;

    localparam integer unsigned EVENT_REQ     = `ucie_ss_iniu_INTR_INIU_EVENT_REQ;
    localparam integer unsigned APB_REQ       = `ucie_ss_iniu_INTR_INIU_APB_REQ;
    typedef struct packed{
        logic                               toggle_flag;
        logic                               overflow;
        logic [INTERRUPT_MAXNUM_WIDTH-1:0]  intr_addr;

    } recorder_pkg;

    typedef struct packed{
        logic                                   srcid;
        logic [INTERRUPT_MAXNUM_WIDTH-1:0]      addr;
        logic                                   toggle_flag;
        logic                                   overflow;
    } event_apb_arb_pkg;

    typedef struct packed{
        logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        // logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
    } lut_pkg;

    typedef struct packed{
        logic [NIU_ID_WIDTH-1   :0]        tgt_id;
        logic [INTR_ID_WIDTH-1  :0]        tgt_intr_id;
        // logic [NIU_ID_WIDTH-1   :0]        src_id;
        logic [INTR_ID_WIDTH-1  :0]        src_intr_id;
        logic                              toggle_flag;
        logic                              internal_init; // used to indicate if the event is generated by internal initialization
        logic [$clog2($bits(lut_pkg))-1:0] ecc; // used to indicate the interrupt address
    } ecc_pkg;



endpackage
